// AUTO-GENERATED by scripts/generate-component-metadata.mjs — do not edit
// Source: api.star-citizen.wiki @ 2026-06-09T22:19:42.244Z

export interface ComponentMeta { itemClass?: string; grade?: string }

export const COMPONENT_METADATA: Record<string, ComponentMeta> = {
  "LIVEfiles\\libs\\foundry\\records\\crafting\\blueprints\\crafting\\vehiclegear\\cooler\\bp_craft_cool_acom_s01_iceplunge_scitem.json": {
    "itemClass": "competition",
    "grade": "C"
  },
  "LIVEfiles\\libs\\foundry\\records\\crafting\\blueprints\\crafting\\vehiclegear\\cooler\\bp_craft_cool_acom_s01_quickcool_scitem.json": {
    "itemClass": "competition",
    "grade": "D"
  },
  "LIVEfiles\\libs\\foundry\\records\\crafting\\blueprints\\crafting\\vehiclegear\\cooler\\bp_craft_cool_acom_s01_zerorush_scitem.json": {
    "itemClass": "competition",
    "grade": "B"
  },
  "LIVEfiles\\libs\\foundry\\records\\crafting\\blueprints\\crafting\\vehiclegear\\cooler\\bp_craft_cool_acom_s02_absolutezero_scitem.json": {
    "itemClass": "competition",
    "grade": "B"
  },
  "LIVEfiles\\libs\\foundry\\records\\crafting\\blueprints\\crafting\\vehiclegear\\cooler\\bp_craft_cool_acom_s02_icedive_scitem.json": {
    "itemClass": "competition",
    "grade": "C"
  },
  "LIVEfiles\\libs\\foundry\\records\\crafting\\blueprints\\crafting\\vehiclegear\\cooler\\bp_craft_cool_acom_s02_rapidcool_scitem.json": {
    "itemClass": "competition",
    "grade": "D"
  },
  "LIVEfiles\\libs\\foundry\\records\\crafting\\blueprints\\crafting\\vehiclegear\\cooler\\bp_craft_cool_aegs_s01_bracer_scitem.json": {
    "itemClass": "military",
    "grade": "C"
  },
  "LIVEfiles\\libs\\foundry\\records\\crafting\\blueprints\\crafting\\vehiclegear\\cooler\\bp_craft_cool_aegs_s01_glacier_scitem.json": {
    "itemClass": "military",
    "grade": "A"
  },
  "LIVEfiles\\libs\\foundry\\records\\crafting\\blueprints\\crafting\\vehiclegear\\cooler\\bp_craft_cool_aegs_s01_polar_scitem.json": {
    "itemClass": "military",
    "grade": "B"
  },
  "LIVEfiles\\libs\\foundry\\records\\crafting\\blueprints\\crafting\\vehiclegear\\cooler\\bp_craft_cool_aegs_s01_tundra_scitem.json": {
    "itemClass": "military",
    "grade": "D"
  },
  "LIVEfiles\\libs\\foundry\\records\\crafting\\blueprints\\crafting\\vehiclegear\\cooler\\bp_craft_cool_aegs_s02_arctic_scitem.json": {
    "itemClass": "military",
    "grade": "C"
  },
  "LIVEfiles\\libs\\foundry\\records\\crafting\\blueprints\\crafting\\vehiclegear\\cooler\\bp_craft_cool_aegs_s02_avalanche_scitem.json": {
    "itemClass": "military",
    "grade": "A"
  },
  "LIVEfiles\\libs\\foundry\\records\\crafting\\blueprints\\crafting\\vehiclegear\\cooler\\bp_craft_cool_aegs_s02_boreal_scitem.json": {
    "itemClass": "military",
    "grade": "D"
  },
  "LIVEfiles\\libs\\foundry\\records\\crafting\\blueprints\\crafting\\vehiclegear\\cooler\\bp_craft_cool_aegs_s02_permafrost_scitem.json": {
    "itemClass": "military",
    "grade": "B"
  },
  "LIVEfiles\\libs\\foundry\\records\\crafting\\blueprints\\crafting\\vehiclegear\\cooler\\bp_craft_cool_aegs_s03_blizzard_scitem.json": {
    "itemClass": "military",
    "grade": "A"
  },
  "LIVEfiles\\libs\\foundry\\records\\crafting\\blueprints\\crafting\\vehiclegear\\cooler\\bp_craft_cool_aegs_s03_galinstan_scitem.json": {
    "itemClass": "military",
    "grade": "D"
  },
  "LIVEfiles\\libs\\foundry\\records\\crafting\\blueprints\\crafting\\vehiclegear\\cooler\\bp_craft_cool_aegs_s03_mercury_scitem.json": {
    "itemClass": "military",
    "grade": "C"
  },
  "LIVEfiles\\libs\\foundry\\records\\crafting\\blueprints\\crafting\\vehiclegear\\cooler\\bp_craft_cool_aegs_s03_tempest_scitem.json": {
    "itemClass": "military",
    "grade": "B"
  },
  "LIVEfiles\\libs\\foundry\\records\\crafting\\blueprints\\crafting\\vehiclegear\\cooler\\bp_craft_cool_aegs_s04_idris_scitem.json": {
    "grade": "A"
  },
  "LIVEfiles\\libs\\foundry\\records\\crafting\\blueprints\\crafting\\vehiclegear\\cooler\\bp_craft_cool_aegs_s04_reclaimer.json": {
    "itemClass": "industrial",
    "grade": "A"
  },
  "LIVEfiles\\libs\\foundry\\records\\crafting\\blueprints\\crafting\\vehiclegear\\cooler\\bp_craft_cool_jspn_s00_cryostarsl_scitem.json": {
    "itemClass": "civilian",
    "grade": "B"
  },
  "LIVEfiles\\libs\\foundry\\records\\crafting\\blueprints\\crafting\\vehiclegear\\cooler\\bp_craft_cool_jspn_s00_froststarsl_scitem.json": {
    "itemClass": "civilian",
    "grade": "C"
  },
  "LIVEfiles\\libs\\foundry\\records\\crafting\\blueprints\\crafting\\vehiclegear\\cooler\\bp_craft_cool_jspn_s00_winterstarsl_scitem.json": {
    "itemClass": "civilian",
    "grade": "D"
  },
  "LIVEfiles\\libs\\foundry\\records\\crafting\\blueprints\\crafting\\vehiclegear\\cooler\\bp_craft_cool_jspn_s01_cryostar_scitem.json": {
    "itemClass": "civilian",
    "grade": "B"
  },
  "LIVEfiles\\libs\\foundry\\records\\crafting\\blueprints\\crafting\\vehiclegear\\cooler\\bp_craft_cool_jspn_s01_froststar_scitem.json": {
    "itemClass": "civilian",
    "grade": "C"
  },
  "LIVEfiles\\libs\\foundry\\records\\crafting\\blueprints\\crafting\\vehiclegear\\cooler\\bp_craft_cool_jspn_s01_winterstar_scitem.json": {
    "itemClass": "civilian",
    "grade": "D"
  },
  "LIVEfiles\\libs\\foundry\\records\\crafting\\blueprints\\crafting\\vehiclegear\\cooler\\bp_craft_cool_jspn_s02_cryostarex_scitem.json": {
    "itemClass": "civilian",
    "grade": "B"
  },
  "LIVEfiles\\libs\\foundry\\records\\crafting\\blueprints\\crafting\\vehiclegear\\cooler\\bp_craft_cool_jspn_s02_froststarex_scitem.json": {
    "itemClass": "civilian",
    "grade": "C"
  },
  "LIVEfiles\\libs\\foundry\\records\\crafting\\blueprints\\crafting\\vehiclegear\\cooler\\bp_craft_cool_jspn_s02_winterstarex_scitem.json": {
    "itemClass": "civilian",
    "grade": "D"
  },
  "LIVEfiles\\libs\\foundry\\records\\crafting\\blueprints\\crafting\\vehiclegear\\cooler\\bp_craft_cool_jspn_s03_cryostarxl_scitem.json": {
    "itemClass": "civilian",
    "grade": "B"
  },
  "LIVEfiles\\libs\\foundry\\records\\crafting\\blueprints\\crafting\\vehiclegear\\cooler\\bp_craft_cool_jspn_s03_froststarxl_scitem.json": {
    "itemClass": "civilian",
    "grade": "C"
  },
  "LIVEfiles\\libs\\foundry\\records\\crafting\\blueprints\\crafting\\vehiclegear\\cooler\\bp_craft_cool_jspn_s03_winterstarxl_scitem.json": {
    "itemClass": "civilian",
    "grade": "D"
  },
  "LIVEfiles\\libs\\foundry\\records\\crafting\\blueprints\\crafting\\vehiclegear\\cooler\\bp_craft_cool_just_s01_ecoflow_scitem.json": {
    "itemClass": "industrial",
    "grade": "B"
  },
  "LIVEfiles\\libs\\foundry\\records\\crafting\\blueprints\\crafting\\vehiclegear\\cooler\\bp_craft_cool_just_s01_hydrocel_scitem.json": {
    "itemClass": "industrial",
    "grade": "D"
  },
  "LIVEfiles\\libs\\foundry\\records\\crafting\\blueprints\\crafting\\vehiclegear\\cooler\\bp_craft_cool_just_s01_thermax_scitem.json": {
    "itemClass": "industrial",
    "grade": "C"
  },
  "LIVEfiles\\libs\\foundry\\records\\crafting\\blueprints\\crafting\\vehiclegear\\cooler\\bp_craft_cool_just_s01_ultraflow_scitem.json": {
    "itemClass": "industrial",
    "grade": "A"
  },
  "LIVEfiles\\libs\\foundry\\records\\crafting\\blueprints\\crafting\\vehiclegear\\cooler\\bp_craft_cool_just_s02_coolcore_scitem.json": {
    "itemClass": "industrial",
    "grade": "C"
  },
  "LIVEfiles\\libs\\foundry\\records\\crafting\\blueprints\\crafting\\vehiclegear\\cooler\\bp_craft_cool_just_s02_hydrojet_scitem.json": {
    "itemClass": "industrial",
    "grade": "D"
  },
  "LIVEfiles\\libs\\foundry\\records\\crafting\\blueprints\\crafting\\vehiclegear\\cooler\\bp_craft_cool_just_s02_snowfall_scitem.json": {
    "itemClass": "industrial",
    "grade": "B"
  },
  "LIVEfiles\\libs\\foundry\\records\\crafting\\blueprints\\crafting\\vehiclegear\\cooler\\bp_craft_cool_just_s02_snowpack_scitem.json": {
    "itemClass": "industrial",
    "grade": "A"
  },
  "LIVEfiles\\libs\\foundry\\records\\crafting\\blueprints\\crafting\\vehiclegear\\cooler\\bp_craft_cool_just_s03_chillmax_scitem.json": {
    "itemClass": "industrial",
    "grade": "A"
  },
  "LIVEfiles\\libs\\foundry\\records\\crafting\\blueprints\\crafting\\vehiclegear\\cooler\\bp_craft_cool_just_s03_hydropulse_scitem.json": {
    "itemClass": "industrial",
    "grade": "D"
  },
  "LIVEfiles\\libs\\foundry\\records\\crafting\\blueprints\\crafting\\vehiclegear\\cooler\\bp_craft_cool_just_s03_iceflush_scitem.json": {
    "itemClass": "industrial",
    "grade": "B"
  },
  "LIVEfiles\\libs\\foundry\\records\\crafting\\blueprints\\crafting\\vehiclegear\\cooler\\bp_craft_cool_just_s03_thermalcore_scitem.json": {
    "itemClass": "industrial",
    "grade": "C"
  },
  "LIVEfiles\\libs\\foundry\\records\\crafting\\blueprints\\crafting\\vehiclegear\\cooler\\bp_craft_cool_lplt_s01_arcticstorm_scitem.json": {
    "itemClass": "civilian",
    "grade": "C"
  },
  "LIVEfiles\\libs\\foundry\\records\\crafting\\blueprints\\crafting\\vehiclegear\\cooler\\bp_craft_cool_lplt_s01_blastchill_scitem.json": {
    "itemClass": "civilian",
    "grade": "D"
  },
  "LIVEfiles\\libs\\foundry\\records\\crafting\\blueprints\\crafting\\vehiclegear\\cooler\\bp_craft_cool_lplt_s01_flashfreeze_scitem.json": {
    "itemClass": "civilian",
    "grade": "B"
  },
  "LIVEfiles\\libs\\foundry\\records\\crafting\\blueprints\\crafting\\vehiclegear\\cooler\\bp_craft_cool_lplt_s02_coldsnap_scitem.json": {
    "itemClass": "civilian",
    "grade": "C"
  },
  "LIVEfiles\\libs\\foundry\\records\\crafting\\blueprints\\crafting\\vehiclegear\\cooler\\bp_craft_cool_lplt_s02_fullfrost_scitem.json": {
    "itemClass": "civilian",
    "grade": "B"
  },
  "LIVEfiles\\libs\\foundry\\records\\crafting\\blueprints\\crafting\\vehiclegear\\cooler\\bp_craft_cool_lplt_s02_whiteout_scitem.json": {
    "itemClass": "civilian",
    "grade": "D"
  },
  "LIVEfiles\\libs\\foundry\\records\\crafting\\blueprints\\crafting\\vehiclegear\\cooler\\bp_craft_cool_lplt_s03_coldsurge_scitem.json": {
    "itemClass": "civilian",
    "grade": "D"
  },
  "LIVEfiles\\libs\\foundry\\records\\crafting\\blueprints\\crafting\\vehiclegear\\cooler\\bp_craft_cool_lplt_s03_frostbite_scitem.json": {
    "itemClass": "civilian",
    "grade": "B"
  },
  "LIVEfiles\\libs\\foundry\\records\\crafting\\blueprints\\crafting\\vehiclegear\\cooler\\bp_craft_cool_lplt_s03_frostburn_scitem.json": {
    "itemClass": "civilian",
    "grade": "C"
  },
  "LIVEfiles\\libs\\foundry\\records\\crafting\\blueprints\\crafting\\vehiclegear\\cooler\\bp_craft_cool_orig_s04_890j_scitem.json": {
    "itemClass": "civilian",
    "grade": "A"
  },
  "LIVEfiles\\libs\\foundry\\records\\crafting\\blueprints\\crafting\\vehiclegear\\cooler\\bp_craft_cool_rsi_s04_polaris_scitem.json": {
    "itemClass": "civilian",
    "grade": "A"
  },
  "LIVEfiles\\libs\\foundry\\records\\crafting\\blueprints\\crafting\\vehiclegear\\cooler\\bp_craft_cool_tydt_s01_heatsafe_scitem.json": {
    "itemClass": "stealth",
    "grade": "C"
  },
  "LIVEfiles\\libs\\foundry\\records\\crafting\\blueprints\\crafting\\vehiclegear\\cooler\\bp_craft_cool_tydt_s01_snowblind_scitem.json": {
    "itemClass": "stealth",
    "grade": "A"
  },
  "LIVEfiles\\libs\\foundry\\records\\crafting\\blueprints\\crafting\\vehiclegear\\cooler\\bp_craft_cool_tydt_s01_vaporblock_scitem.json": {
    "itemClass": "stealth",
    "grade": "B"
  },
  "LIVEfiles\\libs\\foundry\\records\\crafting\\blueprints\\crafting\\vehiclegear\\cooler\\bp_craft_cool_tydt_s02_heatsink_scitem.json": {
    "itemClass": "stealth",
    "grade": "C"
  },
  "LIVEfiles\\libs\\foundry\\records\\crafting\\blueprints\\crafting\\vehiclegear\\cooler\\bp_craft_cool_tydt_s02_icebox_scitem.json": {
    "itemClass": "stealth",
    "grade": "B"
  },
  "LIVEfiles\\libs\\foundry\\records\\crafting\\blueprints\\crafting\\vehiclegear\\cooler\\bp_craft_cool_tydt_s02_nightfall_scitem.json": {
    "itemClass": "stealth",
    "grade": "A"
  },
  "LIVEfiles\\libs\\foundry\\records\\crafting\\blueprints\\crafting\\vehiclegear\\cooler\\bp_craft_cool_wcpr_s00_fridan_scitem.json": {
    "itemClass": "civilian",
    "grade": "C"
  },
  "LIVEfiles\\libs\\foundry\\records\\crafting\\blueprints\\crafting\\vehiclegear\\cooler\\bp_craft_cool_wcpr_s00_kelvid_scitem.json": {
    "itemClass": "civilian",
    "grade": "B"
  },
  "LIVEfiles\\libs\\foundry\\records\\crafting\\blueprints\\crafting\\vehiclegear\\cooler\\bp_craft_cool_wcpr_s00_tepilo_scitem.json": {
    "itemClass": "civilian",
    "grade": "A"
  },
  "LIVEfiles\\libs\\foundry\\records\\crafting\\blueprints\\crafting\\vehiclegear\\cooler\\bp_craft_cool_wcpr_s01_berian_scitem.json": {
    "itemClass": "civilian",
    "grade": "C"
  },
  "LIVEfiles\\libs\\foundry\\records\\crafting\\blueprints\\crafting\\vehiclegear\\cooler\\bp_craft_cool_wcpr_s01_endo_scitem.json": {
    "itemClass": "civilian",
    "grade": "B"
  },
  "LIVEfiles\\libs\\foundry\\records\\crafting\\blueprints\\crafting\\vehiclegear\\cooler\\bp_craft_cool_wcpr_s01_gelid_scitem.json": {
    "itemClass": "civilian",
    "grade": "A"
  },
  "LIVEfiles\\libs\\foundry\\records\\crafting\\blueprints\\crafting\\vehiclegear\\cooler\\bp_craft_cool_wcpr_s02_aufeis_scitem.json": {
    "itemClass": "civilian",
    "grade": "A"
  },
  "LIVEfiles\\libs\\foundry\\records\\crafting\\blueprints\\crafting\\vehiclegear\\cooler\\bp_craft_cool_wcpr_s02_graupel_scitem.json": {
    "itemClass": "civilian",
    "grade": "C"
  },
  "LIVEfiles\\libs\\foundry\\records\\crafting\\blueprints\\crafting\\vehiclegear\\cooler\\bp_craft_cool_wcpr_s02_taiga_scitem.json": {
    "itemClass": "civilian",
    "grade": "B"
  },
  "LIVEfiles\\libs\\foundry\\records\\crafting\\blueprints\\crafting\\vehiclegear\\cooler\\bp_craft_cool_wcpr_s03_draug_scitem.json": {
    "itemClass": "civilian",
    "grade": "A"
  },
  "LIVEfiles\\libs\\foundry\\records\\crafting\\blueprints\\crafting\\vehiclegear\\cooler\\bp_craft_cool_wcpr_s03_elsen_scitem.json": {
    "itemClass": "civilian",
    "grade": "A"
  },
  "LIVEfiles\\libs\\foundry\\records\\crafting\\blueprints\\crafting\\vehiclegear\\cooler\\bp_craft_cool_wcpr_s03_kragen_scitem.json": {
    "itemClass": "civilian",
    "grade": "A"
  },
  "LIVEfiles\\libs\\foundry\\records\\crafting\\blueprints\\crafting\\vehiclegear\\mininglaser\\bp_craft_mining_laser_drak_golem_s1.json": {
    "grade": "A"
  },
  "LIVEfiles\\libs\\foundry\\records\\crafting\\blueprints\\crafting\\vehiclegear\\mininglaser\\bp_craft_mining_laser_grin_arbor_s0.json": {
    "grade": "A"
  },
  "LIVEfiles\\libs\\foundry\\records\\crafting\\blueprints\\crafting\\vehiclegear\\mininglaser\\bp_craft_mining_laser_grin_arbor_s1.json": {
    "grade": "A"
  },
  "LIVEfiles\\libs\\foundry\\records\\crafting\\blueprints\\crafting\\vehiclegear\\mininglaser\\bp_craft_mining_laser_grin_arbor_s2.json": {
    "grade": "A"
  },
  "LIVEfiles\\libs\\foundry\\records\\crafting\\blueprints\\crafting\\vehiclegear\\mininglaser\\bp_craft_mining_laser_grin_lancet_s1.json": {
    "grade": "A"
  },
  "LIVEfiles\\libs\\foundry\\records\\crafting\\blueprints\\crafting\\vehiclegear\\mininglaser\\bp_craft_mining_laser_grin_lancet_s2.json": {
    "grade": "A"
  },
  "LIVEfiles\\libs\\foundry\\records\\crafting\\blueprints\\crafting\\vehiclegear\\mininglaser\\bp_craft_mining_laser_shin_hofstede_s0.json": {
    "grade": "A"
  },
  "LIVEfiles\\libs\\foundry\\records\\crafting\\blueprints\\crafting\\vehiclegear\\mininglaser\\bp_craft_mining_laser_shin_hofstede_s1.json": {
    "grade": "A"
  },
  "LIVEfiles\\libs\\foundry\\records\\crafting\\blueprints\\crafting\\vehiclegear\\mininglaser\\bp_craft_mining_laser_shin_hofstede_s2.json": {
    "grade": "A"
  },
  "LIVEfiles\\libs\\foundry\\records\\crafting\\blueprints\\crafting\\vehiclegear\\mininglaser\\bp_craft_mining_laser_shin_klein_s0.json": {
    "grade": "A"
  },
  "LIVEfiles\\libs\\foundry\\records\\crafting\\blueprints\\crafting\\vehiclegear\\mininglaser\\bp_craft_mining_laser_shin_klein_s1.json": {
    "grade": "A"
  },
  "LIVEfiles\\libs\\foundry\\records\\crafting\\blueprints\\crafting\\vehiclegear\\mininglaser\\bp_craft_mining_laser_shin_klein_s2.json": {
    "grade": "A"
  },
  "LIVEfiles\\libs\\foundry\\records\\crafting\\blueprints\\crafting\\vehiclegear\\mininglaser\\bp_craft_mining_laser_thcn_helix_s0.json": {
    "grade": "A"
  },
  "LIVEfiles\\libs\\foundry\\records\\crafting\\blueprints\\crafting\\vehiclegear\\mininglaser\\bp_craft_mining_laser_thcn_helix_s1.json": {
    "grade": "A"
  },
  "LIVEfiles\\libs\\foundry\\records\\crafting\\blueprints\\crafting\\vehiclegear\\mininglaser\\bp_craft_mining_laser_thcn_helix_s2.json": {
    "grade": "A"
  },
  "LIVEfiles\\libs\\foundry\\records\\crafting\\blueprints\\crafting\\vehiclegear\\mininglaser\\bp_craft_mining_laser_thcn_impact_s1.json": {
    "grade": "A"
  },
  "LIVEfiles\\libs\\foundry\\records\\crafting\\blueprints\\crafting\\vehiclegear\\mininglaser\\bp_craft_mining_laser_thcn_impact_s2.json": {
    "grade": "A"
  },
  "LIVEfiles\\libs\\foundry\\records\\crafting\\blueprints\\crafting\\vehiclegear\\powerplant\\bp_craft_powr_acom_s01_lumacore_scitem.json": {
    "itemClass": "competition",
    "grade": "A"
  },
  "LIVEfiles\\libs\\foundry\\records\\crafting\\blueprints\\crafting\\vehiclegear\\powerplant\\bp_craft_powr_acom_s01_starheart_scitem.json": {
    "itemClass": "competition",
    "grade": "B"
  },
  "LIVEfiles\\libs\\foundry\\records\\crafting\\blueprints\\crafting\\vehiclegear\\powerplant\\bp_craft_powr_acom_s01_sunflare_scitem.json": {
    "itemClass": "competition",
    "grade": "C"
  },
  "LIVEfiles\\libs\\foundry\\records\\crafting\\blueprints\\crafting\\vehiclegear\\powerplant\\bp_craft_powr_acom_s02_luxcore_scitem.json": {
    "itemClass": "competition",
    "grade": "A"
  },
  "LIVEfiles\\libs\\foundry\\records\\crafting\\blueprints\\crafting\\vehiclegear\\powerplant\\bp_craft_powr_acom_s02_solarflare_scitem.json": {
    "itemClass": "competition",
    "grade": "C"
  },
  "LIVEfiles\\libs\\foundry\\records\\crafting\\blueprints\\crafting\\vehiclegear\\powerplant\\bp_craft_powr_acom_s02_starburn_scitem.json": {
    "itemClass": "competition",
    "grade": "B"
  },
  "LIVEfiles\\libs\\foundry\\records\\crafting\\blueprints\\crafting\\vehiclegear\\powerplant\\bp_craft_powr_aegs_s01_charger_scitem.json": {
    "itemClass": "military",
    "grade": "D"
  },
  "LIVEfiles\\libs\\foundry\\records\\crafting\\blueprints\\crafting\\vehiclegear\\powerplant\\bp_craft_powr_aegs_s01_fierellcascade_scitem.json": {
    "itemClass": "military",
    "grade": "B"
  },
  "LIVEfiles\\libs\\foundry\\records\\crafting\\blueprints\\crafting\\vehiclegear\\powerplant\\bp_craft_powr_aegs_s01_quadracell_scitem.json": {
    "itemClass": "military",
    "grade": "A"
  },
  "LIVEfiles\\libs\\foundry\\records\\crafting\\blueprints\\crafting\\vehiclegear\\powerplant\\bp_craft_powr_aegs_s01_regulus_scitem.json": {
    "itemClass": "military",
    "grade": "C"
  },
  "LIVEfiles\\libs\\foundry\\records\\crafting\\blueprints\\crafting\\vehiclegear\\powerplant\\bp_craft_powr_aegs_s02_bolide_scitem.json": {
    "itemClass": "military",
    "grade": "B"
  },
  "LIVEfiles\\libs\\foundry\\records\\crafting\\blueprints\\crafting\\vehiclegear\\powerplant\\bp_craft_powr_aegs_s02_maelstrom_scitem.json": {
    "itemClass": "military",
    "grade": "C"
  },
  "LIVEfiles\\libs\\foundry\\records\\crafting\\blueprints\\crafting\\vehiclegear\\powerplant\\bp_craft_powr_aegs_s02_quadracellmt_scitem.json": {
    "itemClass": "military",
    "grade": "A"
  },
  "LIVEfiles\\libs\\foundry\\records\\crafting\\blueprints\\crafting\\vehiclegear\\powerplant\\bp_craft_powr_aegs_s02_vortex_scitem.json": {
    "itemClass": "military",
    "grade": "D"
  },
  "LIVEfiles\\libs\\foundry\\records\\crafting\\blueprints\\crafting\\vehiclegear\\powerplant\\bp_craft_powr_aegs_s03_centurion_scitem.json": {
    "itemClass": "military",
    "grade": "C"
  },
  "LIVEfiles\\libs\\foundry\\records\\crafting\\blueprints\\crafting\\vehiclegear\\powerplant\\bp_craft_powr_aegs_s03_drassik_scitem.json": {
    "itemClass": "military",
    "grade": "D"
  },
  "LIVEfiles\\libs\\foundry\\records\\crafting\\blueprints\\crafting\\vehiclegear\\powerplant\\bp_craft_powr_aegs_s03_fulgur_scitem.json": {
    "itemClass": "military",
    "grade": "B"
  },
  "LIVEfiles\\libs\\foundry\\records\\crafting\\blueprints\\crafting\\vehiclegear\\powerplant\\bp_craft_powr_aegs_s03_quadracellmx_scitem.json": {
    "itemClass": "military",
    "grade": "A"
  },
  "LIVEfiles\\libs\\foundry\\records\\crafting\\blueprints\\crafting\\vehiclegear\\powerplant\\bp_craft_powr_aegs_s04_idris_scitem.json": {
    "grade": "A"
  },
  "LIVEfiles\\libs\\foundry\\records\\crafting\\blueprints\\crafting\\vehiclegear\\powerplant\\bp_craft_powr_aegs_s04_reclaimer_scitem.json": {
    "grade": "A"
  },
  "LIVEfiles\\libs\\foundry\\records\\crafting\\blueprints\\crafting\\vehiclegear\\powerplant\\bp_craft_powr_amrs_s01_dynaflux_scitem.json": {
    "itemClass": "military",
    "grade": "B"
  },
  "LIVEfiles\\libs\\foundry\\records\\crafting\\blueprints\\crafting\\vehiclegear\\powerplant\\bp_craft_powr_amrs_s01_hypergen_scitem.json": {
    "itemClass": "military",
    "grade": "D"
  },
  "LIVEfiles\\libs\\foundry\\records\\crafting\\blueprints\\crafting\\vehiclegear\\powerplant\\bp_craft_powr_amrs_s01_js300_scitem.json": {
    "itemClass": "military",
    "grade": "A"
  },
  "LIVEfiles\\libs\\foundry\\records\\crafting\\blueprints\\crafting\\vehiclegear\\powerplant\\bp_craft_powr_amrs_s01_overdrive_scitem.json": {
    "itemClass": "military",
    "grade": "C"
  },
  "LIVEfiles\\libs\\foundry\\records\\crafting\\blueprints\\crafting\\vehiclegear\\powerplant\\bp_craft_powr_amrs_s02_exogen_scitem.json": {
    "itemClass": "military",
    "grade": "D"
  },
  "LIVEfiles\\libs\\foundry\\records\\crafting\\blueprints\\crafting\\vehiclegear\\powerplant\\bp_craft_powr_amrs_s02_js400_scitem.json": {
    "itemClass": "military",
    "grade": "A"
  },
  "LIVEfiles\\libs\\foundry\\records\\crafting\\blueprints\\crafting\\vehiclegear\\powerplant\\bp_craft_powr_amrs_s02_turbodrive_scitem.json": {
    "itemClass": "military",
    "grade": "C"
  },
  "LIVEfiles\\libs\\foundry\\records\\crafting\\blueprints\\crafting\\vehiclegear\\powerplant\\bp_craft_powr_amrs_s02_ultraflux_scitem.json": {
    "itemClass": "military",
    "grade": "B"
  },
  "LIVEfiles\\libs\\foundry\\records\\crafting\\blueprints\\crafting\\vehiclegear\\powerplant\\bp_craft_powr_amrs_s03_js500_scitem.json": {
    "itemClass": "military",
    "grade": "A"
  },
  "LIVEfiles\\libs\\foundry\\records\\crafting\\blueprints\\crafting\\vehiclegear\\powerplant\\bp_craft_powr_amrs_s03_megaflux_scitem.json": {
    "itemClass": "military",
    "grade": "B"
  },
  "LIVEfiles\\libs\\foundry\\records\\crafting\\blueprints\\crafting\\vehiclegear\\powerplant\\bp_craft_powr_amrs_s03_smartgen_scitem.json": {
    "itemClass": "military",
    "grade": "D"
  },
  "LIVEfiles\\libs\\foundry\\records\\crafting\\blueprints\\crafting\\vehiclegear\\powerplant\\bp_craft_powr_amrs_s03_superdrive_scitem.json": {
    "itemClass": "military",
    "grade": "C"
  },
  "LIVEfiles\\libs\\foundry\\records\\crafting\\blueprints\\crafting\\vehiclegear\\powerplant\\bp_craft_powr_just_s00_defiant_scitem.json": {
    "itemClass": "industrial",
    "grade": "B"
  },
  "LIVEfiles\\libs\\foundry\\records\\crafting\\blueprints\\crafting\\vehiclegear\\powerplant\\bp_craft_powr_just_s00_jennet_scitem.json": {
    "itemClass": "industrial",
    "grade": "D"
  },
  "LIVEfiles\\libs\\foundry\\records\\crafting\\blueprints\\crafting\\vehiclegear\\powerplant\\bp_craft_powr_just_s00_steadfast_scitem.json": {
    "itemClass": "industrial",
    "grade": "C"
  },
  "LIVEfiles\\libs\\foundry\\records\\crafting\\blueprints\\crafting\\vehiclegear\\powerplant\\bp_craft_powr_just_s01_breton_scitem.json": {
    "itemClass": "industrial",
    "grade": "A"
  },
  "LIVEfiles\\libs\\foundry\\records\\crafting\\blueprints\\crafting\\vehiclegear\\powerplant\\bp_craft_powr_just_s01_endurance_scitem.json": {
    "itemClass": "industrial",
    "grade": "B"
  },
  "LIVEfiles\\libs\\foundry\\records\\crafting\\blueprints\\crafting\\vehiclegear\\powerplant\\bp_craft_powr_just_s01_fortitude_scitem.json": {
    "itemClass": "industrial",
    "grade": "C"
  },
  "LIVEfiles\\libs\\foundry\\records\\crafting\\blueprints\\crafting\\vehiclegear\\powerplant\\bp_craft_powr_just_s01_roughneck_scitem.json": {
    "itemClass": "industrial",
    "grade": "D"
  },
  "LIVEfiles\\libs\\foundry\\records\\crafting\\blueprints\\crafting\\vehiclegear\\powerplant\\bp_craft_powr_just_s02_diligence_scitem.json": {
    "itemClass": "industrial",
    "grade": "C"
  },
  "LIVEfiles\\libs\\foundry\\records\\crafting\\blueprints\\crafting\\vehiclegear\\powerplant\\bp_craft_powr_just_s02_genoa_scitem.json": {
    "itemClass": "industrial",
    "grade": "A"
  },
  "LIVEfiles\\libs\\foundry\\records\\crafting\\blueprints\\crafting\\vehiclegear\\powerplant\\bp_craft_powr_just_s02_sedulity_scitem.json": {
    "itemClass": "industrial",
    "grade": "B"
  },
  "LIVEfiles\\libs\\foundry\\records\\crafting\\blueprints\\crafting\\vehiclegear\\powerplant\\bp_craft_powr_just_s02_trommel_scitem.json": {
    "itemClass": "industrial",
    "grade": "D"
  },
  "LIVEfiles\\libs\\foundry\\records\\crafting\\blueprints\\crafting\\vehiclegear\\powerplant\\bp_craft_powr_just_s03_durango_scitem.json": {
    "itemClass": "industrial",
    "grade": "A"
  },
  "LIVEfiles\\libs\\foundry\\records\\crafting\\blueprints\\crafting\\vehiclegear\\powerplant\\bp_craft_powr_just_s03_ginzel_scitem.json": {
    "itemClass": "industrial",
    "grade": "C"
  },
  "LIVEfiles\\libs\\foundry\\records\\crafting\\blueprints\\crafting\\vehiclegear\\powerplant\\bp_craft_powr_just_s03_reliance_scitem.json": {
    "itemClass": "industrial",
    "grade": "B"
  },
  "LIVEfiles\\libs\\foundry\\records\\crafting\\blueprints\\crafting\\vehiclegear\\powerplant\\bp_craft_powr_lplt_s00_durajet_scitem.json": {
    "itemClass": "civilian",
    "grade": "D"
  },
  "LIVEfiles\\libs\\foundry\\records\\crafting\\blueprints\\crafting\\vehiclegear\\powerplant\\bp_craft_powr_lplt_s00_ionwave_scitem.json": {
    "itemClass": "civilian",
    "grade": "B"
  },
  "LIVEfiles\\libs\\foundry\\records\\crafting\\blueprints\\crafting\\vehiclegear\\powerplant\\bp_craft_powr_lplt_s00_radix_scitem.json": {
    "itemClass": "civilian",
    "grade": "C"
  },
  "LIVEfiles\\libs\\foundry\\records\\crafting\\blueprints\\crafting\\vehiclegear\\powerplant\\bp_craft_powr_lplt_s01_ionburst_scitem.json": {
    "itemClass": "civilian",
    "grade": "B"
  },
  "LIVEfiles\\libs\\foundry\\records\\crafting\\blueprints\\crafting\\vehiclegear\\powerplant\\bp_craft_powr_lplt_s01_powerbolt_scitem.json": {
    "itemClass": "civilian",
    "grade": "C"
  },
  "LIVEfiles\\libs\\foundry\\records\\crafting\\blueprints\\crafting\\vehiclegear\\powerplant\\bp_craft_powr_lplt_s01_zapjet_scitem.json": {
    "itemClass": "civilian",
    "grade": "D"
  },
  "LIVEfiles\\libs\\foundry\\records\\crafting\\blueprints\\crafting\\vehiclegear\\powerplant\\bp_craft_powr_lplt_s02_fullforce_scitem.json": {
    "itemClass": "civilian",
    "grade": "C"
  },
  "LIVEfiles\\libs\\foundry\\records\\crafting\\blueprints\\crafting\\vehiclegear\\powerplant\\bp_craft_powr_lplt_s02_ionsurge_scitem.json": {
    "itemClass": "civilian",
    "grade": "B"
  },
  "LIVEfiles\\libs\\foundry\\records\\crafting\\blueprints\\crafting\\vehiclegear\\powerplant\\bp_craft_powr_lplt_s02_sparkjet_scitem.json": {
    "itemClass": "civilian",
    "grade": "D"
  },
  "LIVEfiles\\libs\\foundry\\records\\crafting\\blueprints\\crafting\\vehiclegear\\powerplant\\bp_craft_powr_lplt_s03_fullforcepro_scitem.json": {
    "itemClass": "civilian",
    "grade": "C"
  },
  "LIVEfiles\\libs\\foundry\\records\\crafting\\blueprints\\crafting\\vehiclegear\\powerplant\\bp_craft_powr_lplt_s03_ionsurgepro_scitem.json": {
    "itemClass": "civilian",
    "grade": "B"
  },
  "LIVEfiles\\libs\\foundry\\records\\crafting\\blueprints\\crafting\\vehiclegear\\powerplant\\bp_craft_powr_lplt_s03_sparkjetpro_scitem.json": {
    "itemClass": "civilian",
    "grade": "D"
  },
  "LIVEfiles\\libs\\foundry\\records\\crafting\\blueprints\\crafting\\vehiclegear\\powerplant\\bp_craft_powr_orig_s04_890j_scitem.json": {
    "itemClass": "civilian",
    "grade": "A"
  },
  "LIVEfiles\\libs\\foundry\\records\\crafting\\blueprints\\crafting\\vehiclegear\\powerplant\\bp_craft_powr_rsi_s04_polaris_scitem.json": {
    "itemClass": "civilian",
    "grade": "A"
  },
  "LIVEfiles\\libs\\foundry\\records\\crafting\\blueprints\\crafting\\vehiclegear\\powerplant\\bp_craft_powr_sasu_s01_lightblossom_scitem.json": {
    "itemClass": "civilian",
    "grade": "C"
  },
  "LIVEfiles\\libs\\foundry\\records\\crafting\\blueprints\\crafting\\vehiclegear\\powerplant\\bp_craft_powr_sasu_s01_magnabloom_scitem.json": {
    "itemClass": "civilian",
    "grade": "B"
  },
  "LIVEfiles\\libs\\foundry\\records\\crafting\\blueprints\\crafting\\vehiclegear\\powerplant\\bp_craft_powr_sasu_s01_whiterose_scitem.json": {
    "itemClass": "civilian",
    "grade": "A"
  },
  "LIVEfiles\\libs\\foundry\\records\\crafting\\blueprints\\crafting\\vehiclegear\\powerplant\\bp_craft_powr_sasu_s02_daybreak_scitem.json": {
    "itemClass": "civilian",
    "grade": "C"
  },
  "LIVEfiles\\libs\\foundry\\records\\crafting\\blueprints\\crafting\\vehiclegear\\powerplant\\bp_craft_powr_sasu_s02_lotus_scitem.json": {
    "itemClass": "civilian",
    "grade": "A"
  },
  "LIVEfiles\\libs\\foundry\\records\\crafting\\blueprints\\crafting\\vehiclegear\\powerplant\\bp_craft_powr_sasu_s02_radiance_scitem.json": {
    "itemClass": "civilian",
    "grade": "B"
  },
  "LIVEfiles\\libs\\foundry\\records\\crafting\\blueprints\\crafting\\vehiclegear\\powerplant\\bp_craft_powr_sasu_s03_celestial_scitem.json": {
    "itemClass": "civilian",
    "grade": "B"
  },
  "LIVEfiles\\libs\\foundry\\records\\crafting\\blueprints\\crafting\\vehiclegear\\powerplant\\bp_craft_powr_sasu_s03_newdawn_scitem.json": {
    "itemClass": "civilian",
    "grade": "C"
  },
  "LIVEfiles\\libs\\foundry\\records\\crafting\\blueprints\\crafting\\vehiclegear\\powerplant\\bp_craft_powr_sasu_s03_tigerlilly_scitem.json": {
    "itemClass": "civilian",
    "grade": "A"
  },
  "LIVEfiles\\libs\\foundry\\records\\crafting\\blueprints\\crafting\\vehiclegear\\powerplant\\bp_craft_powr_tydt_s01_deltamax_scitem.json": {
    "itemClass": "stealth",
    "grade": "B"
  },
  "LIVEfiles\\libs\\foundry\\records\\crafting\\blueprints\\crafting\\vehiclegear\\powerplant\\bp_craft_powr_tydt_s01_slipstream_scitem.json": {
    "itemClass": "stealth",
    "grade": "A"
  },
  "LIVEfiles\\libs\\foundry\\records\\crafting\\blueprints\\crafting\\vehiclegear\\powerplant\\bp_craft_powr_tydt_s01_soniclite_scitem.json": {
    "itemClass": "stealth",
    "grade": "C"
  },
  "LIVEfiles\\libs\\foundry\\records\\crafting\\blueprints\\crafting\\vehiclegear\\powerplant\\bp_craft_powr_tydt_s02_cirrus_scitem.json": {
    "itemClass": "stealth",
    "grade": "C"
  },
  "LIVEfiles\\libs\\foundry\\records\\crafting\\blueprints\\crafting\\vehiclegear\\powerplant\\bp_craft_powr_tydt_s02_eclipse_scitem.json": {
    "itemClass": "stealth",
    "grade": "A"
  },
  "LIVEfiles\\libs\\foundry\\records\\crafting\\blueprints\\crafting\\vehiclegear\\powerplant\\bp_craft_powr_tydt_s02_gammamax_scitem.json": {
    "itemClass": "stealth",
    "grade": "B"
  },
  "LIVEfiles\\libs\\foundry\\records\\crafting\\blueprints\\crafting\\vehiclegear\\quantumdrive\\size1\\bp_craft_qdrv_acas_s01_foxfire_scitem.json": {
    "itemClass": "competition",
    "grade": "B"
  },
  "LIVEfiles\\libs\\foundry\\records\\crafting\\blueprints\\crafting\\vehiclegear\\quantumdrive\\size1\\bp_craft_qdrv_acas_s01_lightfire_scitem.json": {
    "itemClass": "competition",
    "grade": "C"
  },
  "LIVEfiles\\libs\\foundry\\records\\crafting\\blueprints\\crafting\\vehiclegear\\quantumdrive\\size1\\bp_craft_qdrv_arcc_s01_burst_scitem.json": {
    "itemClass": "civilian",
    "grade": "B"
  },
  "LIVEfiles\\libs\\foundry\\records\\crafting\\blueprints\\crafting\\vehiclegear\\quantumdrive\\size1\\bp_craft_qdrv_arcc_s01_flood_scitem.json": {
    "itemClass": "civilian",
    "grade": "D"
  },
  "LIVEfiles\\libs\\foundry\\records\\crafting\\blueprints\\crafting\\vehiclegear\\quantumdrive\\size1\\bp_craft_qdrv_arcc_s01_rush_scitem.json": {
    "itemClass": "civilian",
    "grade": "C"
  },
  "LIVEfiles\\libs\\foundry\\records\\crafting\\blueprints\\crafting\\vehiclegear\\quantumdrive\\size1\\bp_craft_qdrv_just_s01_colossus_scitem.json": {
    "itemClass": "industrial",
    "grade": "B"
  },
  "LIVEfiles\\libs\\foundry\\records\\crafting\\blueprints\\crafting\\vehiclegear\\quantumdrive\\size1\\bp_craft_qdrv_just_s01_goliath_scitem.json": {
    "itemClass": "industrial",
    "grade": "C"
  },
  "LIVEfiles\\libs\\foundry\\records\\crafting\\blueprints\\crafting\\vehiclegear\\quantumdrive\\size1\\bp_craft_qdrv_just_s01_vulcan_scitem.json": {
    "itemClass": "industrial",
    "grade": "D"
  },
  "LIVEfiles\\libs\\foundry\\records\\crafting\\blueprints\\crafting\\vehiclegear\\quantumdrive\\size1\\bp_craft_qdrv_raco_s01_drift_scitem.json": {
    "itemClass": "stealth",
    "grade": "C"
  },
  "LIVEfiles\\libs\\foundry\\records\\crafting\\blueprints\\crafting\\vehiclegear\\quantumdrive\\size1\\bp_craft_qdrv_raco_s01_spectre_scitem.json": {
    "itemClass": "stealth",
    "grade": "A"
  },
  "LIVEfiles\\libs\\foundry\\records\\crafting\\blueprints\\crafting\\vehiclegear\\quantumdrive\\size1\\bp_craft_qdrv_raco_s01_zephyr_scitem.json": {
    "itemClass": "stealth",
    "grade": "B"
  },
  "LIVEfiles\\libs\\foundry\\records\\crafting\\blueprints\\crafting\\vehiclegear\\quantumdrive\\size1\\bp_craft_qdrv_rsi_s01_atlas_scitem.json": {
    "itemClass": "civilian",
    "grade": "A"
  },
  "LIVEfiles\\libs\\foundry\\records\\crafting\\blueprints\\crafting\\vehiclegear\\quantumdrive\\size1\\bp_craft_qdrv_rsi_s01_eos_scitem.json": {
    "itemClass": "civilian",
    "grade": "C"
  },
  "LIVEfiles\\libs\\foundry\\records\\crafting\\blueprints\\crafting\\vehiclegear\\quantumdrive\\size1\\bp_craft_qdrv_rsi_s01_hyperion_scitem.json": {
    "itemClass": "civilian",
    "grade": "B"
  },
  "LIVEfiles\\libs\\foundry\\records\\crafting\\blueprints\\crafting\\vehiclegear\\quantumdrive\\size1\\bp_craft_qdrv_tars_s01_expedition_scitem.json": {
    "itemClass": "civilian",
    "grade": "C"
  },
  "LIVEfiles\\libs\\foundry\\records\\crafting\\blueprints\\crafting\\vehiclegear\\quantumdrive\\size1\\bp_craft_qdrv_tars_s01_voyage_scitem.json": {
    "itemClass": "civilian",
    "grade": "B"
  },
  "LIVEfiles\\libs\\foundry\\records\\crafting\\blueprints\\crafting\\vehiclegear\\quantumdrive\\size1\\bp_craft_qdrv_tars_s01_wayfare_scitem.json": {
    "itemClass": "civilian",
    "grade": "D"
  },
  "LIVEfiles\\libs\\foundry\\records\\crafting\\blueprints\\crafting\\vehiclegear\\quantumdrive\\size1\\bp_craft_qdrv_wetk_s01_beacon_scitem.json": {
    "itemClass": "military",
    "grade": "C"
  },
  "LIVEfiles\\libs\\foundry\\records\\crafting\\blueprints\\crafting\\vehiclegear\\quantumdrive\\size1\\bp_craft_qdrv_wetk_s01_siren_scitem.json": {
    "itemClass": "military",
    "grade": "B"
  },
  "LIVEfiles\\libs\\foundry\\records\\crafting\\blueprints\\crafting\\vehiclegear\\quantumdrive\\size1\\bp_craft_qdrv_wetk_s01_vk00_scitem.json": {
    "itemClass": "military",
    "grade": "A"
  },
  "LIVEfiles\\libs\\foundry\\records\\crafting\\blueprints\\crafting\\vehiclegear\\quantumdrive\\size2\\bp_craft_qdrv_acas_s02_sparkfire_scitem.json": {
    "itemClass": "competition",
    "grade": "C"
  },
  "LIVEfiles\\libs\\foundry\\records\\crafting\\blueprints\\crafting\\vehiclegear\\quantumdrive\\size2\\bp_craft_qdrv_acas_s02_sunfire_scitem.json": {
    "itemClass": "competition",
    "grade": "B"
  },
  "LIVEfiles\\libs\\foundry\\records\\crafting\\blueprints\\crafting\\vehiclegear\\quantumdrive\\size2\\bp_craft_qdrv_arcc_s02_cascade_scitem.json": {
    "itemClass": "civilian",
    "grade": "D"
  },
  "LIVEfiles\\libs\\foundry\\records\\crafting\\blueprints\\crafting\\vehiclegear\\quantumdrive\\size2\\bp_craft_qdrv_arcc_s02_flash_scitem.json": {
    "itemClass": "civilian",
    "grade": "B"
  },
  "LIVEfiles\\libs\\foundry\\records\\crafting\\blueprints\\crafting\\vehiclegear\\quantumdrive\\size2\\bp_craft_qdrv_arcc_s02_torrent_scitem.json": {
    "itemClass": "civilian",
    "grade": "C"
  },
  "LIVEfiles\\libs\\foundry\\records\\crafting\\blueprints\\crafting\\vehiclegear\\quantumdrive\\size2\\bp_craft_qdrv_just_s02_bolon_scitem.json": {
    "itemClass": "industrial",
    "grade": "C"
  },
  "LIVEfiles\\libs\\foundry\\records\\crafting\\blueprints\\crafting\\vehiclegear\\quantumdrive\\size2\\bp_craft_qdrv_just_s02_huracan_scitem.json": {
    "itemClass": "industrial",
    "grade": "B"
  },
  "LIVEfiles\\libs\\foundry\\records\\crafting\\blueprints\\crafting\\vehiclegear\\quantumdrive\\size2\\bp_craft_qdrv_just_s02_yaluk_scitem.json": {
    "itemClass": "industrial",
    "grade": "D"
  },
  "LIVEfiles\\libs\\foundry\\records\\crafting\\blueprints\\crafting\\vehiclegear\\quantumdrive\\size2\\bp_craft_qdrv_raco_s02_bolt_scitem.json": {
    "itemClass": "stealth",
    "grade": "B"
  },
  "LIVEfiles\\libs\\foundry\\records\\crafting\\blueprints\\crafting\\vehiclegear\\quantumdrive\\size2\\bp_craft_qdrv_raco_s02_nova_scitem.json": {
    "itemClass": "stealth",
    "grade": "C"
  },
  "LIVEfiles\\libs\\foundry\\records\\crafting\\blueprints\\crafting\\vehiclegear\\quantumdrive\\size2\\bp_craft_qdrv_raco_s02_spicule_scitem.json": {
    "itemClass": "stealth",
    "grade": "A"
  },
  "LIVEfiles\\libs\\foundry\\records\\crafting\\blueprints\\crafting\\vehiclegear\\quantumdrive\\size2\\bp_craft_qdrv_rsi_s02_aither_scitem.json": {
    "itemClass": "civilian",
    "grade": "B"
  },
  "LIVEfiles\\libs\\foundry\\records\\crafting\\blueprints\\crafting\\vehiclegear\\quantumdrive\\size2\\bp_craft_qdrv_rsi_s02_hemera_scitem.json": {
    "itemClass": "civilian",
    "grade": "A"
  },
  "LIVEfiles\\libs\\foundry\\records\\crafting\\blueprints\\crafting\\vehiclegear\\quantumdrive\\size2\\bp_craft_qdrv_rsi_s02_khaos_scitem.json": {
    "itemClass": "civilian",
    "grade": "C"
  },
  "LIVEfiles\\libs\\foundry\\records\\crafting\\blueprints\\crafting\\vehiclegear\\quantumdrive\\size2\\bp_craft_qdrv_tars_s02_odyssey_scitem.json": {
    "itemClass": "civilian",
    "grade": "C"
  },
  "LIVEfiles\\libs\\foundry\\records\\crafting\\blueprints\\crafting\\vehiclegear\\quantumdrive\\size2\\bp_craft_qdrv_tars_s02_quest_scitem.json": {
    "itemClass": "civilian",
    "grade": "D"
  },
  "LIVEfiles\\libs\\foundry\\records\\crafting\\blueprints\\crafting\\vehiclegear\\quantumdrive\\size2\\bp_craft_qdrv_tars_s02_sojourn_scitem.json": {
    "itemClass": "civilian",
    "grade": "B"
  },
  "LIVEfiles\\libs\\foundry\\records\\crafting\\blueprints\\crafting\\vehiclegear\\quantumdrive\\size2\\bp_craft_qdrv_wetk_s02_crossfield_scitem.json": {
    "itemClass": "military",
    "grade": "C"
  },
  "LIVEfiles\\libs\\foundry\\records\\crafting\\blueprints\\crafting\\vehiclegear\\quantumdrive\\size2\\bp_craft_qdrv_wetk_s02_xl1_scitem.json": {
    "itemClass": "military",
    "grade": "A"
  },
  "LIVEfiles\\libs\\foundry\\records\\crafting\\blueprints\\crafting\\vehiclegear\\quantumdrive\\size2\\bp_craft_qdrv_wetk_s02_yeager_scitem.json": {
    "itemClass": "military",
    "grade": "B"
  },
  "LIVEfiles\\libs\\foundry\\records\\crafting\\blueprints\\crafting\\vehiclegear\\quantumdrive\\size3\\bp_craft_qdrv_arcc_s03_echo_scitem.json": {
    "itemClass": "civilian",
    "grade": "D"
  },
  "LIVEfiles\\libs\\foundry\\records\\crafting\\blueprints\\crafting\\vehiclegear\\quantumdrive\\size3\\bp_craft_qdrv_arcc_s03_fissure_scitem.json": {
    "itemClass": "civilian",
    "grade": "C"
  },
  "LIVEfiles\\libs\\foundry\\records\\crafting\\blueprints\\crafting\\vehiclegear\\quantumdrive\\size3\\bp_craft_qdrv_arcc_s03_impulse_scitem.json": {
    "itemClass": "civilian",
    "grade": "B"
  },
  "LIVEfiles\\libs\\foundry\\records\\crafting\\blueprints\\crafting\\vehiclegear\\quantumdrive\\size3\\bp_craft_qdrv_just_s03_agni_scitem.json": {
    "itemClass": "industrial",
    "grade": "B"
  },
  "LIVEfiles\\libs\\foundry\\records\\crafting\\blueprints\\crafting\\vehiclegear\\quantumdrive\\size3\\bp_craft_qdrv_just_s03_kama_scitem.json": {
    "itemClass": "industrial",
    "grade": "C"
  },
  "LIVEfiles\\libs\\foundry\\records\\crafting\\blueprints\\crafting\\vehiclegear\\quantumdrive\\size3\\bp_craft_qdrv_just_s03_vesta_scitem.json": {
    "itemClass": "industrial",
    "grade": "D"
  },
  "LIVEfiles\\libs\\foundry\\records\\crafting\\blueprints\\crafting\\vehiclegear\\quantumdrive\\size3\\bp_craft_qdrv_rsi_s03_erebos_scitem.json": {
    "itemClass": "civilian",
    "grade": "A"
  },
  "LIVEfiles\\libs\\foundry\\records\\crafting\\blueprints\\crafting\\vehiclegear\\quantumdrive\\size3\\bp_craft_qdrv_rsi_s03_metis_scitem.json": {
    "itemClass": "civilian",
    "grade": "C"
  },
  "LIVEfiles\\libs\\foundry\\records\\crafting\\blueprints\\crafting\\vehiclegear\\quantumdrive\\size3\\bp_craft_qdrv_rsi_s03_tyche_scitem.json": {
    "itemClass": "civilian",
    "grade": "B"
  },
  "LIVEfiles\\libs\\foundry\\records\\crafting\\blueprints\\crafting\\vehiclegear\\quantumdrive\\size3\\bp_craft_qdrv_tars_s03_drifter_scitem.json": {
    "itemClass": "civilian",
    "grade": "D"
  },
  "LIVEfiles\\libs\\foundry\\records\\crafting\\blueprints\\crafting\\vehiclegear\\quantumdrive\\size3\\bp_craft_qdrv_tars_s03_ranger_scitem.json": {
    "itemClass": "civilian",
    "grade": "B"
  },
  "LIVEfiles\\libs\\foundry\\records\\crafting\\blueprints\\crafting\\vehiclegear\\quantumdrive\\size3\\bp_craft_qdrv_tars_s03_wanderer_scitem.json": {
    "itemClass": "civilian",
    "grade": "C"
  },
  "LIVEfiles\\libs\\foundry\\records\\crafting\\blueprints\\crafting\\vehiclegear\\quantumdrive\\size3\\bp_craft_qdrv_wetk_s03_balandin_scitem.json": {
    "itemClass": "military",
    "grade": "B"
  },
  "LIVEfiles\\libs\\foundry\\records\\crafting\\blueprints\\crafting\\vehiclegear\\quantumdrive\\size3\\bp_craft_qdrv_wetk_s03_pontes_scitem.json": {
    "itemClass": "military",
    "grade": "C"
  },
  "LIVEfiles\\libs\\foundry\\records\\crafting\\blueprints\\crafting\\vehiclegear\\quantumdrive\\size3\\bp_craft_qdrv_wetk_s03_ts2_scitem.json": {
    "itemClass": "military",
    "grade": "A"
  },
  "LIVEfiles\\libs\\foundry\\records\\crafting\\blueprints\\crafting\\vehiclegear\\quantumdrive\\size4\\bp_craft_qdrv_orig_s04_890j_scitem.json": {
    "itemClass": "civilian",
    "grade": "A"
  },
  "LIVEfiles\\libs\\foundry\\records\\crafting\\blueprints\\crafting\\vehiclegear\\radar\\bp_craft_radr_bltr_s01_hunter.json": {
    "itemClass": "stealth",
    "grade": "B"
  },
  "LIVEfiles\\libs\\foundry\\records\\crafting\\blueprints\\crafting\\vehiclegear\\radar\\bp_craft_radr_bltr_s01_pelerous.json": {
    "itemClass": "stealth",
    "grade": "A"
  },
  "LIVEfiles\\libs\\foundry\\records\\crafting\\blueprints\\crafting\\vehiclegear\\radar\\bp_craft_radr_bltr_s01_prophet.json": {
    "itemClass": "stealth",
    "grade": "A"
  },
  "LIVEfiles\\libs\\foundry\\records\\crafting\\blueprints\\crafting\\vehiclegear\\radar\\bp_craft_radr_bltr_s02_cassandra.json": {
    "itemClass": "stealth",
    "grade": "A"
  },
  "LIVEfiles\\libs\\foundry\\records\\crafting\\blueprints\\crafting\\vehiclegear\\radar\\bp_craft_radr_bltr_s02_predator.json": {
    "itemClass": "stealth",
    "grade": "B"
  },
  "LIVEfiles\\libs\\foundry\\records\\crafting\\blueprints\\crafting\\vehiclegear\\radar\\bp_craft_radr_bltr_s02_spyglass.json": {
    "itemClass": "stealth",
    "grade": "C"
  },
  "LIVEfiles\\libs\\foundry\\records\\crafting\\blueprints\\crafting\\vehiclegear\\radar\\bp_craft_radr_chco_s00_broadspecgo.json": {
    "itemClass": "industrial",
    "grade": "B"
  },
  "LIVEfiles\\libs\\foundry\\records\\crafting\\blueprints\\crafting\\vehiclegear\\radar\\bp_craft_radr_chco_s00_fullspecgo.json": {
    "itemClass": "industrial",
    "grade": "A"
  },
  "LIVEfiles\\libs\\foundry\\records\\crafting\\blueprints\\crafting\\vehiclegear\\radar\\bp_craft_radr_chco_s00_observergo.json": {
    "itemClass": "industrial",
    "grade": "D"
  },
  "LIVEfiles\\libs\\foundry\\records\\crafting\\blueprints\\crafting\\vehiclegear\\radar\\bp_craft_radr_chco_s00_surveyorgo.json": {
    "itemClass": "industrial",
    "grade": "C"
  },
  "LIVEfiles\\libs\\foundry\\records\\crafting\\blueprints\\crafting\\vehiclegear\\radar\\bp_craft_radr_chco_s01_observerlite.json": {
    "itemClass": "industrial",
    "grade": "D"
  },
  "LIVEfiles\\libs\\foundry\\records\\crafting\\blueprints\\crafting\\vehiclegear\\radar\\bp_craft_radr_chco_s01_surveyorlite.json": {
    "itemClass": "industrial",
    "grade": "C"
  },
  "LIVEfiles\\libs\\foundry\\records\\crafting\\blueprints\\crafting\\vehiclegear\\radar\\bp_craft_radr_chco_s02_broadspec_lite.json": {
    "itemClass": "industrial",
    "grade": "B"
  },
  "LIVEfiles\\libs\\foundry\\records\\crafting\\blueprints\\crafting\\vehiclegear\\radar\\bp_craft_radr_chco_s02_fullspec.json": {
    "itemClass": "industrial",
    "grade": "A"
  },
  "LIVEfiles\\libs\\foundry\\records\\crafting\\blueprints\\crafting\\vehiclegear\\radar\\bp_craft_radr_chco_s02_observer.json": {
    "itemClass": "industrial",
    "grade": "D"
  },
  "LIVEfiles\\libs\\foundry\\records\\crafting\\blueprints\\crafting\\vehiclegear\\radar\\bp_craft_radr_chco_s02_surveyor.json": {
    "itemClass": "industrial",
    "grade": "C"
  },
  "LIVEfiles\\libs\\foundry\\records\\crafting\\blueprints\\crafting\\vehiclegear\\radar\\bp_craft_radr_chco_s03_broudspec.json": {
    "itemClass": "industrial",
    "grade": "B"
  },
  "LIVEfiles\\libs\\foundry\\records\\crafting\\blueprints\\crafting\\vehiclegear\\radar\\bp_craft_radr_chco_s03_fullspecmax.json": {
    "itemClass": "industrial",
    "grade": "A"
  },
  "LIVEfiles\\libs\\foundry\\records\\crafting\\blueprints\\crafting\\vehiclegear\\radar\\bp_craft_radr_chco_s03_observermax.json": {
    "itemClass": "industrial",
    "grade": "D"
  },
  "LIVEfiles\\libs\\foundry\\records\\crafting\\blueprints\\crafting\\vehiclegear\\radar\\bp_craft_radr_chco_s03_surveyormax.json": {
    "itemClass": "industrial",
    "grade": "C"
  },
  "LIVEfiles\\libs\\foundry\\records\\crafting\\blueprints\\crafting\\vehiclegear\\radar\\bp_craft_radr_chco_s04_broadspecmax.json": {
    "itemClass": "industrial",
    "grade": "B"
  },
  "LIVEfiles\\libs\\foundry\\records\\crafting\\blueprints\\crafting\\vehiclegear\\radar\\bp_craft_radr_grno_s00_agure.json": {
    "itemClass": "military",
    "grade": "D"
  },
  "LIVEfiles\\libs\\foundry\\records\\crafting\\blueprints\\crafting\\vehiclegear\\radar\\bp_craft_radr_grnp_s00_prevenir.json": {
    "itemClass": "military",
    "grade": "C"
  },
  "LIVEfiles\\libs\\foundry\\records\\crafting\\blueprints\\crafting\\vehiclegear\\radar\\bp_craft_radr_grnp_s00_sens.json": {
    "itemClass": "military",
    "grade": "B"
  },
  "LIVEfiles\\libs\\foundry\\records\\crafting\\blueprints\\crafting\\vehiclegear\\radar\\bp_craft_radr_grnp_s00_v6026.json": {
    "itemClass": "military",
    "grade": "A"
  },
  "LIVEfiles\\libs\\foundry\\records\\crafting\\blueprints\\crafting\\vehiclegear\\radar\\bp_craft_radr_grnp_s01_ecouter.json": {
    "itemClass": "military",
    "grade": "C"
  },
  "LIVEfiles\\libs\\foundry\\records\\crafting\\blueprints\\crafting\\vehiclegear\\radar\\bp_craft_radr_grnp_s01_tige.json": {
    "itemClass": "military",
    "grade": "B"
  },
  "LIVEfiles\\libs\\foundry\\records\\crafting\\blueprints\\crafting\\vehiclegear\\radar\\bp_craft_radr_grnp_s01_v80111.json": {
    "itemClass": "military",
    "grade": "A"
  },
  "LIVEfiles\\libs\\foundry\\records\\crafting\\blueprints\\crafting\\vehiclegear\\radar\\bp_craft_radr_grnp_s01_voir.json": {
    "itemClass": "military",
    "grade": "D"
  },
  "LIVEfiles\\libs\\foundry\\records\\crafting\\blueprints\\crafting\\vehiclegear\\radar\\bp_craft_radr_grnp_s02_epier.json": {
    "itemClass": "military",
    "grade": "C"
  },
  "LIVEfiles\\libs\\foundry\\records\\crafting\\blueprints\\crafting\\vehiclegear\\radar\\bp_craft_radr_grnp_s02_savoir.json": {
    "itemClass": "military",
    "grade": "D"
  },
  "LIVEfiles\\libs\\foundry\\records\\crafting\\blueprints\\crafting\\vehiclegear\\radar\\bp_craft_radr_grnp_s02_vb80112.json": {
    "itemClass": "military",
    "grade": "A"
  },
  "LIVEfiles\\libs\\foundry\\records\\crafting\\blueprints\\crafting\\vehiclegear\\radar\\bp_craft_radr_grnp_s02_vigilance.json": {
    "itemClass": "military",
    "grade": "B"
  },
  "LIVEfiles\\libs\\foundry\\records\\crafting\\blueprints\\crafting\\vehiclegear\\radar\\bp_craft_radr_grnp_s03_devoue.json": {
    "itemClass": "military",
    "grade": "B"
  },
  "LIVEfiles\\libs\\foundry\\records\\crafting\\blueprints\\crafting\\vehiclegear\\radar\\bp_craft_radr_grnp_s03_fidele.json": {
    "itemClass": "military",
    "grade": "D"
  },
  "LIVEfiles\\libs\\foundry\\records\\crafting\\blueprints\\crafting\\vehiclegear\\radar\\bp_craft_radr_grnp_s03_resolu.json": {
    "itemClass": "military",
    "grade": "C"
  },
  "LIVEfiles\\libs\\foundry\\records\\crafting\\blueprints\\crafting\\vehiclegear\\radar\\bp_craft_radr_grnp_s03_v880.json": {
    "itemClass": "military",
    "grade": "A"
  },
  "LIVEfiles\\libs\\foundry\\records\\crafting\\blueprints\\crafting\\vehiclegear\\radar\\bp_craft_radr_nave_s01_snsr5.json": {
    "itemClass": "competition",
    "grade": "D"
  },
  "LIVEfiles\\libs\\foundry\\records\\crafting\\blueprints\\crafting\\vehiclegear\\radar\\bp_craft_radr_nave_s01_snsr6.json": {
    "itemClass": "competition",
    "grade": "C"
  },
  "LIVEfiles\\libs\\foundry\\records\\crafting\\blueprints\\crafting\\vehiclegear\\radar\\bp_craft_radr_nave_s01_snsr7.json": {
    "itemClass": "competition",
    "grade": "B"
  },
  "LIVEfiles\\libs\\foundry\\records\\crafting\\blueprints\\crafting\\vehiclegear\\radar\\bp_craft_radr_nave_s02_snsr5x.json": {
    "itemClass": "competition",
    "grade": "D"
  },
  "LIVEfiles\\libs\\foundry\\records\\crafting\\blueprints\\crafting\\vehiclegear\\radar\\bp_craft_radr_nave_s02_snsr7x.json": {
    "itemClass": "competition",
    "grade": "B"
  },
  "LIVEfiles\\libs\\foundry\\records\\crafting\\blueprints\\crafting\\vehiclegear\\radar\\bp_craft_radr_nave_s02_sns_r6x.json": {
    "itemClass": "competition",
    "grade": "C"
  },
  "LIVEfiles\\libs\\foundry\\records\\crafting\\blueprints\\crafting\\vehiclegear\\radar\\bp_craft_radr_rsi_s04_polaris.json": {
    "grade": "A"
  },
  "LIVEfiles\\libs\\foundry\\records\\crafting\\blueprints\\crafting\\vehiclegear\\radar\\bp_craft_radr_wlop_s00_denning.json": {
    "itemClass": "civilian",
    "grade": "C"
  },
  "LIVEfiles\\libs\\foundry\\records\\crafting\\blueprints\\crafting\\vehiclegear\\radar\\bp_craft_radr_wlop_s00_fabian.json": {
    "itemClass": "civilian",
    "grade": "A"
  },
  "LIVEfiles\\libs\\foundry\\records\\crafting\\blueprints\\crafting\\vehiclegear\\radar\\bp_craft_radr_wlop_s00_vogel.json": {
    "itemClass": "civilian",
    "grade": "B"
  },
  "LIVEfiles\\libs\\foundry\\records\\crafting\\blueprints\\crafting\\vehiclegear\\radar\\bp_craft_radr_wlop_s01_abetti.json": {
    "itemClass": "civilian",
    "grade": "A"
  },
  "LIVEfiles\\libs\\foundry\\records\\crafting\\blueprints\\crafting\\vehiclegear\\radar\\bp_craft_radr_wlop_s01_backlund.json": {
    "itemClass": "civilian",
    "grade": "B"
  },
  "LIVEfiles\\libs\\foundry\\records\\crafting\\blueprints\\crafting\\vehiclegear\\radar\\bp_craft_radr_wlop_s01_capstan.json": {
    "itemClass": "civilian",
    "grade": "C"
  },
  "LIVEfiles\\libs\\foundry\\records\\crafting\\blueprints\\crafting\\vehiclegear\\radar\\bp_craft_radr_wlop_s01_fleming.json": {
    "itemClass": "civilian",
    "grade": "D"
  },
  "LIVEfiles\\libs\\foundry\\records\\crafting\\blueprints\\crafting\\vehiclegear\\radar\\bp_craft_radr_wlop_s02_agrippa.json": {
    "itemClass": "civilian",
    "grade": "A"
  },
  "LIVEfiles\\libs\\foundry\\records\\crafting\\blueprints\\crafting\\vehiclegear\\radar\\bp_craft_radr_wlop_s02_battani.json": {
    "itemClass": "civilian",
    "grade": "B"
  },
  "LIVEfiles\\libs\\foundry\\records\\crafting\\blueprints\\crafting\\vehiclegear\\radar\\bp_craft_radr_wlop_s02_chernykh.json": {
    "itemClass": "civilian",
    "grade": "C"
  },
  "LIVEfiles\\libs\\foundry\\records\\crafting\\blueprints\\crafting\\vehiclegear\\radar\\bp_craft_radr_wlop_s02_fawad.json": {
    "itemClass": "civilian",
    "grade": "D"
  },
  "LIVEfiles\\libs\\foundry\\records\\crafting\\blueprints\\crafting\\vehiclegear\\radar\\bp_craft_radr_wlop_s03_anysta.json": {
    "itemClass": "civilian",
    "grade": "A"
  },
  "LIVEfiles\\libs\\foundry\\records\\crafting\\blueprints\\crafting\\vehiclegear\\radar\\bp_craft_radr_wlop_s03_capsulo.json": {
    "itemClass": "civilian",
    "grade": "B"
  },
  "LIVEfiles\\libs\\foundry\\records\\crafting\\blueprints\\crafting\\vehiclegear\\radar\\bp_craft_radr_wlop_s03_lephari.json": {
    "grade": "C"
  },
  "LIVEfiles\\libs\\foundry\\records\\crafting\\blueprints\\crafting\\vehiclegear\\radar\\bp_craft_radr_wlop_s03_socoria.json": {
    "itemClass": "civilian",
    "grade": "D"
  },
  "LIVEfiles\\libs\\foundry\\records\\crafting\\blueprints\\crafting\\vehiclegear\\shield\\bp_craft_shld_aegs_s04_reclaimer_scitem.json": {
    "itemClass": "industrial",
    "grade": "A"
  },
  "LIVEfiles\\libs\\foundry\\records\\crafting\\blueprints\\crafting\\vehiclegear\\shield\\bp_craft_shld_asas_s01_cloak_scitem.json": {
    "itemClass": "stealth",
    "grade": "D"
  },
  "LIVEfiles\\libs\\foundry\\records\\crafting\\blueprints\\crafting\\vehiclegear\\shield\\bp_craft_shld_asas_s01_mirage_scitem.json": {
    "itemClass": "stealth",
    "grade": "A"
  },
  "LIVEfiles\\libs\\foundry\\records\\crafting\\blueprints\\crafting\\vehiclegear\\shield\\bp_craft_shld_asas_s01_shimmer_scitem.json": {
    "itemClass": "stealth",
    "grade": "C"
  },
  "LIVEfiles\\libs\\foundry\\records\\crafting\\blueprints\\crafting\\vehiclegear\\shield\\bp_craft_shld_asas_s01_veil_scitem.json": {
    "itemClass": "stealth",
    "grade": "B"
  },
  "LIVEfiles\\libs\\foundry\\records\\crafting\\blueprints\\crafting\\vehiclegear\\shield\\bp_craft_shld_asas_s02_obscura_scitem.json": {
    "itemClass": "stealth",
    "grade": "C"
  },
  "LIVEfiles\\libs\\foundry\\records\\crafting\\blueprints\\crafting\\vehiclegear\\shield\\bp_craft_shld_asas_s02_sheut_scitem.json": {
    "itemClass": "stealth",
    "grade": "B"
  },
  "LIVEfiles\\libs\\foundry\\records\\crafting\\blueprints\\crafting\\vehiclegear\\shield\\bp_craft_shld_asas_s02_shroud_scitem.json": {
    "itemClass": "stealth",
    "grade": "D"
  },
  "LIVEfiles\\libs\\foundry\\records\\crafting\\blueprints\\crafting\\vehiclegear\\shield\\bp_craft_shld_asas_s02_umbra_scitem.json": {
    "itemClass": "stealth",
    "grade": "A"
  },
  "LIVEfiles\\libs\\foundry\\records\\crafting\\blueprints\\crafting\\vehiclegear\\shield\\bp_craft_shld_basl_s00_castra_scitem.json": {
    "itemClass": "industrial",
    "grade": "C"
  },
  "LIVEfiles\\libs\\foundry\\records\\crafting\\blueprints\\crafting\\vehiclegear\\shield\\bp_craft_shld_basl_s01_bulwark_scitem.json": {
    "itemClass": "industrial",
    "grade": "C"
  },
  "LIVEfiles\\libs\\foundry\\records\\crafting\\blueprints\\crafting\\vehiclegear\\shield\\bp_craft_shld_basl_s01_guardian_scitem.json": {
    "itemClass": "industrial",
    "grade": "B"
  },
  "LIVEfiles\\libs\\foundry\\records\\crafting\\blueprints\\crafting\\vehiclegear\\shield\\bp_craft_shld_basl_s01_palisade_scitem.json": {
    "itemClass": "industrial",
    "grade": "A"
  },
  "LIVEfiles\\libs\\foundry\\records\\crafting\\blueprints\\crafting\\vehiclegear\\shield\\bp_craft_shld_basl_s01_steward_scitem.json": {
    "itemClass": "industrial",
    "grade": "D"
  },
  "LIVEfiles\\libs\\foundry\\records\\crafting\\blueprints\\crafting\\vehiclegear\\shield\\bp_craft_shld_basl_s02_armada_scitem.json": {
    "itemClass": "industrial",
    "grade": "D"
  },
  "LIVEfiles\\libs\\foundry\\records\\crafting\\blueprints\\crafting\\vehiclegear\\shield\\bp_craft_shld_basl_s02_aspis_scitem.json": {
    "itemClass": "industrial",
    "grade": "C"
  },
  "LIVEfiles\\libs\\foundry\\records\\crafting\\blueprints\\crafting\\vehiclegear\\shield\\bp_craft_shld_basl_s02_citadel_scitem.json": {
    "itemClass": "industrial",
    "grade": "B"
  },
  "LIVEfiles\\libs\\foundry\\records\\crafting\\blueprints\\crafting\\vehiclegear\\shield\\bp_craft_shld_basl_s02_rampart_scitem.json": {
    "itemClass": "industrial",
    "grade": "A"
  },
  "LIVEfiles\\libs\\foundry\\records\\crafting\\blueprints\\crafting\\vehiclegear\\shield\\bp_craft_shld_basl_s03_barbican_scitem.json": {
    "itemClass": "industrial",
    "grade": "B"
  },
  "LIVEfiles\\libs\\foundry\\records\\crafting\\blueprints\\crafting\\vehiclegear\\shield\\bp_craft_shld_basl_s03_parapet_scitem.json": {
    "itemClass": "industrial",
    "grade": "A"
  },
  "LIVEfiles\\libs\\foundry\\records\\crafting\\blueprints\\crafting\\vehiclegear\\shield\\bp_craft_shld_basl_s03_stronghold_scitem.json": {
    "itemClass": "industrial",
    "grade": "C"
  },
  "LIVEfiles\\libs\\foundry\\records\\crafting\\blueprints\\crafting\\vehiclegear\\shield\\bp_craft_shld_basl_s03_ward_scitem.json": {
    "itemClass": "industrial",
    "grade": "D"
  },
  "LIVEfiles\\libs\\foundry\\records\\crafting\\blueprints\\crafting\\vehiclegear\\shield\\bp_craft_shld_behr_s01_5sa_scitem.json": {
    "itemClass": "civilian",
    "grade": "C"
  },
  "LIVEfiles\\libs\\foundry\\records\\crafting\\blueprints\\crafting\\vehiclegear\\shield\\bp_craft_shld_behr_s01_6sa_scitem.json": {
    "itemClass": "civilian",
    "grade": "B"
  },
  "LIVEfiles\\libs\\foundry\\records\\crafting\\blueprints\\crafting\\vehiclegear\\shield\\bp_craft_shld_behr_s01_7sa_scitem.json": {
    "itemClass": "civilian",
    "grade": "A"
  },
  "LIVEfiles\\libs\\foundry\\records\\crafting\\blueprints\\crafting\\vehiclegear\\shield\\bp_craft_shld_behr_s02_5ma_scitem.json": {
    "itemClass": "civilian",
    "grade": "C"
  },
  "LIVEfiles\\libs\\foundry\\records\\crafting\\blueprints\\crafting\\vehiclegear\\shield\\bp_craft_shld_behr_s02_6ma_scitem.json": {
    "itemClass": "civilian",
    "grade": "B"
  },
  "LIVEfiles\\libs\\foundry\\records\\crafting\\blueprints\\crafting\\vehiclegear\\shield\\bp_craft_shld_behr_s02_7ma_scitem.json": {
    "itemClass": "civilian",
    "grade": "A"
  },
  "LIVEfiles\\libs\\foundry\\records\\crafting\\blueprints\\crafting\\vehiclegear\\shield\\bp_craft_shld_behr_s03_5ca_scitem.json": {
    "itemClass": "civilian",
    "grade": "C"
  },
  "LIVEfiles\\libs\\foundry\\records\\crafting\\blueprints\\crafting\\vehiclegear\\shield\\bp_craft_shld_behr_s03_6ca_scitem.json": {
    "itemClass": "civilian",
    "grade": "B"
  },
  "LIVEfiles\\libs\\foundry\\records\\crafting\\blueprints\\crafting\\vehiclegear\\shield\\bp_craft_shld_behr_s03_7ca_scitem.json": {
    "itemClass": "civilian",
    "grade": "A"
  },
  "LIVEfiles\\libs\\foundry\\records\\crafting\\blueprints\\crafting\\vehiclegear\\shield\\bp_craft_shld_godi_s01_allstop_scitem.json": {
    "itemClass": "military",
    "grade": "C"
  },
  "LIVEfiles\\libs\\foundry\\records\\crafting\\blueprints\\crafting\\vehiclegear\\shield\\bp_craft_shld_godi_s01_forcewall_scitem.json": {
    "itemClass": "military",
    "grade": "B"
  },
  "LIVEfiles\\libs\\foundry\\records\\crafting\\blueprints\\crafting\\vehiclegear\\shield\\bp_craft_shld_godi_s01_fr66_scitem.json": {
    "itemClass": "military",
    "grade": "A"
  },
  "LIVEfiles\\libs\\foundry\\records\\crafting\\blueprints\\crafting\\vehiclegear\\shield\\bp_craft_shld_godi_s01_securehyde_scitem.json": {
    "itemClass": "military",
    "grade": "D"
  },
  "LIVEfiles\\libs\\foundry\\records\\crafting\\blueprints\\crafting\\vehiclegear\\shield\\bp_craft_shld_godi_s02_coverall_scitem.json": {
    "itemClass": "military",
    "grade": "B"
  },
  "LIVEfiles\\libs\\foundry\\records\\crafting\\blueprints\\crafting\\vehiclegear\\shield\\bp_craft_shld_godi_s02_fr76_scitem.json": {
    "itemClass": "military",
    "grade": "A"
  },
  "LIVEfiles\\libs\\foundry\\records\\crafting\\blueprints\\crafting\\vehiclegear\\shield\\bp_craft_shld_godi_s02_fullstop_scitem.json": {
    "itemClass": "military",
    "grade": "C"
  },
  "LIVEfiles\\libs\\foundry\\records\\crafting\\blueprints\\crafting\\vehiclegear\\shield\\bp_craft_shld_godi_s02_secureshield_scitem.json": {
    "itemClass": "military",
    "grade": "D"
  },
  "LIVEfiles\\libs\\foundry\\records\\crafting\\blueprints\\crafting\\vehiclegear\\shield\\bp_craft_shld_godi_s03_fr86_scitem.json": {
    "itemClass": "military",
    "grade": "A"
  },
  "LIVEfiles\\libs\\foundry\\records\\crafting\\blueprints\\crafting\\vehiclegear\\shield\\bp_craft_shld_godi_s03_fullblock_scitem.json": {
    "itemClass": "military",
    "grade": "B"
  },
  "LIVEfiles\\libs\\foundry\\records\\crafting\\blueprints\\crafting\\vehiclegear\\shield\\bp_craft_shld_godi_s03_securescreen_scitem.json": {
    "itemClass": "military",
    "grade": "D"
  },
  "LIVEfiles\\libs\\foundry\\records\\crafting\\blueprints\\crafting\\vehiclegear\\shield\\bp_craft_shld_godi_s03_surestop_scitem.json": {
    "itemClass": "military",
    "grade": "C"
  },
  "LIVEfiles\\libs\\foundry\\records\\crafting\\blueprints\\crafting\\vehiclegear\\shield\\bp_craft_shld_godi_s04_idris_scitem.json": {
    "grade": "A"
  },
  "LIVEfiles\\libs\\foundry\\records\\crafting\\blueprints\\crafting\\vehiclegear\\shield\\bp_craft_shld_orig_s04_890j_scitem.json": {
    "itemClass": "industrial",
    "grade": "A"
  },
  "LIVEfiles\\libs\\foundry\\records\\crafting\\blueprints\\crafting\\vehiclegear\\shield\\bp_craft_shld_rsi_s04_polaris_scitem.json": {
    "itemClass": "industrial",
    "grade": "A"
  },
  "LIVEfiles\\libs\\foundry\\records\\crafting\\blueprints\\crafting\\vehiclegear\\shield\\bp_craft_shld_seco_s00_pin_scitem.json": {
    "itemClass": "civilian",
    "grade": "C"
  },
  "LIVEfiles\\libs\\foundry\\records\\crafting\\blueprints\\crafting\\vehiclegear\\shield\\bp_craft_shld_seco_s01_hex_scitem.json": {
    "itemClass": "civilian",
    "grade": "B"
  },
  "LIVEfiles\\libs\\foundry\\records\\crafting\\blueprints\\crafting\\vehiclegear\\shield\\bp_craft_shld_seco_s01_ink_scitem.json": {
    "itemClass": "civilian",
    "grade": "D"
  },
  "LIVEfiles\\libs\\foundry\\records\\crafting\\blueprints\\crafting\\vehiclegear\\shield\\bp_craft_shld_seco_s01_web_scitem.json": {
    "itemClass": "civilian",
    "grade": "C"
  },
  "LIVEfiles\\libs\\foundry\\records\\crafting\\blueprints\\crafting\\vehiclegear\\shield\\bp_craft_shld_seco_s02_bloc_scitem.json": {
    "itemClass": "civilian",
    "grade": "B"
  },
  "LIVEfiles\\libs\\foundry\\records\\crafting\\blueprints\\crafting\\vehiclegear\\shield\\bp_craft_shld_seco_s02_rpel_scitem.json": {
    "itemClass": "civilian",
    "grade": "D"
  },
  "LIVEfiles\\libs\\foundry\\records\\crafting\\blueprints\\crafting\\vehiclegear\\shield\\bp_craft_shld_seco_s02_stop_scitem.json": {
    "itemClass": "civilian",
    "grade": "C"
  },
  "LIVEfiles\\libs\\foundry\\records\\crafting\\blueprints\\crafting\\vehiclegear\\shield\\bp_craft_shld_seco_s03_armor_scitem.json": {
    "itemClass": "civilian",
    "grade": "B"
  },
  "LIVEfiles\\libs\\foundry\\records\\crafting\\blueprints\\crafting\\vehiclegear\\shield\\bp_craft_shld_seco_s03_guard_scitem.json": {
    "itemClass": "civilian",
    "grade": "C"
  },
  "LIVEfiles\\libs\\foundry\\records\\crafting\\blueprints\\crafting\\vehiclegear\\shield\\bp_craft_shld_seco_s03_haven_scitem.json": {
    "itemClass": "civilian",
    "grade": "D"
  },
  "LIVEfiles\\libs\\foundry\\records\\crafting\\blueprints\\crafting\\vehiclegear\\shield\\bp_craft_shld_yorm_s01_falco_scitem.json": {
    "itemClass": "competition",
    "grade": "D"
  },
  "LIVEfiles\\libs\\foundry\\records\\crafting\\blueprints\\crafting\\vehiclegear\\shield\\bp_craft_shld_yorm_s01_jaghte_scitem.json": {
    "itemClass": "competition",
    "grade": "B"
  },
  "LIVEfiles\\libs\\foundry\\records\\crafting\\blueprints\\crafting\\vehiclegear\\shield\\bp_craft_shld_yorm_s01_targa_scitem.json": {
    "itemClass": "competition",
    "grade": "C"
  },
  "LIVEfiles\\libs\\foundry\\records\\crafting\\blueprints\\crafting\\vehiclegear\\shield\\bp_craft_shld_yorm_s02_bamoty_scitem.json": {
    "itemClass": "competition",
    "grade": "D"
  },
  "LIVEfiles\\libs\\foundry\\records\\crafting\\blueprints\\crafting\\vehiclegear\\shield\\bp_craft_shld_yorm_s02_haltur_scitem.json": {
    "itemClass": "competition",
    "grade": "B"
  },
  "LIVEfiles\\libs\\foundry\\records\\crafting\\blueprints\\crafting\\vehiclegear\\shield\\bp_craft_shld_yorm_s02_trenta_scitem.json": {
    "itemClass": "competition",
    "grade": "C"
  },
  "LIVEfiles\\libs\\foundry\\records\\crafting\\blueprints\\crafting\\vehiclegear\\tractorbeam\\bp_craft_grin_tractorbeam_s1.json": {
    "grade": "A"
  },
  "LIVEfiles\\libs\\foundry\\records\\crafting\\blueprints\\crafting\\vehiclegear\\tractorbeam\\bp_craft_grin_tractorbeam_s2.json": {
    "grade": "A"
  },
  "LIVEfiles\\libs\\foundry\\records\\crafting\\blueprints\\crafting\\vehiclegear\\tractorbeam\\bp_craft_grin_tractorbeam_s3.json": {
    "grade": "A"
  },
  "LIVEfiles\\libs\\foundry\\records\\crafting\\blueprints\\crafting\\vehiclegear\\tractorbeam\\bp_craft_wep_tractorbeam_s1_military_1.json": {
    "grade": "A"
  },
  "LIVEfiles\\libs\\foundry\\records\\crafting\\blueprints\\crafting\\vehiclegear\\tractorbeam\\bp_craft_wep_tractorbeam_s1_utility_1.json": {
    "grade": "A"
  },
  "LIVEfiles\\libs\\foundry\\records\\crafting\\blueprints\\crafting\\vehiclegear\\tractorbeam\\bp_craft_wep_tractorbeam_s1_utility_2.json": {
    "grade": "A"
  },
  "LIVEfiles\\libs\\foundry\\records\\crafting\\blueprints\\crafting\\vehiclegear\\tractorbeam\\bp_craft_wep_tractorbeam_s2_military_1.json": {
    "grade": "A"
  },
  "LIVEfiles\\libs\\foundry\\records\\crafting\\blueprints\\crafting\\vehiclegear\\tractorbeam\\bp_craft_wep_tractorbeam_s2_utility_1.json": {
    "grade": "A"
  },
  "LIVEfiles\\libs\\foundry\\records\\crafting\\blueprints\\crafting\\vehiclegear\\tractorbeam\\bp_craft_wep_tractorbeam_s2_utility_2.json": {
    "grade": "A"
  },
  "LIVEfiles\\libs\\foundry\\records\\crafting\\blueprints\\crafting\\vehiclegear\\tractorbeam\\bp_craft_wep_tractorbeam_s3_military_1.json": {
    "grade": "A"
  },
  "LIVEfiles\\libs\\foundry\\records\\crafting\\blueprints\\crafting\\vehiclegear\\tractorbeam\\bp_craft_wep_tractorbeam_s3_utility_1.json": {
    "grade": "A"
  },
  "LIVEfiles\\libs\\foundry\\records\\crafting\\blueprints\\crafting\\vehiclegear\\tractorbeam\\bp_craft_wep_tractorbeam_s3_utility_2.json": {
    "grade": "A"
  },
  "LIVEfiles\\libs\\foundry\\records\\crafting\\blueprints\\crafting\\vehiclegear\\weapons\\$templates\\ballistic\\bp_craft_banu_tachyoncannon_s1.json": {
    "grade": "A"
  },
  "LIVEfiles\\libs\\foundry\\records\\crafting\\blueprints\\crafting\\vehiclegear\\weapons\\$templates\\ballistic\\bp_craft_banu_tachyoncannon_s2.json": {
    "grade": "A"
  },
  "LIVEfiles\\libs\\foundry\\records\\crafting\\blueprints\\crafting\\vehiclegear\\weapons\\$templates\\ballistic\\bp_craft_banu_tachyoncannon_s3.json": {
    "grade": "A"
  },
  "LIVEfiles\\libs\\foundry\\records\\crafting\\blueprints\\crafting\\vehiclegear\\weapons\\$templates\\ballistic\\bp_craft_mxox_neutroncannon_s1.json": {
    "grade": "A"
  },
  "LIVEfiles\\libs\\foundry\\records\\crafting\\blueprints\\crafting\\vehiclegear\\weapons\\$templates\\ballistic\\bp_craft_mxox_neutroncannon_s2.json": {
    "grade": "A"
  },
  "LIVEfiles\\libs\\foundry\\records\\crafting\\blueprints\\crafting\\vehiclegear\\weapons\\$templates\\ballistic\\bp_craft_mxox_neutroncannon_s3.json": {
    "grade": "A"
  },
  "LIVEfiles\\libs\\foundry\\records\\crafting\\blueprints\\crafting\\vehiclegear\\weapons\\$templates\\ballistic\\bp_craft_mxox_neutronrepeater_s1.json": {
    "grade": "A"
  },
  "LIVEfiles\\libs\\foundry\\records\\crafting\\blueprints\\crafting\\vehiclegear\\weapons\\$templates\\ballistic\\bp_craft_mxox_neutronrepeater_s2.json": {
    "grade": "A"
  },
  "LIVEfiles\\libs\\foundry\\records\\crafting\\blueprints\\crafting\\vehiclegear\\weapons\\$templates\\ballistic\\bp_craft_mxox_neutronrepeater_s3.json": {
    "grade": "A"
  },
  "LIVEfiles\\libs\\foundry\\records\\crafting\\blueprints\\crafting\\vehiclegear\\weapons\\$templates\\ballistic\\bp_craft_toag_lasergatling_s2.json": {
    "grade": "A"
  },
  "LIVEfiles\\libs\\foundry\\records\\crafting\\blueprints\\crafting\\vehiclegear\\weapons\\ballistic\\cannon\\bp_craft_behr_ballisticcannon_s4.json": {
    "grade": "A"
  },
  "LIVEfiles\\libs\\foundry\\records\\crafting\\blueprints\\crafting\\vehiclegear\\weapons\\ballistic\\cannon\\bp_craft_behr_ballisticcannon_vng_s2.json": {
    "grade": "A"
  },
  "LIVEfiles\\libs\\foundry\\records\\crafting\\blueprints\\crafting\\vehiclegear\\weapons\\ballistic\\cannon\\bp_craft_espr_ballisticcannon_s1.json": {
    "grade": "A"
  },
  "LIVEfiles\\libs\\foundry\\records\\crafting\\blueprints\\crafting\\vehiclegear\\weapons\\ballistic\\cannon\\bp_craft_espr_ballisticcannon_s2.json": {
    "grade": "A"
  },
  "LIVEfiles\\libs\\foundry\\records\\crafting\\blueprints\\crafting\\vehiclegear\\weapons\\ballistic\\cannon\\bp_craft_espr_ballisticcannon_s3.json": {
    "grade": "A"
  },
  "LIVEfiles\\libs\\foundry\\records\\crafting\\blueprints\\crafting\\vehiclegear\\weapons\\ballistic\\cannon\\bp_craft_espr_ballisticcannon_s4.json": {
    "grade": "A"
  },
  "LIVEfiles\\libs\\foundry\\records\\crafting\\blueprints\\crafting\\vehiclegear\\weapons\\ballistic\\cannon\\bp_craft_espr_ballisticcannon_s5.json": {
    "grade": "A"
  },
  "LIVEfiles\\libs\\foundry\\records\\crafting\\blueprints\\crafting\\vehiclegear\\weapons\\ballistic\\cannon\\bp_craft_espr_ballisticcannon_s6.json": {
    "grade": "A"
  },
  "LIVEfiles\\libs\\foundry\\records\\crafting\\blueprints\\crafting\\vehiclegear\\weapons\\ballistic\\cannon\\bp_craft_gats_ballisticcannon_s1.json": {
    "grade": "A"
  },
  "LIVEfiles\\libs\\foundry\\records\\crafting\\blueprints\\crafting\\vehiclegear\\weapons\\ballistic\\cannon\\bp_craft_gats_ballisticcannon_s2.json": {
    "grade": "A"
  },
  "LIVEfiles\\libs\\foundry\\records\\crafting\\blueprints\\crafting\\vehiclegear\\weapons\\ballistic\\cannon\\bp_craft_gats_ballisticcannon_s3.json": {
    "grade": "A"
  },
  "LIVEfiles\\libs\\foundry\\records\\crafting\\blueprints\\crafting\\vehiclegear\\weapons\\ballistic\\cannon\\bp_craft_kbar_ballisticcannon_s1.json": {
    "grade": "A"
  },
  "LIVEfiles\\libs\\foundry\\records\\crafting\\blueprints\\crafting\\vehiclegear\\weapons\\ballistic\\cannon\\bp_craft_kbar_ballisticcannon_s2.json": {
    "grade": "A"
  },
  "LIVEfiles\\libs\\foundry\\records\\crafting\\blueprints\\crafting\\vehiclegear\\weapons\\ballistic\\cannon\\bp_craft_kbar_ballisticcannon_s3.json": {
    "grade": "A"
  },
  "LIVEfiles\\libs\\foundry\\records\\crafting\\blueprints\\crafting\\vehiclegear\\weapons\\ballistic\\gatling\\bp_craft_apar_ballisticgatling_s4.json": {
    "grade": "A"
  },
  "LIVEfiles\\libs\\foundry\\records\\crafting\\blueprints\\crafting\\vehiclegear\\weapons\\ballistic\\gatling\\bp_craft_apar_ballisticgatling_s6.json": {
    "grade": "A"
  },
  "LIVEfiles\\libs\\foundry\\records\\crafting\\blueprints\\crafting\\vehiclegear\\weapons\\ballistic\\gatling\\bp_craft_behr_ballisticgatling_s4.json": {
    "grade": "A"
  },
  "LIVEfiles\\libs\\foundry\\records\\crafting\\blueprints\\crafting\\vehiclegear\\weapons\\ballistic\\gatling\\bp_craft_behr_ballisticgatling_s5.json": {
    "grade": "A"
  },
  "LIVEfiles\\libs\\foundry\\records\\crafting\\blueprints\\crafting\\vehiclegear\\weapons\\ballistic\\gatling\\bp_craft_behr_ballisticgatling_s6.json": {
    "grade": "A"
  },
  "LIVEfiles\\libs\\foundry\\records\\crafting\\blueprints\\crafting\\vehiclegear\\weapons\\ballistic\\gatling\\bp_craft_gats_ballisticgatling_s1.json": {
    "grade": "A"
  },
  "LIVEfiles\\libs\\foundry\\records\\crafting\\blueprints\\crafting\\vehiclegear\\weapons\\ballistic\\gatling\\bp_craft_gats_ballisticgatling_s2.json": {
    "grade": "A"
  },
  "LIVEfiles\\libs\\foundry\\records\\crafting\\blueprints\\crafting\\vehiclegear\\weapons\\ballistic\\gatling\\bp_craft_gats_ballisticgatling_s3.json": {
    "grade": "A"
  },
  "LIVEfiles\\libs\\foundry\\records\\crafting\\blueprints\\crafting\\vehiclegear\\weapons\\ballistic\\gatling\\bp_craft_krig_ballisticgatling_s2.json": {
    "grade": "A"
  },
  "LIVEfiles\\libs\\foundry\\records\\crafting\\blueprints\\crafting\\vehiclegear\\weapons\\ballistic\\massdriver\\bp_craft_apar_massdriver_s2.json": {
    "grade": "A"
  },
  "LIVEfiles\\libs\\foundry\\records\\crafting\\blueprints\\crafting\\vehiclegear\\weapons\\ballistic\\massdriver\\bp_craft_klwe_massdriver_s1.json": {
    "grade": "A"
  },
  "LIVEfiles\\libs\\foundry\\records\\crafting\\blueprints\\crafting\\vehiclegear\\weapons\\ballistic\\massdriver\\bp_craft_klwe_massdriver_s2.json": {
    "grade": "A"
  },
  "LIVEfiles\\libs\\foundry\\records\\crafting\\blueprints\\crafting\\vehiclegear\\weapons\\ballistic\\massdriver\\bp_craft_klwe_massdriver_s3.json": {
    "grade": "A"
  },
  "LIVEfiles\\libs\\foundry\\records\\crafting\\blueprints\\crafting\\vehiclegear\\weapons\\ballistic\\repeater\\bp_craft_behr_ballisticrepeater_s1.json": {
    "grade": "A"
  },
  "LIVEfiles\\libs\\foundry\\records\\crafting\\blueprints\\crafting\\vehiclegear\\weapons\\ballistic\\repeater\\bp_craft_behr_ballisticrepeater_s2.json": {
    "grade": "A"
  },
  "LIVEfiles\\libs\\foundry\\records\\crafting\\blueprints\\crafting\\vehiclegear\\weapons\\ballistic\\repeater\\bp_craft_behr_ballisticrepeater_s3.json": {
    "grade": "A"
  },
  "LIVEfiles\\libs\\foundry\\records\\crafting\\blueprints\\crafting\\vehiclegear\\weapons\\ballistic\\repeater\\bp_craft_behr_ballisticrepeater_vng_s2.json": {
    "grade": "A"
  },
  "LIVEfiles\\libs\\foundry\\records\\crafting\\blueprints\\crafting\\vehiclegear\\weapons\\ballistic\\scatter\\bp_craft_apar_ballisticscattergun_s1.json": {
    "grade": "A"
  },
  "LIVEfiles\\libs\\foundry\\records\\crafting\\blueprints\\crafting\\vehiclegear\\weapons\\ballistic\\scatter\\bp_craft_apar_ballisticscattergun_s2.json": {
    "grade": "A"
  },
  "LIVEfiles\\libs\\foundry\\records\\crafting\\blueprints\\crafting\\vehiclegear\\weapons\\ballistic\\scatter\\bp_craft_apar_ballisticscattergun_s3.json": {
    "grade": "A"
  },
  "LIVEfiles\\libs\\foundry\\records\\crafting\\blueprints\\crafting\\vehiclegear\\weapons\\distortion\\cannon\\bp_craft_behr_distortioncannon_vng_s2.json": {
    "grade": "A"
  },
  "LIVEfiles\\libs\\foundry\\records\\crafting\\blueprints\\crafting\\vehiclegear\\weapons\\distortion\\cannon\\bp_craft_jokr_distortioncannon_s1.json": {
    "grade": "A"
  },
  "LIVEfiles\\libs\\foundry\\records\\crafting\\blueprints\\crafting\\vehiclegear\\weapons\\distortion\\cannon\\bp_craft_jokr_distortioncannon_s2.json": {
    "grade": "A"
  },
  "LIVEfiles\\libs\\foundry\\records\\crafting\\blueprints\\crafting\\vehiclegear\\weapons\\distortion\\cannon\\bp_craft_jokr_distortioncannon_s3.json": {
    "grade": "A"
  },
  "LIVEfiles\\libs\\foundry\\records\\crafting\\blueprints\\crafting\\vehiclegear\\weapons\\distortion\\repeater\\bp_craft_asad_distortionrepeater_s1.json": {
    "grade": "A"
  },
  "LIVEfiles\\libs\\foundry\\records\\crafting\\blueprints\\crafting\\vehiclegear\\weapons\\distortion\\repeater\\bp_craft_asad_distortionrepeater_s2.json": {
    "grade": "A"
  },
  "LIVEfiles\\libs\\foundry\\records\\crafting\\blueprints\\crafting\\vehiclegear\\weapons\\distortion\\repeater\\bp_craft_asad_distortionrepeater_s3.json": {
    "grade": "A"
  },
  "LIVEfiles\\libs\\foundry\\records\\crafting\\blueprints\\crafting\\vehiclegear\\weapons\\distortion\\repeater\\bp_craft_behr_distortionrepeater_vng_s2.json": {
    "grade": "A"
  },
  "LIVEfiles\\libs\\foundry\\records\\crafting\\blueprints\\crafting\\vehiclegear\\weapons\\laser\\cannon\\bp_craft_amrs_lasercannon_s1.json": {
    "grade": "A"
  },
  "LIVEfiles\\libs\\foundry\\records\\crafting\\blueprints\\crafting\\vehiclegear\\weapons\\laser\\cannon\\bp_craft_amrs_lasercannon_s2.json": {
    "grade": "A"
  },
  "LIVEfiles\\libs\\foundry\\records\\crafting\\blueprints\\crafting\\vehiclegear\\weapons\\laser\\cannon\\bp_craft_amrs_lasercannon_s3.json": {
    "grade": "A"
  },
  "LIVEfiles\\libs\\foundry\\records\\crafting\\blueprints\\crafting\\vehiclegear\\weapons\\laser\\cannon\\bp_craft_amrs_lasercannon_s4.json": {
    "grade": "A"
  },
  "LIVEfiles\\libs\\foundry\\records\\crafting\\blueprints\\crafting\\vehiclegear\\weapons\\laser\\cannon\\bp_craft_amrs_lasercannon_s5.json": {
    "grade": "A"
  },
  "LIVEfiles\\libs\\foundry\\records\\crafting\\blueprints\\crafting\\vehiclegear\\weapons\\laser\\cannon\\bp_craft_amrs_lasercannon_s6.json": {
    "grade": "A"
  },
  "LIVEfiles\\libs\\foundry\\records\\crafting\\blueprints\\crafting\\vehiclegear\\weapons\\laser\\cannon\\bp_craft_behr_lasercannon_s1.json": {
    "grade": "A"
  },
  "LIVEfiles\\libs\\foundry\\records\\crafting\\blueprints\\crafting\\vehiclegear\\weapons\\laser\\cannon\\bp_craft_behr_lasercannon_s2.json": {
    "grade": "A"
  },
  "LIVEfiles\\libs\\foundry\\records\\crafting\\blueprints\\crafting\\vehiclegear\\weapons\\laser\\cannon\\bp_craft_behr_lasercannon_s3.json": {
    "grade": "A"
  },
  "LIVEfiles\\libs\\foundry\\records\\crafting\\blueprints\\crafting\\vehiclegear\\weapons\\laser\\cannon\\bp_craft_behr_lasercannon_s4.json": {
    "grade": "A"
  },
  "LIVEfiles\\libs\\foundry\\records\\crafting\\blueprints\\crafting\\vehiclegear\\weapons\\laser\\cannon\\bp_craft_behr_lasercannon_s5.json": {
    "grade": "A"
  },
  "LIVEfiles\\libs\\foundry\\records\\crafting\\blueprints\\crafting\\vehiclegear\\weapons\\laser\\cannon\\bp_craft_behr_lasercannon_s6.json": {
    "grade": "A"
  },
  "LIVEfiles\\libs\\foundry\\records\\crafting\\blueprints\\crafting\\vehiclegear\\weapons\\laser\\cannon\\bp_craft_behr_lasercannon_vng_s2.json": {
    "grade": "A"
  },
  "LIVEfiles\\libs\\foundry\\records\\crafting\\blueprints\\crafting\\vehiclegear\\weapons\\laser\\cannon\\bp_craft_espr_lasercannon_s1.json": {
    "grade": "A"
  },
  "LIVEfiles\\libs\\foundry\\records\\crafting\\blueprints\\crafting\\vehiclegear\\weapons\\laser\\cannon\\bp_craft_espr_lasercannon_s2.json": {
    "grade": "A"
  },
  "LIVEfiles\\libs\\foundry\\records\\crafting\\blueprints\\crafting\\vehiclegear\\weapons\\laser\\cannon\\bp_craft_espr_lasercannon_s3.json": {
    "grade": "A"
  },
  "LIVEfiles\\libs\\foundry\\records\\crafting\\blueprints\\crafting\\vehiclegear\\weapons\\laser\\cannon\\bp_craft_espr_lasercannon_s4.json": {
    "grade": "A"
  },
  "LIVEfiles\\libs\\foundry\\records\\crafting\\blueprints\\crafting\\vehiclegear\\weapons\\laser\\cannon\\bp_craft_espr_lasercannon_s5.json": {
    "grade": "A"
  },
  "LIVEfiles\\libs\\foundry\\records\\crafting\\blueprints\\crafting\\vehiclegear\\weapons\\laser\\cannon\\bp_craft_espr_lasercannon_s6.json": {
    "grade": "A"
  },
  "LIVEfiles\\libs\\foundry\\records\\crafting\\blueprints\\crafting\\vehiclegear\\weapons\\laser\\cannon\\bp_craft_krig_lasercannon_s3.json": {
    "grade": "A"
  },
  "LIVEfiles\\libs\\foundry\\records\\crafting\\blueprints\\crafting\\vehiclegear\\weapons\\laser\\cannon\\bp_craft_kron_lasercannon_s1.json": {
    "grade": "A"
  },
  "LIVEfiles\\libs\\foundry\\records\\crafting\\blueprints\\crafting\\vehiclegear\\weapons\\laser\\cannon\\bp_craft_kron_lasercannon_s2.json": {
    "grade": "A"
  },
  "LIVEfiles\\libs\\foundry\\records\\crafting\\blueprints\\crafting\\vehiclegear\\weapons\\laser\\cannon\\bp_craft_kron_lasercannon_s3.json": {
    "grade": "A"
  },
  "LIVEfiles\\libs\\foundry\\records\\crafting\\blueprints\\crafting\\vehiclegear\\weapons\\laser\\repeater\\bp_craft_behr_laserrepeater_vng_s2.json": {
    "grade": "A"
  },
  "LIVEfiles\\libs\\foundry\\records\\crafting\\blueprints\\crafting\\vehiclegear\\weapons\\laser\\repeater\\bp_craft_hrst_laserrepeater_s1.json": {
    "grade": "A"
  },
  "LIVEfiles\\libs\\foundry\\records\\crafting\\blueprints\\crafting\\vehiclegear\\weapons\\laser\\repeater\\bp_craft_hrst_laserrepeater_s2.json": {
    "grade": "A"
  },
  "LIVEfiles\\libs\\foundry\\records\\crafting\\blueprints\\crafting\\vehiclegear\\weapons\\laser\\repeater\\bp_craft_hrst_laserrepeater_s3.json": {
    "grade": "A"
  },
  "LIVEfiles\\libs\\foundry\\records\\crafting\\blueprints\\crafting\\vehiclegear\\weapons\\laser\\repeater\\bp_craft_hrst_laserrepeater_s4.json": {
    "grade": "A"
  },
  "LIVEfiles\\libs\\foundry\\records\\crafting\\blueprints\\crafting\\vehiclegear\\weapons\\laser\\repeater\\bp_craft_hrst_laserrepeater_s5.json": {
    "grade": "A"
  },
  "LIVEfiles\\libs\\foundry\\records\\crafting\\blueprints\\crafting\\vehiclegear\\weapons\\laser\\repeater\\bp_craft_hrst_laserrepeater_s6.json": {
    "grade": "A"
  },
  "LIVEfiles\\libs\\foundry\\records\\crafting\\blueprints\\crafting\\vehiclegear\\weapons\\laser\\repeater\\bp_craft_hrst_storm_laserrepeater_s3.json": {
    "grade": "A"
  },
  "LIVEfiles\\libs\\foundry\\records\\crafting\\blueprints\\crafting\\vehiclegear\\weapons\\laser\\repeater\\bp_craft_klwe_laserrepeater_s1.json": {
    "grade": "A"
  },
  "LIVEfiles\\libs\\foundry\\records\\crafting\\blueprints\\crafting\\vehiclegear\\weapons\\laser\\repeater\\bp_craft_klwe_laserrepeater_s2.json": {
    "grade": "A"
  },
  "LIVEfiles\\libs\\foundry\\records\\crafting\\blueprints\\crafting\\vehiclegear\\weapons\\laser\\repeater\\bp_craft_klwe_laserrepeater_s3.json": {
    "grade": "A"
  },
  "LIVEfiles\\libs\\foundry\\records\\crafting\\blueprints\\crafting\\vehiclegear\\weapons\\laser\\repeater\\bp_craft_klwe_laserrepeater_s4.json": {
    "grade": "A"
  },
  "LIVEfiles\\libs\\foundry\\records\\crafting\\blueprints\\crafting\\vehiclegear\\weapons\\laser\\repeater\\bp_craft_klwe_laserrepeater_s5.json": {
    "grade": "A"
  },
  "LIVEfiles\\libs\\foundry\\records\\crafting\\blueprints\\crafting\\vehiclegear\\weapons\\laser\\repeater\\bp_craft_klwe_laserrepeater_s6.json": {
    "grade": "A"
  },
  "LIVEfiles\\libs\\foundry\\records\\crafting\\blueprints\\crafting\\vehiclegear\\weapons\\laser\\scatter\\bp_craft_amrs_scattergun_s3.json": {
    "grade": "A"
  },
  "LIVEfiles\\libs\\foundry\\records\\crafting\\blueprints\\crafting\\vehiclegear\\weapons\\laser\\scatter\\bp_craft_hrst_laserscattergun_s1.json": {
    "grade": "A"
  },
  "LIVEfiles\\libs\\foundry\\records\\crafting\\blueprints\\crafting\\vehiclegear\\weapons\\laser\\scatter\\bp_craft_hrst_laserscattergun_s3.json": {
    "grade": "A"
  },
  "LIVEfiles\\libs\\foundry\\records\\crafting\\blueprints\\crafting\\vehiclegear\\weapons\\laser\\scatter\\bp_hrst_laserscattergun_s2.json": {
    "grade": "A"
  }
}

export function getComponentMetadata(
  file?: string,
  _internalName?: string,
): ComponentMeta | null {
  if (file && COMPONENT_METADATA[file]) return COMPONENT_METADATA[file]
  return null
}
