import { bundledComponentCatalog } from '../lib/componentCatalog'
import { enrichMiningCatalog } from '../lib/miningDataHelpers'
import { miningLocations, gameOrdnance } from '../data'

export interface MiningData {
  id: number
  ore_name: string
  rarity: string
  locations: string[]
}

export interface ComponentData {
  id: number
  internal_id: string
  display_name: string
  component_type: string
  type_code: string
  manufacturer: string
  manufacturer_code: string
  size: number
  class: string
  class_code: string
  grade: string
  grade_rank: number
  full_label: string
}

export interface OrdnanceData {
  id: number
  internal_id: string
  display_name: string
  guidance: string
  guidance_code: string
  size: number
  is_gimbal: boolean
  is_torpedo: boolean
  ordnance_type: string
  manufacturer: string | null
  full_label: string
}

interface UseArchiveDataResult<T> {
  data: T[] | null
  loading: boolean
  error: string | null
  refetch: () => void
}

function staticResult<T>(data: T[]): UseArchiveDataResult<T> {
  return { data, loading: false, error: null, refetch: () => {} }
}

/**
 * All archive catalogs are served from the bundled parser output
 * (src/data/*.json) — the single source of truth generated by
 * `npm run parse-game-data`. No Supabase mirror tables are involved,
 * so a patch-day parse + deploy updates everything at once.
 */

function buildMiningCatalog(): MiningData[] {
  const rows: MiningData[] = []
  let id = 1
  for (const [rarity, ores] of Object.entries(miningLocations.rarityTiers)) {
    for (const ore of ores) {
      rows.push({ id: id++, ore_name: ore.name, rarity, locations: ore.locations ?? [] })
    }
  }
  return enrichMiningCatalog(rows)
}

function buildOrdnanceCatalog(): OrdnanceData[] {
  return gameOrdnance.ordnance
    .map((o, index) => ({
      id: index + 1,
      internal_id: o.internalId,
      display_name: o.displayName,
      guidance: o.guidance,
      guidance_code: o.guidanceCode,
      size: o.size,
      is_gimbal: o.isGimbal,
      is_torpedo: o.isTorpedo,
      ordnance_type: o.type,
      manufacturer: o.manufacturer ?? null,
      full_label: o.fullLabel,
    }))
    .sort((a, b) => a.size - b.size || a.display_name.localeCompare(b.display_name))
}

const bundledMiningCatalog = buildMiningCatalog()
const bundledOrdnanceCatalog = buildOrdnanceCatalog()

export function useMiningData(): UseArchiveDataResult<MiningData> {
  return staticResult(bundledMiningCatalog)
}

export function useComponentsData(): UseArchiveDataResult<ComponentData> {
  return staticResult(bundledComponentCatalog)
}

export function useOrdnanceData(): UseArchiveDataResult<OrdnanceData> {
  return staticResult(bundledOrdnanceCatalog)
}
