export type ArchivePageGuide = {
  id: string
  title: string
  description: string
  details: string[]
  relatesTo: string[]
}

export const PAGE_GUIDES: ArchivePageGuide[] = [
  {
    id: 'blueprints',
    title: 'Blueprints',
    description: 'The main hub for browsing all available crafting blueprints in Star Citizen.',
    details: [
      'Browse and filter blueprints by type, manufacturer, and availability',
      'FPS Armour includes combat clothing (armored apparel like the Bellator set): these show a Combat Clothing tag plus a garment type (Shirt, Jacket, Pants, Shoes, Gloves) instead of an armor weight/slot, and you can filter by garment type',
      'Material filter (cyan): type or pick any crafting material to show blueprints that require it — runs before category filters',
      'Search, category, material, and acquisition filters are remembered when you return (per account in this browser; Offline Mode uses local guest storage)',
      'See what reputation level is required to unlock each blueprint',
      'Mark blueprints as "acquired" to track your collection progress',
      'When you have at least one friend, a Members dropdown appears beside the acquisition filter — choose Mine or a friend to filter the grid by that collection (checkboxes still update only your own acquired marks)',
      'Missions on reward blueprints lists every contract that drops it and opens Browse Missions',
      'View the resources and components required to craft each item',
      'Click any blueprint to see detailed crafting requirements and DFP values',
      'Use the quality sliders to preview how resource quality affects final stats and DFP pricing',
      'Add a blueprint to your order draft from the detail view — continue on My Listings',
      '**RS Track** on a blueprint card or detail modal footer adds that blueprint\'s mineable ores to **Mining Tracker → RS Tracker** in one click — skips ores you already track',
      'Optional Display setting: group FPS weapon and armor variants into expandable family cards (off by default; only affects visible FPS items on this page)',
      'Acquired marks from BP Dumper sync here automatically — set up BP Dumper on Mission Tracker',
      'Offline Mode: acquired marks save locally until you sign in',
    ],
    relatesTo: ['Mission Tracker', 'Resource Tracker', 'My Listings', 'Friends', 'Settings'],
  },
  {
    id: 'wikelo',
    title: 'Wikelo',
    description: 'Browse every Wikelo Emporium barter trade — what to hand in and what you get back.',
    details: [
      'Every Wikelo trade is listed as a card: hand-in items on the front, full details on click',
      'Filter tags by reward category: Ships, Ground Vehicles, Armor, Weapons, Gear, Favors',
      'Search by trade name, hand-in item, or reward item',
      'Each card shows the Wikelo reputation gained and any customer-rank requirement',
      'Trades marked "Intro required" unlock after completing "Wikelo Arrive to System"',
      'Rose "NFR" tag: Not For Release in the game files — allegedly not offered live, but still listed so you can see what is in the data (hover for details)',
      'Trades that also award a crafting blueprint carry a ★ Blueprint tag',
      'DFP estimates the fair value of everything you hand in — ship and vehicle rewards show N/A because they are game bound',
      'Cart button (card and details) sends a trade\'s reward gear to your listing cart — finish on My Listings and choose WTS or WTB there (blueprints and game-bound vehicles excluded)',
      'Mission button jumps to the Wikelo Emporium faction in the Mission Tracker browse view',
    ],
    relatesTo: ['Blueprints', 'Mission Tracker', 'My Listings'],
  },
  {
    id: 'targets',
    title: 'Mission Tracker',
    description: 'Your personal wishlist of blueprints you\'re working towards unlocking.',
    details: [
      'Track blueprints from the main Blueprints page',
      'Browse Missions: pick a faction, then browse its mission pools',
      'Open a contract to expand Mission text (collapsed by default) — violet chips mark values the game fills in when you take the contract',
      'Missions with multiple regional pools are grouped under one title with location rows underneath',
      'Faction cards show which star systems that faction appears in',
      'Filter Browse Missions by star system (Stanton / Pyro / Nyx) — faction cards and mission lists update to match',
      'Inside a faction, tag chips appear beside System (Verified, contract type, career path, standing, NFR, etc. — not system or refresh-time tags) and filter the mission list',
      'Every contract with blueprint rewards is shown — nothing is hidden once you have collected all of a mission\'s blueprints (the count just turns green)',
      'See X/X progress (owned vs total) for each mission location',
      'Add unowned blueprints to your tracker directly from the browse view',
      'Use Missions on a blueprint card to list every contract that rewards it and jump to that mission',
      'My Tracker: view your tracked blueprints and build a mission checklist',
      'Mission rows use color-coded tags — see the legend below when this section is expanded',
      'Location tags: violet system/region tags plus green planet/moon tags (no tooltips)',
      'System-wide missions show only the system name (e.g. Pyro); region missions add Pyro A/B/C/D plus locations',
      'Mission tag order: Verified/Unverified → mobiGlas contract type → system/location → career path (e.g. Standing, Security) → standing tier (e.g. Jr. Contractor) → aUEC → rep points (then prereq / drop % / NFR when relevant); a second row shows how many offers, board refresh cadence, and a red Solo tag when the contract cannot be party-shared',
      'Rose "NFR" tag: contract is marked Not For Release in the game files — allegedly not on the live board, but still shown here (hover for details)',
      'Rep reward tags: green +rep you earn on completion; if a mission also lowers another faction\'s rep (e.g. CFP raids on Head Hunters), a red −rep tag shows the loss',
      'Purple "🔒 Unlocked by prior mission" tag: the contract only appears after an intro/starter mission — click for the unlock options (including starters that give no blueprint themselves); when any one of several prereqs unlocks the contract, every listed option is marked Intro',
      'Blue "📍" location tag: the contract only appears in your Contracts app while you\'re in that area (e.g. Hurston area, Pyro region B, Anywhere in Nyx)',
      'Blueprint "Missions" lists show prerequisite missions at the top so you know what to run first',
      'Investigation missions are mostly Hockrow Agency\'s Jorrit Dossier line at ASD\'s Onyx Facility (Stanton)',
      'Jorrit Dossier is a linear story chain — complete each step to unlock the next; repeat runs drop blueprints',
      'Collection missions include Wikelo Emporium craft contracts in Stanton (turn in gathered items for blueprints)',
      'BHG Hathor PAF bounties (Verified Bounty · Hathor · Planetary Alignment Facility) resolve to Stanton — Daymar and Aberdeen platform sites',
      'Scenario Progress rows (e.g. Orison Relief, Return of XenoThreat) are event contribution milestones with point thresholds — not Contracts-app mission titles',
      'Prioritize which factions to grind based on your goals',
      'Header buttons: BP Dumper (downloads + API key) and Live Tracker (active in-game missions while watching)',
      'Dismissible callout explains the BP Dumper + Live Tracker workflow',
      'Offline Mode: list saves locally until you sign in (then migrates automatically)',
    ],
    relatesTo: ['Blueprints', 'Factions', 'BP Dumper', 'Live Mission Tracker'],
  },
  {
    id: 'targets-live',
    title: 'Live Mission Tracker',
    description: 'Real-time view of in-game missions and pool blueprints still to acquire while BP Dumper is watching.',
    details: [
      'Open from Mission Tracker header buttons (BP Dumper + Live Tracker) or the avatar menu (BP Dumper only)',
      'Requires BP Dumper running in watch mode with your API key',
      'Left column: missions you accepted in-game right now',
      'Right column: pool blueprints from those missions you have not acquired yet',
      'Updates instantly when you accept missions, finish them, or receive blueprints',
      'ReSync button (header, shown while connected) re-pulls your active missions if the page shows connected but a mission is missing',
      'Color-coded status bar: connected in the PU, quit to menu, game closed, crash recovery, or back online',
      'Quitting to the menu or closing Star Citizen clears active missions (the game abandons them); they return when you load back into the PU',
      'After a crash, the bar waits for reconnect — missions may restore only if you rejoin within 30 minutes',
      'When those 30 minutes have passed, tracking returns to normal while BP Dumper keeps watching your log',
      'Missions with no remaining pool blueprints show in red',
      'When BP Dumper stops or disconnects, lists clear and a not-connected message appears',
      'If Dumper Apps is open but Star Citizen is closed (or you are not in the PU), Live Tracker can show not connected after a short idle window — that is expected',
    ],
    relatesTo: ['Mission Tracker', 'BP Dumper', 'Blueprints'],
  },
  {
    id: 'resources',
    title: 'Resource Tracker',
    description: 'Track your personal inventory of mined and refined resources.',
    details: [
      'Log quantities and quality levels of resources you\'ve collected',
      'Track store-purchased refined materials at Purchased (Q0)',
      '**Friends Resources** tab (next to My Resources) appears when you have at least one friend — pick a friend from the Members dropdown to browse their stock in a read-only list (search, quality, and location chips); you cannot edit their inventory',
      '**Can Craft** always uses only your My Resources — never a friend’s stock',
      '**Can Craft** tab lists acquired blueprints you can make right now from your My Resources stock — including recipes that need gems or other whole-unit harvestables (same blueprint cards and filters as the Blueprints page)',
      'On Can Craft, note chips (plus **ALL**) let you scope craftability to one stock location; **ALL** (default) uses every card. Craft deducts only from cards that match the selected chip',
      'Open any ready-to-craft blueprint in the Can Craft tab to find a green **Craft** button under its materials — pick the quality tier to use for each material (only the tiers you actually hold are shown), then craft to deduct the exact amounts from My Resources',
      'The Craft button greys out if the quality you picked for a material doesn\'t have enough on hand, and locks for a couple of seconds after each craft to prevent accidental double-clicks',
      'Optional **Close, no Cigar** includes nearly-ready recipes from your My Resources: every required material at least 70% on hand; for two or more materials, also those fully stocked except one (that one may be missing). These do not get a Craft button until you have enough',
      'Switch between Cards (edit quantities) and List (read-only overview with notes) on My Resources / Site Total',
      'Optional notes (e.g. location) split the same resource and quality into separate stock cards — notes match case-insensitively when adding',
      'On My Resources, stock notes (e.g. hangar / ship) automatically become location filter chips — variants like `arcL1`, `Arc l1`, and `ARC-l1` collapse into one; cards with no note use an **Empty** chip; chips refresh when you add or edit cards',
      'Filter by quality band on both views — each Q-tier stays on its own row',
      'Mined/refined ore uses quality bands (typically Q500–Q1000) — higher quality = exponentially higher DFP value',
      'Salvage and trade goods use fixed Q0 tiers',
      'Perfect for tracking what you have available for crafting or trading',
      'Each stock card and list row shows a blue **UEX** chip (on commodities) — click it to see every terminal that buys or sells that material, with SCU box sizes, in a popup. Powered by UEX',
      'Offline Mode: inventory saves locally until you sign in (then migrates automatically)',
    ],
    relatesTo: ['Blueprints', 'Mining Tracker', 'Commodity Lookup', 'Friends'],
  },
  {
    id: 'mining-tracker',
    title: 'Mining Tracker',
    description:
      'Compare RS signatures, plan rocks with the calculator, get loadout advice, browse where ores spawn, and run crew payout ledgers.',
    details: [
      'Three tabs: **RS Tracker** (signature reference + tools on the right), **Mining Guide** (browse ores and locations), and **Ledgers** (crew payout books — RSI-verified members only)',
      '**RS Tracker** lists each ship-mining ore\'s base RS signature and typical cluster spawn odds. Use it to sanity-check what your in-game scanner is showing',
      'Track up to two cards per ore — **Surface** and **Asteroid** — each with composition bands, cluster rows, and spawn context. Add cards with Track Surface / Track Asteroid on a card or from the Mining Guide',
      'Location-specific cards pin data to one site (header shows At [location]). Track a site from ore detail or location browse when you care about one belt or moon, not the whole profile',
      'Click any tracked card to load its ore, deposit type, location, and expected composition into the **Rock Calculator** — handy when you know the deposit type but are punching in a fresh fracture scan',
      '**Rock Calculator** (RS Tracker sidebar): enter **mass**, **resistance**, and **instability** from your HUD for breakability and power-required readouts',
      '**Gadgets in use**: pick up to two mining gadgets (Sabir, Stalwart, BoreMax, etc.) from the two dropdowns. A gadget modifies the **rock\'s base stats** (resistance and instability) before your head/module math applies, so Power required and head plans update to match what you actually deploy. The same gadget cannot be chosen in both slots',
      'The calculator also shows an **Estimated Window Size** bar — a green bar whose thickness previews how big the optimal charge window will be for that ore (head plans show it adjusted per head\'s modules)',
      'Enter **total rock SCU** and each material\'s **%** from your scan. **Inert** fills automatically as whatever remains after valuable lines — you do not type inert manually',
      'Many ores show the primary element twice (**High** and **Low** bands) as separate rows — match the two composition lines from your scanner',
      'Each material row has a **Q band** picker for ledger export. The **DFP** column beside each row is always fair-value at purchased (Q0) so you can compare yield value without changing bands',
      'Search for an ore or load from a tracked card. Toggle **Surface / Asteroid** when the ore has both deposit types. The **location** dropdown lists known spawn sites for that ore and type',
      '**Smart Cracker** (button in the calculator header) opens a loadout planner and **automated crack advisor**. Enter rock mass and resistance in the calculator for breakability, gadget fit, and crew head plans — you can still open Smart Cracker anytime to edit loadouts',
      'Smart Cracker compares your selected ship and loadout against the rock, warns if a head cannot break it, suggests **throttle and head assignments** (including multi-crew Mole setups), and recommends **gadgets** with alternates for different jobs (fracture power, instability, charge window). Gadgets you have already picked in **Gadgets in use** are folded into the rock and skipped as suggestions — up to two gadget ports total',
      '**Mole crew** (check **Crew** in the Rock Calculator header, or uncheck **Solo mining** in Smart Cracker): lighter heads run **full @ 100%** first; the driver finishes at computed throttle just under the equalizer (6% under when all three contribute). Driver is picked by module stack and instability — not always the heaviest head',
      '**CHP** (Crew Head Plan) in the calculator header when **Crew** is checked on Mole — pick **2X CHP** (two seats manned) or **3X+ CHP** (full crew) for a coordinated throttle plan: supports fire first, one seat backs down under the equalizer, and the driver ramps up last to crack (mass + resistance required)',
      '**SHP** (Solo Head Plan) in the calculator header in solo mode — on **Mole**, shows every head with a status: **green** = recommended seat with a starting throttle, **yellow** = could work but not ideal (throttle shown), **off** = cannot crack this rock; on **Prospector, Golem, ROC**, shows pro-tip suggestions only',
      'SHP starting throttles target the **stable hold point** — expect to feather power **up** from there to build charge, especially on high-instability rocks',
      'Head plans include a **"hold within Xm"** reminder — staying inside the laser\'s optimal range matters as much as throttle (power falls off fast beyond it)',
      '**Module swap suggestions** appear when a swap genuinely helps: unlocking an uncrackable rock, freeing up throttle headroom, or widening a narrow charge window. Modules can be swapped on-the-fly at the head — swap ideas cover **passive** modules; active modules are toggled, not swapped',
      '**Active modules** are off by default — the plan runs on your passive baseline. When a rock will not crack on passives, the head plan tells you **which equipped actives to switch on** (the fewest needed, best throttle headroom), so you avoid unnecessary charge drain and instability. Every installed active can run at the same time (up to the head\'s module slots)',
      'In the loadout editor, the **Effective totals** card shows two numbers per stat: the normal value is your passive baseline, and a **blue value after the /** is that stat with all active modules switched on',
      '**Mole + Solo** (**Crew** unchecked in the calculator, or **Solo mining** checked in Smart Cracker): one laser at a time like a Prospector',
      'Sign in to save loadouts to your account (works on any device). RSI verification is **not** required for Smart Cracker or loadouts — only for Ledgers',
      'Each ship has a factory **Default** loadout plus up to **three custom** slots. Swap heads and modules freely in Smart Cracker — changes preview live and **do not auto-save** until you click **Save** (custom slots) or **Save as New** (copies into the next custom slot; Default is never overwritten)',
      '**Premade build** dropdown loads org and community templates (Mole + Prospector) into the editor for tweaking — still requires Save or Save as New to keep changes',
      'Choose head models, mining modules (Focus, Rieger, FLTR, XTR, etc.), and optionally enter your **crafted mining head** stats if you run a blueprint head',
      '**Golem** ships use the factory **Pitman** head only (no swapping to other S1 models). Custom slots still equip **two module hardpoints** and can optionally toggle **Crafted head** for a blueprint Pitman',
      'The **selected loadout** label above the calculator shows which setup Smart Cracker will use. Open Smart Cracker to change ship, slot, or edit modules',
      '**Mining Guide → By Ore**: filter by rarity, open an ore for composition and locations, jump to RS Tracker cards from location chips',
      '**Mining Guide → By Location**: pick a site and see which ores can spawn there, with spawn %, cluster odds, and composition tooltips',
      '**All Sites / Surface / Asteroid** filter narrows both guide views by deposit type — pick Asteroid to skip planetary weather when soloing a Mole',
      'Belt and cluster tooltips include a 📍 **find-it-in-game** hint: which QT markers or starmap search terms to use (e.g. Akiro Cluster sits near Pyro I L3)',
      'Click a belt/cluster location to open its **QT markers & stations** panel — organized by belt L-point or Pyro region (PYAM stations per Lagrange point, RAB/RMB cluster bases per region, BRK breaker stations) instead of one long list',
      'Chips marked **trace spawn (<0.01%)** are technically possible but effectively never worth farming — they sort last and appear dimmed',
      'Some regions use an **Overall** summary (e.g. broad asteroid cluster families) instead of listing every vague bucket as its own site',
      'Hand-mineable **gems** show cave vs surface availability per planet. Gems and hand mineables are guide reference only — they are not in the RS signature grid yet',
      'Compare in-game cluster readings: cluster RS ≈ node count × base RS on your reference card',
      'A blue **UEX** chip appears on tracked ore cards, the ore detail popup, and each ledger row (for tradable commodities) — click it to see every terminal that buys/sells that ore plus SCU box sizes, without leaving the page. Powered by UEX',
      '**Ledgers** (RSI-verified): create a book for a mining run, add rows per ore/gem with quantity and quality tier — matching ore + quality merges into one line',
      'Assign **crew** with RSI handles (green = verified member here, yellow = valid RSI not on site, red = fix before paying). Split by shares; **0 shares** members can get alternate compensation instead of pool aUEC',
      'Track deductibles and other profits, record **Paid so far** for partial payouts, mark crew **paid** when settled. Click payout or outstanding amounts to copy aUEC to clipboard',
      'Ledger managers can **share access** with other RSI-verified members. Crew and managers get site notifications for access, ledger close, and payout updates',
      '**Export JSON** saves a ledger snapshot; **View JSON** loads a saved file read-only. Close when everyone is paid or delete from the toolbar anytime',
      'Closed crew ledgers contribute to **lifetime site totals** shown on the Ledgers tab',
      'Signed-in members sync tracker cards and loadouts. **Offline Mode** still lets you browse RS reference and the Mining Guide locally',
    ],
    relatesTo: ['Resource Tracker', 'My Listings', 'Commodity Lookup'],
  },
  {
    id: 'commodity-lookup',
    title: 'Commodity Lookup',
    description:
      'Find every terminal where you can sell or buy a commodity, plus the SCU box sizes offered. Powered by UEX.',
    details: [
      'Search or filter commodities by kind (Metal, Mineral, Gas, etc.), then click one to see where to trade it',
      '**Sell to** lists every terminal that buys the commodity from you (turn refined ore into aUEC); **Buy from** lists terminals that sell it to you',
      'Locations are grouped by star system (Stanton, Pyro, Nyx) and show the full breadcrumb down to the outpost, station, or city — including planet-side TDD kiosks like ArcCorp Mining Area 045',
      'Each location shows **UEX per-SCU price** (avg when available), plus the **SCU box (container) sizes** available for that commodity at that terminal',
      'A **Refinery** badge marks terminals with a refinery on-site',
      'Buy/sell locations, prices, and box sizes are crowdsourced by **UEX**; in-game prices can differ from UEX averages',
    ],
    relatesTo: ['Mining Tracker', 'Resource Tracker'],
  },
  {
    id: 'orders',
    title: 'My Listings',
    description: 'Manage your one WTB buy listing and one WTS sell listing, plus every transaction they create.',
    details: [
      'You have at most one open WTB listing and one open WTS listing — posting new items appends them to the matching listing',
      'Click Post items to open the builder for items (blueprints) and/or commodities (resources); Add to my WTB listing requests items, Add to my WTS listing offers stock on hand',
      'All pricing is exact DFP — no price sliders or adjustments; the live total and effective stat preview update as you compose the cart',
      'Expand any cart line to edit per-slot material qualities and see stat changes before posting',
      'Add blueprints from the Blueprints page into a session draft, then continue on My Listings',
      'My open listings shows each listing\'s lines — change quantities or remove lines inline; removing the last line closes the listing',
      'Listings are line-by-line on The Bazaar: pick which lines to buy or fulfill — whole-unit items (gems, armor crafts, etc.) can use a quantity; SCU resources must be taken as the full listed amount (refined cargo cannot be split in-game)',
      'Each purchase or fulfillment claim becomes its own child transaction with the normal handoff, deadlines, ratings, and rep limits',
      'Active transactions show itemized materials and resulting stats (base → final) for blueprint lines',
      'Release or cancel in-progress sales — claimed items restore to your listing with quantities intact',
      'Track active, completed, and archived transactions; confirm pickup on Active, then archive & rate on Completed',
      'After pickup, open the Completed tab — each order shows a purple Archive & rate button; both parties must rate to unlock new trades',
      'Requires a verified RSI Handle; new-member buyer limits apply per transaction, not to your open listings',
      'Offline Mode cannot create or manage listings',
    ],
    relatesTo: ['Resource Tracker', 'The Bazaar', 'Blueprints', 'Discord Webhooks'],
  },
  {
    id: 'The Bazaar',
    title: 'The Bazaar',
    description: 'Shop members\' WTS listings and fulfill WTB requests — pick exactly the items you want.',
    details: [
      'Two tabs: Fulfillment (WTB listings you can craft/supply for) and Store (WTS listings you can buy from)',
      'Search by item name and filter by minimum quality band — a listing matches if any of its lines match',
      'Fulfillment tab extras: min buyer rep filter and "Only listings with my blueprints" (you only need blueprints for the lines you pick)',
      'Listings collapse to a compact summary row (title, tag, member, price, rep) — click to expand line details; only one expands at a time',
      'Item-by-item checkout: check lines to buy or fulfill — set quantities on whole-unit items; SCU resources are always the full listed amount (refined cargo cannot be split) — unchecked lines stay listed',
      'Each checkout or fulfillment claim becomes its own transaction through the normal handoff, pickup, and rating flow',
      'Active transactions show the other party\'s in-game name — add them in Star Citizen to coordinate pickup',
      'Seller-side WTS: actions and status appear directly on each sale card — start handoff, mark ready, or cancel',
      'After marking a WTS sale ready, wait for the buyer to confirm pickup in My Listings → Active',
      'Rate completed trades on The Bazaar or My Listings → Completed — purple Archive & rate on each finished deal',
      'Cancel or release returns claimed items to the owner\'s listing with quantities restored',
      'Same reputation ratings for all paths; visible fulfiller/seller rep shows average delivery time (ddd:HH:mm from accept to ready) after 5 completed trades',
      'Requires a verified RSI Handle; fulfiller and buyer pending limits apply by role per transaction',
      'Friends’ open Bazaar listings are hidden from each other by design — not a bug',
      'Offline Mode shows an open-listing count teaser only — sign in to browse or trade',
      'Verify you have materials before claiming 800+ quality WTB blueprint lines',
      'Marketplace listing ads can deep-link here with ?highlight= — the matching listing expands and scrolls into view',
    ],
    relatesTo: ['My Listings', 'Resource Tracker', 'Friends', 'Settings'],
  },
  {
    id: 'discord-webhooks',
    title: 'Discord Webhooks',
    description: 'Route marketplace and personal deal alerts to your own Discord channel.',
    details: [
      'Paste a webhook URL from your Discord server (Integrations → Webhooks)',
      'My activity: pings when someone else moves your deal forward (accepted, ready, completed, released, etc.) — requires verified RSI Handle',
      'Marketplace activity (opt-in): new WTB/WTS listings, acceptances, and cancellations from other members — no RSI verification required',
      'Use the same channel URL in both sections if you want everything in one Discord channel',
      'Coalesced marketplace digests require New WTB, New WTS, or Listing cancelled — not Listing accepted alone',
      'You never receive marketplace pings for your own posts or actions (no self-echo)',
      'Order alerts include itemized lines with material summaries and effective stats when available',
      'Repeated post/cancel bursts from the same member may arrive as one grouped marketplace ping',
      'Support: staff replies and ticket resolved notices on your tickets',
      'One channel name and webhook URL per alert type — leave the URL blank to unregister',
      'Set up from your avatar menu → Webhooks after sign-in',
    ],
    relatesTo: ['My Listings', 'The Bazaar', 'Notifications'],
  },
  {
    id: 'notifications',
    title: 'Notifications',
    description: 'In-app alerts for marketplace activity from the header bell.',
    details: [
      'Bell icon in the header shows your unread notification count',
      'Notifications are grouped into collapsible categories — BP Dumper, WTB & Craft Orders, WTS Listings, Support, Mining Ledgers, Friends, and more',
      'Every category stays visible even when empty; expand a section to see its alerts or a None placeholder',
      'Alerts cover marketplace events such as order acceptances, ready-for-pickup, and status changes',
      'Friend request alerts: incoming show Accept / Deny (no Clear); outgoing show Cancel instead of Clear — under the Friends category',
      'Order alerts include a clickable link in the message — The Bazaar for seller/fulfiller actions, My Listings → Completed to archive & rate',
      'Itemized order summaries reflect blueprint stats and materials when the order includes them',
      'Click Clear on a notification to dismiss it — dismissed rows are deleted (no read history kept)',
      'Questionnaire prompts cannot be Cleared — open them and submit or decline to remove them',
      'Use Clear all to dismiss other notifications at once (questionnaire prompts are left until you respond)',
      'Active questionnaires also appear in the bottom Updates ticker — click a line to open the form (declined/submitted ones never show there)',
      'Unavailable while your account is pending approval',
    ],
    relatesTo: ['My Listings', 'The Bazaar', 'Friends'],
  },
  {
    id: 'friends',
    title: 'Friends',
    description:
      'Add approved members by RSI Handle, organize private groups, and view friends’ blueprints and resources.',
    details: [
      'Friends icon in the header (between notifications and your avatar) — add by RSI Handle, remove friends, and manage private groups',
      'Send a request by RSI Handle; the other member must accept before you are friends',
      'Until a request is accepted, only RSI Handles are shown (not real names) in requests and notifications',
      'Incoming and outgoing requests are handled in the notification bell (Friends category) — Accept, Deny, or Cancel there',
      'Create private group labels to organize your list; use the arrows to reorder groups — only you see your group names',
      'On Blueprints, pick a friend in Members to filter by their acquired collection (your checkboxes stay yours)',
      'On Resource Tracker, Friends Resources shows a friend’s stock in a read-only list',
      'Friends’ Bazaar listings stay hidden from each other by design',
      'Unavailable while your account is pending approval or in Offline Mode',
    ],
    relatesTo: ['Blueprints', 'Resource Tracker', 'The Bazaar', 'Notifications'],
  },
  {
    id: 'updates-ticker',
    title: 'Updates Ticker',
    description: 'Bottom bar that surfaces recent game-data changes and questionnaires.',
    details: [
      'When something is new, a slim Updates bar sits at the true bottom of every page (it never covers page content)',
      'Color-coded badges: Site Update, Game Update, Questionnaire, and Dumper Apps',
      'Short titles rotate in the bar; click a line for the full detail in a modal',
      'Game Update lines from the latest parse stay for 7 days; Site Update and Dumper Apps lines stay for 3 days',
      'Questionnaire lines open the form (answers stay anonymous); poll results use the Questionnaire badge',
      'If there is nothing to show, the ticker hides completely',
    ],
    relatesTo: ['Notifications', 'Blueprints', 'Mission Tracker', 'Wikelo'],
  },
  {
    id: 'partnership',
    title: 'Partnership',
    description:
      'Verified org leaders can apply so their org can offer help to members — medical, stuck lift, security, salvage, and more — with transparent pricing.',
    details: [
      'Visible under Account in the avatar menu only when your RSI Handle is verified',
      'Partnership means: members request a service from the site; partner Discord channels get the ping; first Accept wins',
      'Request Services (next to notifications, also available in guest/offline preview) lists **3rd Party FREE** / **3rd Party FEE** at the top — e.g. Call Medrunner (FREE) opens their client portal in a new tab (hover for a short description; their account may be required)',
      'Below that, signed-in members with a verified RSI Handle see partner **FREE SERVICES** and **FEE SERVICES**; the same type (e.g. Medical) can appear in both when some orgs offer FREE and others charge',
      'FREE requests only notify orgs that list that service as FREE; FEE requests only notify orgs that list a fee — Discord shows FREE or FEE for which option you clicked',
      'If no partner orgs are offering services you’ll see a short note under 3rd Party; partner Discord Accept still requires sign-in + verified RSI',
      'Actionable requests (medical, security, refuel, repair, CrimeStat, prison pickup, transport) need a short details note (max 250 chars); first Discord Accept wins; cooldown is per service × FREE/FEE',
      'Intel tips (report salvage / report pirate) need details + a Ctrl+V starmap screenshot with r_DisplayInfo 3 — no Accept; tip data is deleted after Discord delivery',
      'Apply with your RSI org page URL (Org SID fills in automatically), org name, and role — staff check Spectrum/RSI evidence before approval',
      'Submitting creates a Partnership Application Support ticket and can ping the Super-Admin Discord webhook',
      'After approval, manage which services you offer, pricing (default FREE), and a Discord webhook per service',
      'After approval, Partnership shows the Dumper Services bot invite URL — add it to the same Discord server as each webhook channel (Send Messages, Embed Links, Attach Files)',
      'Listed services and pricing must be transparent, honest, and upheld — bait pricing or refusing listed terms can revoke the partnership',
      'When an org Accepts your request, a modal shows that org’s name and the pricing they listed for that service',
      'Partnership webhooks are separate from personal Webhooks under Discord subscribe',
    ],
    relatesTo: ['Settings', 'Support', 'Updates', 'Site Rules'],
  },
  {
    id: 'contribute',
    title: 'Contribute',
    description:
      'Approved members can apply for a GitHub collaborator seat on the public dumpers_repo — triage issues, open pull requests, and request ladder upgrades.',
    details: [
      'Open Contribute from your avatar menu (Account) once your member account is approved',
      'Choose an entry seat: Triage (discuss/triage) or Contributor (push to open PRs)',
      'Applications and upgrades are reviewed by the lead maintainer — not automatic',
      'Active seats can request the next ladder step (Contributor → Reviewer → Maintainer) with justification and evidence links',
      'You can leave the team anytime; GitHub collaborator access is removed when you leave or are revoked',
      'Contributor Team access is separate from site officer/super-admin roles and does not grant signing or secrets',
    ],
    relatesTo: ['Settings', 'Updates', 'Dumper Apps'],
  },
  {
    id: 'settings',
    title: 'Settings',
    description: 'Manage your profile and account from your avatar menu.',
    details: [
      'Verify your RSI Handle: get a short code, paste it into your public RSI citizen Bio, then Verify (proves you control that page)',
      'Handle is only saved after Verify succeeds — Get code alone does not set it; Change clears your handle until you verify a new (or re-verify the old) one',
      'After verifying you can remove the code from your RSI bio',
      'Deduct inventory on craft complete: when enabled, finishing a WTB fulfillment deducts materials from My Resources (requires verified RSI Handle)',
      'Connect Google or Discord from Connected Accounts to sign in with either method on one account',
      'When provider emails match, sign-in automatically merges into your existing account',
      'Disconnect a linked provider from Settings if you have at least two sign-in methods connected',
      'Clear Collected Blueprints to reset your acquired blueprint list (starter blueprints may reappear on refresh)',
      'Clear Tracked Resources to wipe all quantities and notes from My Resources in the Resource Tracker',
      'Marketplace section (when an admin enables site-wide features): opt in or out of WTS listing ads, WTB listing ads, and live purchase toasts independently',
      'Live purchase toasts only show accepts while you are online — there is no backlog for missed events',
    ],
    relatesTo: ['Blueprints', 'Mission Tracker', 'Resource Tracker', 'Mining Tracker', 'BP Dumper', 'The Bazaar'],
  },
  {
    id: 'bp-dumper',
    title: 'Dumper Apps',
    description:
      'Desktop app that reads your local Star Citizen Game.log — not CIG servers — to sync blueprint unlocks and power Live Mission Tracker.',
    details: [
      'Open from Mission Tracker header buttons — BP Dumper for setup, Live Tracker for the live page — or the avatar menu',
      '**Windows:** download **DumperApps.exe** (built from the Python watcher) — it **searches for your Star Citizen install** (LIVE) for you, then paste your API key',
      '**macOS / Linux (or advanced Windows):** use **Python scripts** from Downloads (Python 3 + requirements.txt), then run `dumper.py --watch` — same auto-detect',
      'You can paste a custom path if auto-detect misses your install',
      'Does **not** download your craft-bench / inventory from CIG — only blueprint award lines found in local log files',
      'First run can import awards from `.log` files under detected log dirs, then watch mode tails the live Game.log',
      'Blueprints earned before those logs existed, or after logs were deleted, will not appear — mark those manually on Blueprints',
      'Copy your API key from this page and paste it when Dumper Apps asks on first run',
      'Regenerate your API key if compromised; the old key stops working immediately',
      'Windows updates come from GitHub Releases when Keep App Up to Date is on (Microsoft Store remains an optional listing for now)',
      'Download panel includes the SignPath Foundation code-signing credit and a link to the project Code signing policy (Authenticode signing after SignPath approval)',
      'Older builds are blocked by the server — update when prompted',
      'While watch mode runs, use Live Tracker to see active missions and remaining pool blueprints',
      'Successful imports appear under BP Dumper — Success in the notification bell',
    ],
    relatesTo: ['Blueprints', 'Mission Tracker', 'Live Mission Tracker', 'Mining Tracker', 'Notifications', 'Settings'],
  },
  {
    id: 'support',
    title: 'Support',
    description: 'Report issues or get help from site staff.',
    details: [
      'Access Support from the Help section of your avatar menu',
      'Report bugs or technical issues with the site',
      'Report inappropriate behavior from other members',
      'Get help with RSI Handle verification issues',
      'Request a new Partnership service type (Add New Service Request) or file Other for anything else',
      'View the status of your open tickets and respond to staff questions',
      'All ticket data is deleted after resolution for your privacy',
    ],
    relatesTo: ['Settings', 'Blueprints', 'Partnership'],
  },
  {
    id: 'components',
    title: 'Component Database',
    description: 'Browse ship components by type, size, grade, and manufacturer.',
    details: [
      'Filter by component type: coolers, power plants, shields, quantum drives',
      'Browse by size (S1-S4) and grade (A-D)',
      'See manufacturer information for each component',
      'Click any component to view detailed stats',
      'Compare upgrade paths between similar components',
    ],
    relatesTo: ['Blueprints'],
  },
  {
    id: 'ordnance',
    title: 'Ordnance Reference',
    description: 'Compare missiles and torpedoes by size, guidance type, and manufacturer.',
    details: [
      'Browse all missiles and torpedoes in the game',
      'Filter by guidance type: Cross-Section (CS), Electromagnetic (EM), Infrared (IR)',
      'Filter by size (S1-S9) to find compatible ordnance for your ship',
      'See manufacturer and full designation for each missile',
      'Understand guidance system differences for combat effectiveness',
    ],
    relatesTo: ['Blueprints', 'Component Database'],
  },
  {
    id: 'factions',
    title: 'Faction Reference',
    description: 'Understand reputation systems, standing tiers, and blueprint rewards.',
    details: [
      'View all factions and their reputation tiers',
      'See the reputation points required for each standing level',
      'Understand how faction standing affects blueprint availability',
      'Plan your reputation grind based on desired blueprints',
      'Cross-reference with Mission Tracker for efficient progression',
    ],
    relatesTo: ['Mission Tracker', 'Blueprints'],
  },
  {
    id: 'lore',
    title: 'Resource Lore',
    description: 'In-game flavor text and descriptions for commodities, ship components, armor, weapons, and more.',
    details: [
      'Browse lore for ores, commodities, ship components, armor, weapons, and flair items',
      'Search entries by name or description text',
      'Filter by category to explore related items and materials',
      'Learn the in-universe backstory for gear you use and resources you trade',
      'Data sourced directly from Star Citizen game files',
    ],
    relatesTo: ['Resource Tracker', 'Mining Tracker'],
  },
  {
    id: 'general',
    title: 'General Archive',
    description: 'External resources, quick tips, and data attribution.',
    details: [
      'Links to useful Star Citizen community resources',
      'Quick tips for mining, trading, and crafting',
      'Data source attribution and acknowledgments',
      'Information about how Dumper\'s Repo data is sourced and updated',
    ],
    relatesTo: ['Component Database', 'Resource Lore'],
  },
]
