export type ArchivePageGuide = {
  id: string
  title: string
  description: string
  details: string[]
  relatesTo: string[]
}

export const PAGE_GUIDES: ArchivePageGuide[] = [
  {
    id: 'blueprints',
    title: 'Blueprints',
    description: 'The main hub for browsing all available crafting blueprints in Star Citizen.',
    details: [
      'Browse and filter blueprints by type, manufacturer, and availability',
      'Material filter (cyan): type or pick any crafting material to show blueprints that require it — runs before category filters',
      'Search, category, material, and acquisition filters are remembered when you return (per account in this browser; Offline Mode uses local guest storage)',
      'See what reputation level is required to unlock each blueprint',
      'Mark blueprints as "acquired" to track your collection progress',
      'Missions on reward blueprints lists every contract that drops it and opens Browse Missions',
      'View the resources and components required to craft each item',
      'Click any blueprint to see detailed crafting requirements and DFP values',
      'Use the quality sliders to preview how resource quality affects final stats and DFP pricing',
      'Add a blueprint to your order draft from the detail view — continue on My Listings',
      'Optional Display setting: group FPS weapon and armor variants into expandable family cards (off by default; only affects visible FPS items on this page)',
      'Acquired marks from BP Dumper sync here automatically — set up BP Dumper on Mission Tracker',
      'Offline Mode: acquired marks save locally until you sign in',
    ],
    relatesTo: ['Mission Tracker', 'Resource Tracker', 'My Listings', 'Settings'],
  },
  {
    id: 'wikelo',
    title: 'Wikelo',
    description: 'Browse every Wikelo Emporium barter trade — what to hand in and what you get back.',
    details: [
      'Every Wikelo trade is listed as a card: hand-in items on the front, full details on click',
      'Filter tags by reward category: Ships, Ground Vehicles, Armor, Weapons, Gear, Favors',
      'Search by trade name, hand-in item, or reward item',
      'Each card shows the Wikelo reputation gained and any customer-rank requirement',
      'Trades marked "Intro required" unlock after completing "Wikelo Arrive to System"',
      'Trades that also award a crafting blueprint carry a ★ Blueprint tag',
      'DFP estimates the fair value of everything you hand in — ship and vehicle rewards show N/A because they are game bound',
      'Cart button (card and details) sends a trade\'s reward gear to your listing cart — finish on My Listings and choose WTS or WTB there (blueprints and game-bound vehicles excluded)',
      'Mission button jumps to the Wikelo Emporium faction in the Mission Tracker browse view',
    ],
    relatesTo: ['Blueprints', 'Mission Tracker', 'My Listings'],
  },
  {
    id: 'targets',
    title: 'Mission Tracker',
    description: 'Your personal wishlist of blueprints you\'re working towards unlocking.',
    details: [
      'Track blueprints from the main Blueprints page',
      'Browse Missions: pick a faction, then browse its mission pools',
      'Missions with multiple regional pools are grouped under one title with location rows underneath',
      'Faction cards show which star systems that faction appears in',
      'See X/X progress (owned vs total) for each mission location',
      'Add unowned blueprints to your tracker directly from the browse view',
      'Use Missions on a blueprint card to list every contract that rewards it and jump to that mission',
      'My Tracker: view your tracked blueprints and build a mission checklist',
      'Mission rows use color-coded tags — see the legend below when this section is expanded',
      'Location tags: violet system/region tags plus green planet/moon tags (no tooltips)',
      'System-wide missions show only the system name (e.g. Pyro); region missions add Pyro A/B/C/D plus locations',
      'Other tags: amber category, cyan rep requirement, red illegal, purple unlock level under blueprint names',
      'Rep reward tags: green +rep you earn on completion; if a mission also lowers another faction\'s rep (e.g. CFP raids on Head Hunters), a red −rep tag shows the loss',
      'Purple "🔒 Unlocked by prior mission" tag: the contract only appears after an intro/starter mission — click the tag to see which mission, its faction, and where it shows in the Contracts app',
      'Blue "📍" location tag: the contract only appears in your Contracts app while you\'re in that area (e.g. Hurston area, Pyro region B, Anywhere in Nyx)',
      'Blueprint "Missions" lists show prerequisite missions at the top so you know what to run first',
      'Investigation missions are mostly Hockrow Agency\'s Jorrit Dossier line at ASD\'s Onyx Facility (Stanton)',
      'Jorrit Dossier is a linear story chain — complete each step to unlock the next; repeat runs drop blueprints',
      'Collection missions include Wikelo Emporium craft contracts in Stanton (turn in gathered items for blueprints)',
      'BHG Hathor PAF bounties (Verified Bounty · Hathor · Planetary Alignment Facility) resolve to Stanton — Daymar and Aberdeen platform sites',
      'Prioritize which factions to grind based on your goals',
      'Header buttons: BP Dumper (downloads + API key) and Live Tracker (active in-game missions while watching)',
      'Dismissible callout explains the BP Dumper + Live Tracker workflow',
      'Offline Mode: list saves locally until you sign in (then migrates automatically)',
    ],
    relatesTo: ['Blueprints', 'Factions', 'BP Dumper', 'Live Mission Tracker'],
  },
  {
    id: 'targets-live',
    title: 'Live Mission Tracker',
    description: 'Real-time view of in-game missions and pool blueprints still to acquire while BP Dumper is watching.',
    details: [
      'Open from Mission Tracker header buttons (BP Dumper + Live Tracker) or the avatar menu (BP Dumper only)',
      'Requires BP Dumper running in watch mode with your API key',
      'Left column: missions you accepted in-game right now',
      'Right column: pool blueprints from those missions you have not acquired yet',
      'Updates instantly when you accept missions, finish them, or receive blueprints',
      'Color-coded status bar: connected in the PU, quit to menu, game closed, crash recovery, or back online',
      'Quit to menu or closing Star Citizen clears active missions until you load back into the PU',
      'After a crash, the bar waits for reconnect — missions may restore only if you rejoin within one hour',
      'When that hour has passed, tracking returns to normal while BP Dumper keeps watching your log',
      'Missions with no remaining pool blueprints show in red',
      'When BP Dumper stops or disconnects, lists clear and a not-connected message appears',
    ],
    relatesTo: ['Mission Tracker', 'BP Dumper', 'Blueprints'],
  },
  {
    id: 'resources',
    title: 'Resource Tracker',
    description: 'Track your personal inventory of mined and refined resources.',
    details: [
      'Log quantities and quality levels of resources you\'ve collected',
      'Track store-purchased refined materials at Purchased (Q0)',
      'Switch between Cards (edit quantities) and List (read-only overview with notes)',
      'Filter by quality band on both views — each Q-tier stays on its own row',
      'Mined/refined ore uses quality bands (typically Q500–Q1000) — higher quality = exponentially higher DFP value',
      'Salvage and trade goods use fixed Q0 tiers',
      'Perfect for tracking what you have available for crafting or trading',
      'Offline Mode: inventory saves locally until you sign in (then migrates automatically)',
    ],
    relatesTo: ['Blueprints', 'Mining Tracker'],
  },
  {
    id: 'mining-tracker',
    title: 'Mining Tracker',
    description:
      'Compare RS signatures, plan rocks with the calculator, get loadout advice, browse where ores spawn, and run crew payout ledgers.',
    details: [
      'Three tabs: **RS Tracker** (signature reference + tools on the right), **Mining Guide** (browse ores and locations), and **Ledgers** (crew payout books — RSI-verified members only)',
      '**RS Tracker** lists each ship-mining ore\'s base RS signature and typical cluster spawn odds. Use it to sanity-check what your in-game scanner is showing',
      'Track up to two cards per ore — **Surface** and **Asteroid** — each with composition bands, cluster rows, and spawn context. Add cards with Track Surface / Track Asteroid on a card or from the Mining Guide',
      'Location-specific cards pin data to one site (header shows At [location]). Track a site from ore detail or location browse when you care about one belt or moon, not the whole profile',
      'Click any tracked card to load its ore, deposit type, location, and expected composition into the **Rock Calculator** — handy when you know the deposit type but are punching in a fresh fracture scan',
      '**Rock Calculator** (RS Tracker sidebar): enter **mass**, **resistance**, and **instability** from your HUD for breakability and power-required readouts',
      'The calculator also shows an **Estimated Window Size** bar — a green bar whose thickness previews how big the optimal charge window will be for that ore (head plans show it adjusted per head\'s modules)',
      'Enter **total rock SCU** and each material\'s **%** from your scan. **Inert** fills automatically as whatever remains after valuable lines — you do not type inert manually',
      'Many ores show the primary element twice (**High** and **Low** bands) as separate rows — match the two composition lines from your scanner',
      'Each material row has a **Q band** picker for ledger export. The **DFP** column beside each row is always fair-value at purchased (Q0) so you can compare yield value without changing bands',
      'Search for an ore or load from a tracked card. Toggle **Surface / Asteroid** when the ore has both deposit types. The **location** dropdown lists known spawn sites for that ore and type',
      '**Smart Cracker** (button in the calculator header) opens a loadout planner and **automated crack advisor**. Enter rock mass and resistance in the calculator for breakability, gadget fit, and crew head plans — you can still open Smart Cracker anytime to edit loadouts',
      'Smart Cracker compares your selected ship and loadout against the rock, warns if a head cannot break it, flags **slow grinds** when full-blast power is only slightly over the equalizer (uses your composition Q bands to say if the wait is worth it), suggests **throttle and head assignments** (including multi-crew Mole setups), and recommends **one gadget per rock** with alternates for different jobs (fracture power, instability, charge window) — only one can be attached at a time',
      '**Mole crew** (check **Crew** in the Rock Calculator header, or uncheck **Solo mining** in Smart Cracker): lighter heads run **full @ 100%** first; the driver finishes at computed throttle just under the equalizer (6% under when all three contribute). Driver is picked by module stack and instability — not always the heaviest head',
      '**CHP** (Crew Head Plan) in the calculator header when **Crew** is checked on Mole — pick **2X CHP** (two seats manned) or **3X+ CHP** (full crew) for a coordinated throttle plan: supports fire first, one seat backs down under the equalizer, and the driver ramps up last to crack (mass + resistance required)',
      '**SHP** (Solo Head Plan) in the calculator header in solo mode — on **Mole**, shows every head with a status: **green** = recommended seat with a starting throttle, **yellow** = could work but not ideal (throttle shown), **off** = cannot crack this rock; on **Prospector, Golem, ROC**, shows pro-tip suggestions only',
      'SHP starting throttles target the **stable hold point** — expect to feather power **up** from there to build charge, especially on high-instability rocks',
      'Head plans include a **"hold within Xm"** reminder — staying inside the laser\'s optimal range matters as much as throttle (power falls off fast beyond it)',
      '**Module swap suggestions** appear when a swap genuinely helps: unlocking an uncrackable rock, freeing up throttle headroom, or widening a narrow charge window. Modules can be swapped on-the-fly at the head; active modules are left alone',
      '**Mole + Solo** (**Crew** unchecked in the calculator, or **Solo mining** checked in Smart Cracker): one laser at a time like a Prospector',
      'Sign in to save loadouts to your account (works on any device). RSI verification is **not** required for Smart Cracker or loadouts — only for Ledgers',
      'Each ship has a factory **Default** loadout plus up to **three custom** slots. Swap heads and modules freely in Smart Cracker — changes preview live and **do not auto-save** until you click **Save** (custom slots) or **Save as New** (copies into the next custom slot; Default is never overwritten)',
      '**Premade build** dropdown loads org and community templates (Mole + Prospector) into the editor for tweaking — still requires Save or Save as New to keep changes',
      'Choose head models, mining modules (Focus, Rieger, FLTR, XTR, etc.), and optionally enter your **crafted mining head** stats if you run a blueprint head',
      '**Golem** ships use the factory **Pitman** head only (no swapping to other S1 models). Custom slots still equip **two module hardpoints** and can optionally toggle **Crafted head** for a blueprint Pitman',
      'The **selected loadout** label above the calculator shows which setup Smart Cracker will use. Open Smart Cracker to change ship, slot, or edit modules',
      '**Mining Guide → By Ore**: filter by rarity, open an ore for composition and locations, jump to RS Tracker cards from location chips',
      '**Mining Guide → By Location**: pick a site and see which ores can spawn there, with spawn %, cluster odds, and composition tooltips',
      '**All Sites / Surface / Asteroid** filter narrows both guide views by deposit type — pick Asteroid to skip planetary weather when soloing a Mole',
      'Belt and cluster tooltips include a 📍 **find-it-in-game** hint: which QT markers or starmap search terms to use (e.g. Akiro Cluster sits near Pyro I L3)',
      'Click a belt/cluster location to open its **QT markers & stations** panel — organized by belt L-point or Pyro region (PYAM stations per Lagrange point, RAB/RMB cluster bases per region, BRK breaker stations) instead of one long list',
      'Chips marked **trace spawn (<0.01%)** are technically possible but effectively never worth farming — they sort last and appear dimmed',
      'Some regions use an **Overall** summary (e.g. broad asteroid cluster families) instead of listing every vague bucket as its own site',
      'Hand-mineable **gems** show cave vs surface availability per planet. Gems and hand mineables are guide reference only — they are not in the RS signature grid yet',
      'Compare in-game cluster readings: cluster RS ≈ node count × base RS on your reference card',
      '**Ledgers** (RSI-verified): create a book for a mining run, add rows per ore/gem with quantity and quality tier — matching ore + quality merges into one line',
      'Assign **crew** with RSI handles (green = verified member here, yellow = valid RSI not on site, red = fix before paying). Split by shares; **0 shares** members can get alternate compensation instead of pool aUEC',
      'Track deductibles and other profits, record **Paid so far** for partial payouts, mark crew **paid** when settled. Click payout or outstanding amounts to copy aUEC to clipboard',
      'Ledger managers can **share access** with other RSI-verified members. Crew and managers get site notifications for access, ledger close, and payout updates',
      '**Export JSON** saves a ledger snapshot; **View JSON** loads a saved file read-only. Close when everyone is paid or delete from the toolbar anytime',
      'Closed crew ledgers contribute to **lifetime site totals** shown on the Ledgers tab',
      'Signed-in members sync tracker cards and loadouts. **Offline Mode** still lets you browse RS reference and the Mining Guide locally',
    ],
    relatesTo: ['Resource Tracker', 'My Listings'],
  },
  {
    id: 'orders',
    title: 'My Listings',
    description: 'Manage your one WTB buy listing and one WTS sell listing, plus every transaction they create.',
    details: [
      'You have at most one open WTB listing and one open WTS listing — posting new items appends them to the matching listing',
      'Click Post items to open the builder for blueprints and/or resources; Add to my WTB listing requests items, Add to my WTS listing offers stock on hand',
      'All pricing is exact DFP — no price sliders or adjustments; the live total and effective stat preview update as you compose the cart',
      'Expand any cart line to edit per-slot material qualities and see stat changes before posting',
      'Add blueprints from the Blueprints page into a session draft, then continue on My Listings',
      'My open listings shows each listing\'s lines — change quantities or remove lines inline; removing the last line closes the listing',
      'Every listing is always partially shoppable: buyers and fulfillers pick lines and quantities on The Bazaar',
      'Each purchase or fulfillment claim becomes its own child transaction with the normal handoff, deadlines, ratings, and rep limits',
      'Active transactions show itemized materials and resulting stats (base → final) for blueprint lines',
      'Release or cancel in-progress sales — claimed items restore to your listing with quantities intact',
      'Track active, completed, and archived transactions; confirm pickup on Active, then archive & rate on Completed',
      'After pickup, open the Completed tab — each order shows a purple Archive & rate button; both parties must rate to unlock new trades',
      'Requires a verified RSI Handle; new-member buyer limits apply per transaction, not to your open listings',
      'Offline Mode cannot create or manage listings',
    ],
    relatesTo: ['Resource Tracker', 'The Bazaar', 'Blueprints', 'Discord Webhooks'],
  },
  {
    id: 'The Bazaar',
    title: 'The Bazaar',
    description: 'Shop members\' WTS listings and fulfill WTB requests — pick exactly the items you want.',
    details: [
      'Two tabs: Fulfillment (WTB listings you can craft/supply for) and Store (WTS listings you can buy from)',
      'Search by item name and filter by minimum quality band — a listing matches if any of its lines match',
      'Fulfillment tab extras: min buyer rep filter and "Only listings with my blueprints" (you only need blueprints for the lines you pick)',
      'Listings collapse to a compact summary row (title, tag, member, price, rep) — click to expand line details; only one expands at a time',
      'Every listing is item-by-item: check lines, set quantities, and buy or claim only what you want — the rest stays listed',
      'Each checkout or fulfillment claim becomes its own transaction through the normal handoff, pickup, and rating flow',
      'Active transactions show the other party\'s in-game name — add them in Star Citizen to coordinate pickup',
      'Seller-side WTS: actions and status appear directly on each sale card — start handoff, mark ready, or cancel',
      'After marking a WTS sale ready, wait for the buyer to confirm pickup in My Listings → Active',
      'Rate completed trades on The Bazaar or My Listings → Completed — purple Archive & rate on each finished deal',
      'Cancel or release returns claimed items to the owner\'s listing with quantities restored',
      'Same reputation ratings for all paths; visible fulfiller/seller rep shows average delivery time (ddd:HH:mm from accept to ready) after 5 completed trades',
      'Requires a verified RSI Handle; fulfiller and buyer pending limits apply by role per transaction',
      'Offline Mode shows an open-listing count teaser only — sign in to browse or trade',
      'Verify you have materials before claiming 800+ quality WTB blueprint lines',
      'Marketplace listing ads can deep-link here with ?highlight= — the matching listing expands and scrolls into view',
    ],
    relatesTo: ['My Listings', 'Resource Tracker', 'Settings'],
  },
  {
    id: 'discord-webhooks',
    title: 'Discord Webhooks',
    description: 'Route marketplace and personal deal alerts to your own Discord channel.',
    details: [
      'Paste a webhook URL from your Discord server (Integrations → Webhooks)',
      'My activity: pings when someone else moves your deal forward (accepted, ready, completed, released, etc.) — requires verified RSI Handle',
      'Marketplace activity (opt-in): new WTB/WTS listings, acceptances, and cancellations from other members — no RSI verification required',
      'Use the same channel URL in both sections if you want everything in one Discord channel',
      'Coalesced marketplace digests require New WTB, New WTS, or Listing cancelled — not Listing accepted alone',
      'You never receive marketplace pings for your own posts or actions (no self-echo)',
      'Order alerts include itemized lines with material summaries and effective stats when available',
      'Repeated post/cancel bursts from the same member may arrive as one grouped marketplace ping',
      'Support: staff replies and ticket resolved notices on your tickets',
      'One channel name and webhook URL per alert type — leave the URL blank to unregister',
      'Set up from your avatar menu → Webhooks after sign-in',
    ],
    relatesTo: ['My Listings', 'The Bazaar', 'Notifications'],
  },
  {
    id: 'notifications',
    title: 'Notifications',
    description: 'In-app alerts for marketplace activity from the header bell.',
    details: [
      'Bell icon in the header shows your unread notification count',
      'Notifications are grouped into collapsible categories — BP Dumper, WTB & Craft Orders, WTS Listings, Support, Mining Ledgers, and more',
      'Every category stays visible even when empty; expand a section to see its alerts or a None placeholder',
      'Alerts cover marketplace events such as order acceptances, ready-for-pickup, and status changes',
      'Order alerts include a clickable link in the message — The Bazaar for seller/fulfiller actions, My Listings → Completed to archive & rate',
      'Itemized order summaries reflect blueprint stats and materials when the order includes them',
      'Click Clear on a notification to dismiss it — dismissed rows are deleted (no read history kept)',
      'Use Clear all to dismiss every notification at once',
      'Unavailable while your account is pending approval',
    ],
    relatesTo: ['My Listings', 'The Bazaar'],
  },
  {
    id: 'settings',
    title: 'Settings',
    description: 'Manage your profile and account from your avatar menu.',
    details: [
      'Set or update your RSI Handle for verification and orders',
      'Deduct inventory on craft complete: when enabled, finishing a WTB fulfillment deducts materials from My Resources (requires verified RSI Handle)',
      'Connect Google or Discord from Connected Accounts to sign in with either method on one account',
      'When provider emails match, sign-in automatically merges into your existing account',
      'Disconnect a linked provider from Settings if you have at least two sign-in methods connected',
      'Clear Collected Blueprints to reset your acquired blueprint list (starter blueprints may reappear on refresh)',
      'Clear Tracked Resources to wipe all quantities and notes from My Resources in the Resource Tracker',
      'Marketplace section (when an admin enables site-wide features): opt in or out of WTS listing ads, WTB listing ads, and live purchase toasts independently',
      'Live purchase toasts only show accepts while you are online — there is no backlog for missed events',
    ],
    relatesTo: ['Blueprints', 'Mission Tracker', 'Resource Tracker', 'Mining Tracker', 'BP Dumper', 'The Bazaar'],
  },
  {
    id: 'bp-dumper',
    title: 'Dumper Apps',
    description: 'Desktop log watcher that automatically syncs blueprint unlocks to your account.',
    details: [
      'Open from Mission Tracker header buttons — BP Dumper for setup, Live Tracker for the live page — or the avatar menu',
      '**Windows:** download **Windows installer** (under Downloads), run the setup wizard, then open **Dumper Apps** from the Start Menu',
      'Copy your API key from this page and paste it when Dumper Apps asks on first run',
      'Regenerate your API key if compromised; the old key stops working immediately',
      'While watch mode runs, use Live Tracker to see active missions and remaining pool blueprints',
      'Successful imports appear under BP Dumper — Success in the notification bell',
    ],
    relatesTo: ['Blueprints', 'Mission Tracker', 'Live Mission Tracker', 'Mining Tracker', 'Notifications', 'Settings'],
  },
  {
    id: 'support',
    title: 'Support',
    description: 'Report issues or get help from site staff.',
    details: [
      'Access Support from your user menu (click your avatar)',
      'Report bugs or technical issues with the site',
      'Report inappropriate behavior from other members',
      'Get help with RSI Handle verification issues',
      'View the status of your open tickets and respond to staff questions',
      'All ticket data is deleted after resolution for your privacy',
    ],
    relatesTo: ['Settings', 'Blueprints'],
  },
  {
    id: 'components',
    title: 'Component Database',
    description: 'Browse ship components by type, size, grade, and manufacturer.',
    details: [
      'Filter by component type: coolers, power plants, shields, quantum drives',
      'Browse by size (S1-S4) and grade (A-D)',
      'See manufacturer information for each component',
      'Click any component to view detailed stats',
      'Compare upgrade paths between similar components',
    ],
    relatesTo: ['Blueprints'],
  },
  {
    id: 'ordnance',
    title: 'Ordnance Reference',
    description: 'Compare missiles and torpedoes by size, guidance type, and manufacturer.',
    details: [
      'Browse all missiles and torpedoes in the game',
      'Filter by guidance type: Cross-Section (CS), Electromagnetic (EM), Infrared (IR)',
      'Filter by size (S1-S9) to find compatible ordnance for your ship',
      'See manufacturer and full designation for each missile',
      'Understand guidance system differences for combat effectiveness',
    ],
    relatesTo: ['Blueprints', 'Component Database'],
  },
  {
    id: 'factions',
    title: 'Faction Reference',
    description: 'Understand reputation systems, standing tiers, and blueprint rewards.',
    details: [
      'View all factions and their reputation tiers',
      'See the reputation points required for each standing level',
      'Understand how faction standing affects blueprint availability',
      'Plan your reputation grind based on desired blueprints',
      'Cross-reference with Mission Tracker for efficient progression',
    ],
    relatesTo: ['Mission Tracker', 'Blueprints'],
  },
  {
    id: 'lore',
    title: 'Resource Lore',
    description: 'In-game flavor text and descriptions for commodities, ship components, armor, weapons, and more.',
    details: [
      'Browse lore for ores, commodities, ship components, armor, weapons, and flair items',
      'Search entries by name or description text',
      'Filter by category to explore related items and materials',
      'Learn the in-universe backstory for gear you use and resources you trade',
      'Data sourced directly from Star Citizen game files',
    ],
    relatesTo: ['Resource Tracker', 'Mining Tracker'],
  },
  {
    id: 'general',
    title: 'General Archive',
    description: 'External resources, quick tips, and data attribution.',
    details: [
      'Links to useful Star Citizen community resources',
      'Quick tips for mining, trading, and crafting',
      'Data source attribution and acknowledgments',
      'Information about how Dumper\'s Repo data is sourced and updated',
    ],
    relatesTo: ['Component Database', 'Resource Lore'],
  },
]
