export type ArchivePageGuide = {
  id: string
  title: string
  description: string
  details: string[]
  relatesTo: string[]
}

export const PAGE_GUIDES: ArchivePageGuide[] = [
  {
    id: 'blueprints',
    title: 'Blueprints',
    description: 'The main hub for browsing all available crafting blueprints in Star Citizen.',
    details: [
      'Browse and filter blueprints by type, manufacturer, and availability',
      'Material filter (cyan): type or pick any crafting material to show blueprints that require it — runs before category filters',
      'Search, category, material, and acquisition filters are remembered when you return (per account in this browser; Offline Mode uses local guest storage)',
      'See what reputation level is required to unlock each blueprint',
      'Mark blueprints as "acquired" to track your collection progress',
      'Missions on reward blueprints lists every contract that drops it and opens Browse Missions',
      'View the resources and components required to craft each item',
      'Click any blueprint to see detailed crafting requirements and DFP values',
      'Use the quality sliders to preview how resource quality affects final stats and DFP pricing',
      'Add a blueprint to your order draft from the detail view — continue on Custom Orders',
      'Optional Display setting: group FPS weapon and armor variants into expandable family cards (off by default; only affects visible FPS items on this page)',
      'Acquired marks from BP Dumper sync here automatically — set up BP Dumper on Mission Tracker',
      'Offline Mode: acquired marks save locally until you sign in',
    ],
    relatesTo: ['Mission Tracker', 'Resource Tracker', 'Custom Orders', 'Settings'],
  },
  {
    id: 'targets',
    title: 'Mission Tracker',
    description: 'Your personal wishlist of blueprints you\'re working towards unlocking.',
    details: [
      'Track blueprints from the main Blueprints page',
      'Browse Missions: pick a faction, then browse its mission pools',
      'Missions with multiple regional pools are grouped under one title with location rows underneath',
      'Faction cards show which star systems that faction appears in',
      'See X/X progress (owned vs total) for each mission location',
      'Add unowned blueprints to your tracker directly from the browse view',
      'Use Missions on a blueprint card to list every contract that rewards it and jump to that mission',
      'My Tracker: view your tracked blueprints and build a mission checklist',
      'Mission rows use color-coded tags — see the legend below when this section is expanded',
      'Location tags: violet system/region tags plus green planet/moon tags (no tooltips)',
      'System-wide missions show only the system name (e.g. Pyro); region missions add Pyro A/B/C/D plus locations',
      'Other tags: amber category, cyan rep requirement, red illegal, purple unlock level under blueprint names',
      'Investigation missions are mostly Hockrow Agency\'s Jorrit Dossier line at ASD\'s Onyx Facility (Stanton)',
      'Jorrit Dossier is a linear story chain — complete each step to unlock the next; repeat runs drop blueprints',
      'Collection missions include Wikelo Emporium craft contracts in Stanton (turn in gathered items for blueprints)',
      'BHG Hathor PAF bounties (Verified Bounty · Hathor · Planetary Alignment Facility) resolve to Stanton — Daymar and Aberdeen platform sites',
      'Prioritize which factions to grind based on your goals',
      'Header buttons: BP Dumper (downloads + API key) and Live Tracker (active in-game missions while watching)',
      'Dismissible callout explains the BP Dumper + Live Tracker workflow',
      'Offline Mode: list saves locally until you sign in (then migrates automatically)',
    ],
    relatesTo: ['Blueprints', 'Factions', 'BP Dumper', 'Live Mission Tracker'],
  },
  {
    id: 'targets-live',
    title: 'Live Mission Tracker',
    description: 'Real-time view of in-game missions and pool blueprints still to acquire while BP Dumper is watching.',
    details: [
      'Open from Mission Tracker header buttons (BP Dumper + Live Tracker) or the avatar menu (BP Dumper only)',
      'Requires BP Dumper running in watch mode with your API key',
      'Left column: missions you accepted in-game right now',
      'Right column: pool blueprints from those missions you have not acquired yet',
      'Updates instantly when you accept missions, finish them, or receive blueprints',
      'Color-coded status bar: connected in the PU, quit to menu, game closed, crash recovery, or back online',
      'Quit to menu or closing Star Citizen clears active missions until you load back into the PU',
      'After a crash, the bar waits for reconnect — missions may restore only if you rejoin within one hour',
      'When that hour has passed, tracking returns to normal while BP Dumper keeps watching your log',
      'Missions with no remaining pool blueprints show in red',
      'When BP Dumper stops or disconnects, lists clear and a not-connected message appears',
    ],
    relatesTo: ['Mission Tracker', 'BP Dumper', 'Blueprints'],
  },
  {
    id: 'resources',
    title: 'Resource Tracker',
    description: 'Track your personal inventory of mined and refined resources.',
    details: [
      'Log quantities and quality levels of resources you\'ve collected',
      'Track store-purchased refined materials at Purchased (Q0)',
      'Switch between Cards (edit quantities) and List (read-only overview with notes)',
      'Filter by quality band on both views — each Q-tier stays on its own row',
      'Mined/refined ore uses quality bands (typically Q500–Q1000) — higher quality = exponentially higher DFP value',
      'Salvage and trade goods use fixed Q0 tiers',
      'Perfect for tracking what you have available for crafting or trading',
      'Offline Mode: inventory saves locally until you sign in (then migrates automatically)',
    ],
    relatesTo: ['Blueprints', 'Mining Tracker'],
  },
  {
    id: 'mining-tracker',
    title: 'Mining Tracker',
    description:
      'Compare RS signatures, plan rocks with the calculator, get loadout advice, browse where ores spawn, and run crew payout ledgers.',
    details: [
      'Three tabs: **RS Tracker** (signature reference + tools on the right), **Mining Guide** (browse ores and locations), and **Ledgers** (crew payout books — RSI-verified members only)',
      '**RS Tracker** lists each ship-mining ore\'s base RS signature and typical cluster spawn odds. Use it to sanity-check what your in-game scanner is showing',
      'Track up to two cards per ore — **Surface** and **Asteroid** — each with composition bands, cluster rows, and spawn context. Add cards with Track Surface / Track Asteroid on a card or from the Mining Guide',
      'Location-specific cards pin data to one site (header shows At [location]). Track a site from ore detail or location browse when you care about one belt or moon, not the whole profile',
      'Click any tracked card to load its ore, deposit type, location, and expected composition into the **Rock Calculator** — handy when you know the deposit type but are punching in a fresh fracture scan',
      '**Rock Calculator** (RS Tracker sidebar): enter **mass**, **resistance**, and **instability** from your HUD for breakability and power-required readouts',
      'Enter **total rock SCU** and each material\'s **%** from your scan. **Inert** fills automatically as whatever remains after valuable lines — you do not type inert manually',
      'Many ores show the primary element twice (**High** and **Low** bands) as separate rows — match the two composition lines from your scanner',
      'Each material row has a **Q band** picker for ledger export. The **DFP** column beside each row is always fair-value at purchased (Q0) so you can compare yield value without changing bands',
      'Search for an ore or load from a tracked card. Toggle **Surface / Asteroid** when the ore has both deposit types. The **location** dropdown lists known spawn sites for that ore and type',
      '**Scanner OCR** (button in the calculator header): ALT+PrtSc the in-game SCAN RESULTS panel, paste here with Ctrl+V, crop the **entire** RESULTS block (include the word **RESULTS** and the ore name under it), and **Process** to auto-fill mass, resistance, instability, SCU, composition %, and Q bands. Primary ore comes from under RESULTS; duplicate composition lines for that ore are sorted High/Low by **smaller % = High**',
      'After OCR fill the calculator stays in **scan mode** until you pick an ore from search or click a tracked card again — deposit-type hints and expected % ranges stay hidden so scan data is not overwritten. The screenshot is never saved',
      'If a long material name hid the Q readout on your HUD (some overlay mods truncate names), you\'ll see a notice to set that row\'s Q band yourself',
      'Use **Tilt scan inside crop** in the OCR window when the panel looks skewed or quality numbers are clipped at the edge of your crop box',
      '**Smart Cracker** (button in the calculator header) opens a loadout planner and **automated crack advisor**. Enter rock mass and resistance in the calculator for breakability, gadget fit, and crew head plans — you can still open Smart Cracker anytime to edit loadouts',
      'Smart Cracker compares your selected ship and loadout against the rock, warns if a head cannot break it, flags **slow grinds** when full-blast power is only slightly over the equalizer (uses your composition Q bands to say if the wait is worth it), suggests **throttle and head assignments** (including multi-crew Mole setups), and recommends **one gadget per rock** with alternates for different jobs (fracture power, instability, charge window) — only one can be attached at a time',
      '**Mole crew** (Solo mining unchecked near the top of Smart Cracker, or **CHP** in the calculator header): lighter heads run **full @ 100%** first; the driver finishes at computed throttle just under the equalizer (6% under when all three contribute). Driver is picked by module stack and instability — not always the heaviest head',
      '**CHP** (Crew Head Plan) beside OCR opens a Mole crew head-plan modal when your calculator has mass/resistance and a Mole loadout is selected — same panel as Smart Cracker, without opening the full planner',
      '**Mole + Solo mining** (checkbox near the top of Smart Cracker): one laser at a time like a Prospector — per-head pro-tips appear on each hardpoint (collapsed by default on Mole; expand to read), plus a **Solo garage · 3-head spread** panel that labels heavy / daily / finesse roles and flags gaps (power tiers too close, no wide-window head, duplicate builds)',
      'Sign in to save loadouts to your account (works on any device). RSI verification is **not** required for Smart Cracker or loadouts — only for Ledgers',
      'Each ship has a factory **Default** loadout plus up to **three custom** slots. Swap heads and modules freely in Smart Cracker — changes preview live and **do not auto-save** until you click **Save** (custom slots) or **Save as New** (copies into the next custom slot; Default is never overwritten)',
      '**Premade build** dropdown loads org and community templates (Mole + Prospector) into the editor for tweaking — still requires Save or Save as New to keep changes',
      'Choose head models, mining modules (Focus, Rieger, FLTR, XTR, etc.), and optionally enter your **crafted mining head** stats if you run a blueprint head',
      '**Golem** ships use the factory **Pitman** head only (no swapping to other S1 models). Custom slots still equip **two module hardpoints** and can optionally toggle **Crafted head** for a blueprint Pitman',
      'The **selected loadout** label above the calculator shows which setup Smart Cracker will use. Open Smart Cracker to change ship, slot, or edit modules',
      '**Mining Guide → By Ore**: filter by rarity, open an ore for composition and locations, jump to RS Tracker cards from location chips',
      '**Mining Guide → By Location**: pick a site and see which ores can spawn there, with spawn %, cluster odds, and composition tooltips',
      'Some regions use an **Overall** summary (e.g. broad asteroid cluster families) instead of listing every vague bucket as its own site',
      'Hand-mineable **gems** show cave vs surface availability per planet. Gems and hand mineables are guide reference only — they are not in the RS signature grid yet',
      'Compare in-game cluster readings: cluster RS ≈ node count × base RS on your reference card',
      '**Ledgers** (RSI-verified): create a book for a mining run, add rows per ore/gem with quantity and quality tier — matching ore + quality merges into one line',
      'Assign **crew** with RSI handles (green = verified member here, yellow = valid RSI not on site, red = fix before paying). Split by shares; **0 shares** members can get alternate compensation instead of pool aUEC',
      'Track deductibles and other profits, record **Paid so far** for partial payouts, mark crew **paid** when settled. Click payout or outstanding amounts to copy aUEC to clipboard',
      'Ledger managers can **share access** with other RSI-verified members. Crew and managers get site notifications for access, ledger close, and payout updates',
      '**Export JSON** saves a ledger snapshot; **View JSON** loads a saved file read-only. Close when everyone is paid or delete from the toolbar anytime',
      'Closed crew ledgers contribute to **lifetime site totals** shown on the Ledgers tab',
      'Signed-in members sync tracker cards and loadouts. **Offline Mode** still lets you browse RS reference and the Mining Guide locally',
    ],
    relatesTo: ['Resource Tracker', 'Custom Orders'],
  },
  {
    id: 'orders',
    title: 'Custom Orders',
    description: 'Build, post, and manage WTB buy requests and WTS sell listings from one order form.',
    details: [
      'Click New order to open the order builder for blueprints and/or resources',
      'Submit Buy Order posts a WTB request (you want someone to craft or supply)',
      'Submit Sell Order posts a WTS listing (you are offering stock on hand)',
      'Live DFP total and effective stat preview while you compose the cart',
      'Expand any cart line to edit per-slot material qualities and see stat changes before posting',
      'Add blueprints from the Blueprints page into a session draft, then continue on Custom Orders',
      'WTS listings allow partial purchases by default — buyers pick lines and quantities on Fulfillment',
      'Check “Buyers must purchase the full listing” on WTS if the whole bundle must sell together',
      'WTS sellers can adjust list price with sliders: ±20% per line (partial listings) or ±10% on the order total (full listing only); 0% is the DFP base',
      'Same fields for both tags: lines, quality tiers, min reputation, notes, DFP pricing',
      'WTB/WTS tag and Partial OK / Full listing only badges shown on your orders',
      'Active and completed orders show itemized materials and resulting stats (base → final) for blueprint lines',
      'Edit or delete pending listings while no one has accepted',
      'Release or cancel in-progress WTS sales — partial purchases restore unsold qty to the listing',
      'Track active, completed, and archived orders; confirm pickup on Active, then archive & rate on Completed',
      'After pickup, open the Completed tab — each order shows a purple Archive & rate button; both parties must rate to unlock new orders',
      'Partial WTS purchases are full child orders — same handoff, deadlines, ratings, and rep limits',
      'Requires a verified RSI Handle; new-member buyer limits apply to WTB posts and WTS purchases',
      'Offline Mode cannot create or manage orders',
    ],
    relatesTo: ['Resource Tracker', 'Fulfillment', 'Blueprints', 'Discord Webhooks'],
  },
  {
    id: 'fulfillment',
    title: 'Fulfillment',
    description: 'Browse, filter, and act on other members\' WTB and WTS orders.',
    details: [
      'Main filter: All, WTB only, or WTS only',
      'Available orders collapse to a compact summary row (title, tag, buyer, price, rep) — click to expand blueprint details; only one order expands at a time',
      'WTB orders — accept to fulfill/craft for the buyer; expanded view shows materials and effective stats per line',
      'WTS full listings (Full listing only badge) — Buy listing accepts the entire offer at once',
      'WTS partial listings (Partial OK badge) — check lines, set quantities, and buy only what you want',
      'Each partial purchase becomes its own order through the normal handoff, pickup, and rating flow',
      'WTB/WTS and Partial OK / Full listing only badges on every row',
      'Active orders show the other party\'s in-game name — add them in Star Citizen to coordinate pickup',
      'Seller-side WTS: actions and status appear directly on each sale card — start handoff, mark ready, or cancel',
      'After marking a WTS sale ready, wait for the buyer to confirm pickup in Custom Orders → Active',
      'Rate completed orders in Fulfillment or Custom Orders → Completed — purple Archive & rate on each finished deal',
      'Buyer-side WTS: confirm pickup and archive/rate like any other purchase',
      'Cancel or release returns partial purchases to the seller\'s listing with quantities restored',
      'Same reputation ratings for all paths — no separate partial rating',
      'Visible fulfiller/seller rep shows average delivery time (ddd:HH:mm from accept to ready) after 5 completed trades',
      'Requires a verified RSI Handle; fulfiller and buyer pending limits apply by role',
      'Offline Mode shows a pending-order count teaser only — sign in to browse or accept',
      'Verify you have materials before accepting 800+ quality WTB blueprint orders',
      'Marketplace listing ads can deep-link here with ?highlight= — the matching pending order expands and scrolls into view',
    ],
    relatesTo: ['Custom Orders', 'Resource Tracker', 'Settings'],
  },
  {
    id: 'discord-webhooks',
    title: 'Discord Webhooks',
    description: 'Route marketplace and personal deal alerts to your own Discord channel.',
    details: [
      'Paste a webhook URL from your Discord server (Integrations → Webhooks)',
      'My activity: pings when someone else moves your deal forward (accepted, ready, completed, released, etc.) — requires verified RSI Handle',
      'Marketplace activity (opt-in): new WTB/WTS listings, acceptances, and cancellations from other members — no RSI verification required',
      'Use the same channel URL in both sections if you want everything in one Discord channel',
      'Coalesced marketplace digests require New WTB, New WTS, or Listing cancelled — not Listing accepted alone',
      'You never receive marketplace pings for your own posts or actions (no self-echo)',
      'Order alerts include itemized lines with material summaries and effective stats when available',
      'Repeated post/cancel bursts from the same member may arrive as one grouped marketplace ping',
      'Support: staff replies and ticket resolved notices on your tickets',
      'One channel name and webhook URL per alert type — leave the URL blank to unregister',
      'Set up from your avatar menu → Webhooks after sign-in',
    ],
    relatesTo: ['Custom Orders', 'Fulfillment', 'Notifications'],
  },
  {
    id: 'notifications',
    title: 'Notifications',
    description: 'In-app alerts for marketplace activity from the header bell.',
    details: [
      'Bell icon in the header shows your unread notification count',
      'Notifications are grouped into collapsible categories — BP Dumper, WTB & Craft Orders, WTS Listings, Support, Mining Ledger, and more',
      'Every category stays visible even when empty; expand a section to see its alerts or a None placeholder',
      'Alerts cover marketplace events such as order acceptances, ready-for-pickup, and status changes',
      'Order alerts include a clickable link in the message — Fulfillment for seller/fulfiller actions, Custom Orders → Completed to archive & rate',
      'Itemized order summaries reflect blueprint stats and materials when the order includes them',
      'Click Clear on a notification to dismiss it — dismissed rows are deleted (no read history kept)',
      'Use Clear all to dismiss every notification at once',
      'Unavailable while your account is pending approval',
    ],
    relatesTo: ['Custom Orders', 'Fulfillment'],
  },
  {
    id: 'settings',
    title: 'Settings',
    description: 'Manage your profile and account from your avatar menu.',
    details: [
      'Set or update your RSI Handle for verification and orders',
      'Deduct inventory on craft complete: when enabled, finishing a WTB fulfillment deducts materials from My Resources (requires verified RSI Handle)',
      'Connect Google or Discord from Connected Accounts to sign in with either method on one account',
      'When provider emails match, sign-in automatically merges into your existing account',
      'Disconnect a linked provider from Settings if you have at least two sign-in methods connected',
      'Clear Collected Blueprints to reset your acquired blueprint list (starter blueprints may reappear on refresh)',
      'Clear Tracked Resources to wipe all quantities and notes from My Resources in the Resource Tracker',
      'Marketplace section (when an admin enables site-wide features): opt in or out of WTS listing ads, WTB listing ads, and live purchase toasts independently',
      'Live purchase toasts only show accepts while you are online — there is no backlog for missed events',
    ],
    relatesTo: ['Blueprints', 'Mission Tracker', 'Resource Tracker', 'Mining Tracker', 'BP Dumper', 'Fulfillment'],
  },
  {
    id: 'bp-dumper',
    title: 'BP Dumper',
    description: 'Desktop log watcher that automatically syncs blueprint unlocks to your account.',
    details: [
      'Open from Mission Tracker header buttons — BP Dumper for setup, Live Tracker for the live page — or the avatar menu',
      'Download Windows, macOS (Intel or Apple Silicon), Linux, or the Python script zip from GitHub releases',
      'Copy or reveal your personal API key in the modal — paste it into BP Dumper on first run',
      'Regenerate your key if compromised; the old key stops working immediately',
      'Run watch mode while you play; use Live Tracker on Mission Tracker to see active missions and remaining pool blueprints',
      'Watch mode reads Game.log for blueprint unlocks, mission accept/end events, and session changes (menu, quit, crash)',
      'Successful imports appear under BP Dumper — Success in the notification bell; ambiguous names may need manual review',
    ],
    relatesTo: ['Blueprints', 'Mission Tracker', 'Live Mission Tracker', 'Notifications', 'Settings'],
  },
  {
    id: 'support',
    title: 'Support',
    description: 'Report issues or get help from site staff.',
    details: [
      'Access Support from your user menu (click your avatar)',
      'Report bugs or technical issues with the site',
      'Report inappropriate behavior from other members',
      'Get help with RSI Handle verification issues',
      'View the status of your open tickets and respond to staff questions',
      'All ticket data is deleted after resolution for your privacy',
    ],
    relatesTo: ['Settings', 'Blueprints'],
  },
  {
    id: 'components',
    title: 'Component Database',
    description: 'Browse ship components by type, size, grade, and manufacturer.',
    details: [
      'Filter by component type: coolers, power plants, shields, quantum drives',
      'Browse by size (S1-S4) and grade (A-D)',
      'See manufacturer information for each component',
      'Click any component to view detailed stats',
      'Compare upgrade paths between similar components',
    ],
    relatesTo: ['Blueprints'],
  },
  {
    id: 'ordnance',
    title: 'Ordnance Reference',
    description: 'Compare missiles and torpedoes by size, guidance type, and manufacturer.',
    details: [
      'Browse all missiles and torpedoes in the game',
      'Filter by guidance type: Cross-Section (CS), Electromagnetic (EM), Infrared (IR)',
      'Filter by size (S1-S9) to find compatible ordnance for your ship',
      'See manufacturer and full designation for each missile',
      'Understand guidance system differences for combat effectiveness',
    ],
    relatesTo: ['Blueprints', 'Component Database'],
  },
  {
    id: 'factions',
    title: 'Faction Reference',
    description: 'Understand reputation systems, standing tiers, and blueprint rewards.',
    details: [
      'View all factions and their reputation tiers',
      'See the reputation points required for each standing level',
      'Understand how faction standing affects blueprint availability',
      'Plan your reputation grind based on desired blueprints',
      'Cross-reference with Mission Tracker for efficient progression',
    ],
    relatesTo: ['Mission Tracker', 'Blueprints'],
  },
  {
    id: 'lore',
    title: 'Resource Lore',
    description: 'In-game flavor text and descriptions for commodities, ship components, armor, weapons, and more.',
    details: [
      'Browse lore for ores, commodities, ship components, armor, weapons, and flair items',
      'Search entries by name or description text',
      'Filter by category to explore related items and materials',
      'Learn the in-universe backstory for gear you use and resources you trade',
      'Data sourced directly from Star Citizen game files',
    ],
    relatesTo: ['Resource Tracker', 'Mining Tracker'],
  },
  {
    id: 'general',
    title: 'General Archive',
    description: 'External resources, quick tips, and data attribution.',
    details: [
      'Links to useful Star Citizen community resources',
      'Quick tips for mining, trading, and crafting',
      'Data source attribution and acknowledgments',
      'Information about how Dumper\'s Repo data is sourced and updated',
    ],
    relatesTo: ['Component Database', 'Resource Lore'],
  },
]
