import { readFileSync, writeFileSync } from 'fs'
import { dirname, join } from 'path'
import { fileURLToPath, pathToFileURL } from 'url'
import { resolveGameBuildVersion, toMinGameVersionSecret } from './gameBuildVersion.mjs'

const __dirname = dirname(fileURLToPath(import.meta.url))
const PROJECT_ROOT = join(__dirname, '..', '..')
const PY_MIN_VERSION = join(PROJECT_ROOT, 'scripts', 'bp-dumper-py', '_min_game_version.py')
const GO_MIN_VERSION = join(PROJECT_ROOT, 'scripts', 'bp-dumper-go', 'mingame.txt')
const GAME_BUILD_FILE = join(PROJECT_ROOT, 'src', 'data', 'game-build-version.json')

function readCommittedGameBuildVersion() {
  try {
    const data = JSON.parse(readFileSync(GAME_BUILD_FILE, 'utf8'))
    return typeof data?.version === 'string' ? data.version : null
  } catch {
    return null
  }
}

/**
 * Bake major.minor into BP Dumper for the recent-import filter only
 * (IMPORT_OLD_LOGS / first-run backup prompt). Full history and live watch do not use this.
 */
export function syncDumperMinGameVersion(version, options = {}) {
  const minVersion = toMinGameVersionSecret(version)
  if (!minVersion) {
    console.warn('  ⚠ Skipping dumper MIN_GAME_VERSION sync: no major.minor version available')
    return { skipped: true, reason: 'no-version' }
  }

  if (options.dryRun) {
    console.log(`  [dry-run] Would set dumper MinGameVersion=${minVersion}`)
    return { dryRun: true, minVersion }
  }

  writeFileSync(
    PY_MIN_VERSION,
    `# Generated by scripts/lib/syncDumperMinGameVersion.mjs — do not edit.\nMIN_GAME_VERSION = "${minVersion}"\n`
  )
  writeFileSync(GO_MIN_VERSION, `${minVersion}\n`)

  console.log(`  ✓ BP Dumper MinGameVersion set to ${minVersion}`)
  return { synced: true, minVersion }
}

async function runCli() {
  const extractedData = join(PROJECT_ROOT, 'extracted-data')
  const version =
    process.argv.find((arg) => /^\d+\.\d+(\.x)?$/.test(arg)) ??
    resolveGameBuildVersion({ extractedData, projectRoot: PROJECT_ROOT }) ??
    readCommittedGameBuildVersion()

  const dryRun = process.argv.includes('--dry-run')
  const result = syncDumperMinGameVersion(version, { dryRun })
  if (result.skipped) {
    process.exit(1)
  }
}

const isDirectRun = process.argv[1] && import.meta.url === pathToFileURL(process.argv[1]).href
if (isDirectRun) {
  runCli().catch((err) => {
    console.error('Fatal error:', err)
    process.exit(1)
  })
}
