-- Dumper's Repo greenfield baseline (001) — core identity & auth
-- Fresh install only. Do not run on databases that already applied migrations_legacy 001-041.

-- =============================================================================
-- profiles (baseline — was pre-existing before incremental migrations)
-- =============================================================================

CREATE TABLE IF NOT EXISTS public.profiles (
  id uuid PRIMARY KEY REFERENCES auth.users(id) ON DELETE CASCADE,
  email text,
  display_name text,
  avatar_url text,
  rsi_handle text,
  role text NOT NULL DEFAULT 'pending'
    CHECK (role IN ('pending', 'member', 'officer', 'super-admin')),
  created_at timestamptz NOT NULL DEFAULT now(),
  approved_at timestamptz,
  approved_by uuid REFERENCES public.profiles(id) ON DELETE SET NULL,
  ghost_mode boolean NOT NULL DEFAULT false,
  preview_features_enabled boolean NOT NULL DEFAULT false,
  craft_deduct_inventory boolean NOT NULL DEFAULT false
);

CREATE INDEX IF NOT EXISTS profiles_ghost_mode_idx
  ON public.profiles (ghost_mode)
  WHERE ghost_mode = true;

ALTER TABLE public.profiles ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "profiles_select_authenticated" ON public.profiles;
CREATE POLICY "profiles_select_authenticated"
  ON public.profiles FOR SELECT TO authenticated
  USING (true);

DROP POLICY IF EXISTS "profiles_update_own" ON public.profiles;
CREATE POLICY "profiles_update_own"
  ON public.profiles FOR UPDATE TO authenticated
  USING (id = auth.uid())
  WITH CHECK (id = auth.uid());

DROP POLICY IF EXISTS "profiles_update_officers" ON public.profiles;
CREATE POLICY "profiles_update_officers"
  ON public.profiles FOR UPDATE TO authenticated
  USING (
    EXISTS (
      SELECT 1 FROM public.profiles p
      WHERE p.id = auth.uid() AND p.role IN ('officer', 'super-admin')
    )
  )
  WITH CHECK (
    EXISTS (
      SELECT 1 FROM public.profiles p
      WHERE p.id = auth.uid() AND p.role IN ('officer', 'super-admin')
    )
  );

-- =============================================================================
-- acquired_blueprints
-- =============================================================================

CREATE TABLE IF NOT EXISTS public.acquired_blueprints (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id uuid NOT NULL REFERENCES public.profiles(id) ON DELETE CASCADE,
  blueprint_id text NOT NULL,
  acquired_at timestamptz NOT NULL DEFAULT now(),
  UNIQUE (user_id, blueprint_id)
);

CREATE INDEX IF NOT EXISTS acquired_blueprints_user_idx
  ON public.acquired_blueprints (user_id);

ALTER TABLE public.acquired_blueprints ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "acquired_blueprints_select" ON public.acquired_blueprints;
CREATE POLICY "acquired_blueprints_select"
  ON public.acquired_blueprints FOR SELECT TO authenticated
  USING (true);

DROP POLICY IF EXISTS "acquired_blueprints_insert_own" ON public.acquired_blueprints;
CREATE POLICY "acquired_blueprints_insert_own"
  ON public.acquired_blueprints FOR INSERT TO authenticated
  WITH CHECK (user_id = auth.uid());

DROP POLICY IF EXISTS "acquired_blueprints_update_own" ON public.acquired_blueprints;
CREATE POLICY "acquired_blueprints_update_own"
  ON public.acquired_blueprints FOR UPDATE TO authenticated
  USING (user_id = auth.uid())
  WITH CHECK (user_id = auth.uid());

DROP POLICY IF EXISTS "acquired_blueprints_delete_own" ON public.acquired_blueprints;
CREATE POLICY "acquired_blueprints_delete_own"
  ON public.acquired_blueprints FOR DELETE TO authenticated
  USING (user_id = auth.uid());

-- =============================================================================
-- Role helpers (006)
-- =============================================================================

CREATE OR REPLACE FUNCTION public.get_current_user_role()
RETURNS text
LANGUAGE sql STABLE SECURITY DEFINER SET search_path = public
AS $$ SELECT role FROM public.profiles WHERE id = auth.uid(); $$;

CREATE OR REPLACE FUNCTION public.is_super_admin()
RETURNS boolean
LANGUAGE sql STABLE SECURITY DEFINER SET search_path = public
AS $$ SELECT COALESCE(public.get_current_user_role(), '') = 'super-admin'; $$;

-- Member ban system: banned_users table, RLS, ban_member RPC
-- Run in Supabase SQL Editor (Dashboard → SQL → New query)

-- =============================================================================
-- banned_users table
-- =============================================================================

CREATE TABLE IF NOT EXISTS public.banned_users (
  id uuid PRIMARY KEY,
  email text,
  display_name text,
  rsi_handle text,
  avatar_url text,
  banned_at timestamptz NOT NULL DEFAULT now(),
  banned_by uuid REFERENCES public.profiles(id) ON DELETE SET NULL,
  reason text
);

CREATE INDEX IF NOT EXISTS banned_users_email_idx ON public.banned_users (email);

ALTER TABLE public.banned_users ENABLE ROW LEVEL SECURITY;

-- Users can read their own ban record (client ban detection)
CREATE POLICY "banned_users_select_own"
  ON public.banned_users
  FOR SELECT
  TO authenticated
  USING (id = auth.uid());

-- Officers and super-admins can read all ban records (audit tab)
CREATE POLICY "banned_users_select_officers"
  ON public.banned_users
  FOR SELECT
  TO authenticated
  USING (
    EXISTS (
      SELECT 1 FROM public.profiles
      WHERE profiles.id = auth.uid()
        AND profiles.role IN ('officer', 'super-admin')
    )
  );

-- No INSERT/UPDATE/DELETE policies for clients — only ban_member RPC inserts

-- =============================================================================
-- Block banned users from profiles and acquired_blueprints (RESTRICTIVE)
-- =============================================================================

-- Helper: true when the current session user is on the ban list
CREATE OR REPLACE FUNCTION public.is_current_user_banned()
RETURNS boolean
LANGUAGE sql
STABLE
SECURITY DEFINER
SET search_path = public
AS $$
  SELECT EXISTS (
    SELECT 1 FROM public.banned_users WHERE id = auth.uid()
  );
$$;

-- RESTRICTIVE policies deny access when the caller is banned
CREATE POLICY "profiles_deny_banned"
  ON public.profiles
  AS RESTRICTIVE
  FOR ALL
  TO authenticated
  USING (NOT public.is_current_user_banned());

CREATE POLICY "acquired_blueprints_deny_banned"
  ON public.acquired_blueprints
  AS RESTRICTIVE
  FOR ALL
  TO authenticated
  USING (NOT public.is_current_user_banned());

-- =============================================================================
-- ban_member RPC
-- =============================================================================

CREATE OR REPLACE FUNCTION public.ban_member(
  target_user_id uuid,
  reason text DEFAULT NULL
)
RETURNS jsonb
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS $$
DECLARE
  caller_role text;
  target_role text;
  profile_row public.profiles%ROWTYPE;
BEGIN
  SELECT role INTO caller_role
  FROM public.profiles
  WHERE id = auth.uid();

  IF caller_role IS NULL OR caller_role NOT IN ('officer', 'super-admin') THEN
    RAISE EXCEPTION 'Permission denied: officer or super-admin required';
  END IF;

  IF target_user_id = auth.uid() THEN
    RAISE EXCEPTION 'Cannot ban yourself';
  END IF;

  SELECT * INTO profile_row
  FROM public.profiles
  WHERE id = target_user_id;

  IF NOT FOUND THEN
    RAISE EXCEPTION 'User not found';
  END IF;

  target_role := profile_row.role;

  IF target_role = 'super-admin' THEN
    RAISE EXCEPTION 'Cannot ban a super-admin';
  END IF;

  DELETE FROM public.acquired_blueprints
  WHERE user_id = target_user_id;

  INSERT INTO public.banned_users (
    id, email, display_name, rsi_handle, avatar_url,
    banned_at, banned_by, reason
  )
  VALUES (
    profile_row.id,
    profile_row.email,
    profile_row.display_name,
    profile_row.rsi_handle,
    profile_row.avatar_url,
    now(),
    auth.uid(),
    reason
  );

  DELETE FROM public.profiles
  WHERE id = target_user_id;

  RETURN jsonb_build_object('success', true, 'banned_user_id', target_user_id);
END;
$$;

REVOKE ALL ON FUNCTION public.ban_member(uuid, text) FROM PUBLIC;
GRANT EXECUTE ON FUNCTION public.ban_member(uuid, text) TO authenticated;

-- Super-admin unban: remove from banned_users, restore profile as pending
-- Run in Supabase SQL Editor after 001_banned_users.sql

CREATE OR REPLACE FUNCTION public.unban_member(target_user_id uuid)
RETURNS jsonb
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS $$
DECLARE
  caller_role text;
  ban_row public.banned_users%ROWTYPE;
BEGIN
  SELECT role INTO caller_role
  FROM public.profiles
  WHERE id = auth.uid();

  IF caller_role IS DISTINCT FROM 'super-admin' THEN
    RAISE EXCEPTION 'Permission denied: super-admin required';
  END IF;

  SELECT * INTO ban_row
  FROM public.banned_users
  WHERE id = target_user_id;

  IF NOT FOUND THEN
    RAISE EXCEPTION 'User is not banned';
  END IF;

  IF EXISTS (SELECT 1 FROM public.profiles WHERE id = target_user_id) THEN
    RAISE EXCEPTION 'Profile already exists for this user';
  END IF;

  DELETE FROM public.banned_users
  WHERE id = target_user_id;

  INSERT INTO public.profiles (
    id, email, display_name, avatar_url, rsi_handle, role
  )
  VALUES (
    ban_row.id,
    ban_row.email,
    ban_row.display_name,
    ban_row.avatar_url,
    ban_row.rsi_handle,
    'pending'
  );

  RETURN jsonb_build_object('success', true, 'unbanned_user_id', target_user_id);
END;
$$;

REVOKE ALL ON FUNCTION public.unban_member(uuid) FROM PUBLIC;
GRANT EXECUTE ON FUNCTION public.unban_member(uuid) TO authenticated;

-- Self-service account deletion (does not modify banned_users)
-- Run in Supabase SQL Editor

CREATE OR REPLACE FUNCTION public.delete_own_account()
RETURNS jsonb
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS $$
DECLARE
  caller_id uuid;
  caller_role text;
BEGIN
  caller_id := auth.uid();

  IF caller_id IS NULL THEN
    RAISE EXCEPTION 'Not authenticated';
  END IF;

  IF EXISTS (SELECT 1 FROM public.banned_users WHERE id = caller_id) THEN
    RAISE EXCEPTION 'Banned accounts cannot be deleted through settings';
  END IF;

  SELECT role INTO caller_role
  FROM public.profiles
  WHERE id = caller_id;

  IF NOT FOUND THEN
    RAISE EXCEPTION 'Profile not found';
  END IF;

  IF caller_role = 'super-admin' THEN
    RAISE EXCEPTION 'Super-admin accounts cannot self-delete';
  END IF;

  -- Clear references from other profiles (approved_by has no ON DELETE SET NULL)
  UPDATE public.profiles
  SET approved_by = NULL
  WHERE approved_by = caller_id;

  DELETE FROM public.acquired_blueprints
  WHERE user_id = caller_id;

  DELETE FROM public.profiles
  WHERE id = caller_id;

  -- banned_users intentionally untouched (audit/blocklist preserved)

  RETURN jsonb_build_object('success', true, 'deleted_user_id', caller_id);
END;
$$;

REVOKE ALL ON FUNCTION public.delete_own_account() FROM PUBLIC;
GRANT EXECUTE ON FUNCTION public.delete_own_account() TO authenticated;

-- Ghost Mode preference on profiles
-- Run in Supabase SQL Editor

ALTER TABLE public.profiles
  ADD COLUMN IF NOT EXISTS ghost_mode boolean NOT NULL DEFAULT false;

CREATE INDEX IF NOT EXISTS profiles_ghost_mode_idx
  ON public.profiles (ghost_mode)
  WHERE ghost_mode = true;

-- handle_new_user + trigger (039 final)
CREATE OR REPLACE FUNCTION public.handle_new_user()
RETURNS trigger
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS $$
BEGIN
  IF EXISTS (SELECT 1 FROM public.banned_users WHERE id = NEW.id) THEN
    RAISE EXCEPTION 'This account has been banned';
  END IF;

  IF EXISTS (
    SELECT 1 FROM public.banned_users
    WHERE email IS NOT NULL AND email = NEW.email
  ) THEN
    RAISE EXCEPTION 'This email has been banned';
  END IF;

  INSERT INTO public.profiles (id, email, display_name, avatar_url, role)
  VALUES (
    NEW.id,
    NEW.email,
    COALESCE(NEW.raw_user_meta_data->>'full_name', NEW.raw_user_meta_data->>'name'),
    NEW.raw_user_meta_data->>'avatar_url',
    'pending'
  );

  RETURN NEW;
END;
$$;

DROP TRIGGER IF EXISTS on_auth_user_created ON auth.users;
CREATE TRIGGER on_auth_user_created
  AFTER INSERT ON auth.users
  FOR EACH ROW EXECUTE FUNCTION public.handle_new_user();
