-- =============================================================================
-- Migration 118: Drop game data mirror tables
--
-- The site now serves ALL game catalogs (mining guide, ordnance, components)
-- from the bundled parser output in src/data/*.json — the single source of
-- truth generated by `npm run parse-game-data`. The Supabase mirrors below
-- were only populated by scripts/sync-game-data-to-db.mjs (now removed) and
-- could silently drift from the bundled data between patch-day syncs.
--
-- Dropped here:
--   • game_mining              (mining guide — now bundled game-mining-locations.json)
--   • game_ordnance            (ordnance archive — now bundled game-ordnance.json)
--   • game_blueprint_pools     (never read by the app)
--   • game_blueprint_standings (never read by the app)
--   • game_sync_meta + get_game_data_sync_status() (sync bookkeeping, unused)
--
-- game_components was already dropped in migration 114.
-- =============================================================================

-- Dropping the function removes its grants; no REVOKE needed.
DROP FUNCTION IF EXISTS public.get_game_data_sync_status();

DROP POLICY IF EXISTS "Anyone can read game_mining" ON public.game_mining;
DROP POLICY IF EXISTS "Anyone can read game_ordnance" ON public.game_ordnance;
DROP POLICY IF EXISTS "Anyone can read game_blueprint_pools" ON public.game_blueprint_pools;
DROP POLICY IF EXISTS "Anyone can read game_blueprint_standings" ON public.game_blueprint_standings;
DROP POLICY IF EXISTS "Anyone can read game_sync_meta" ON public.game_sync_meta;

DROP TABLE IF EXISTS public.game_mining CASCADE;
DROP TABLE IF EXISTS public.game_ordnance CASCADE;
DROP TABLE IF EXISTS public.game_blueprint_pools CASCADE;
DROP TABLE IF EXISTS public.game_blueprint_standings CASCADE;
DROP TABLE IF EXISTS public.game_sync_meta CASCADE;
